const assert = require('node:assert/strict');
const fs = require('node:fs');
process.chdir(__dirname);

const account = fs.readFileSync('account.js','utf8');
const network = fs.readFileSync('network.js','utf8');
const engine = fs.readFileSync('engine-core.js','utf8');
const ui = fs.readFileSync('engine-ui.js','utf8');
const page = fs.readFileSync('index.html','utf8');
const schema = fs.readFileSync('supabase/schema.sql','utf8');
const responsive = fs.readFileSync('styles-responsive.css','utf8');

for (const id of ['account-card','account-name','account-flux','account-avatar','account-record','account-dialog','profile-icon-dialog','public-profile-dialog','profile-color-grid','profile-view-history','leaderboard-list','account-login','account-signup','p1-record','p2-record']) assert.match(page,new RegExp(`id="${id}"`));
assert.match(page, /@supabase\/supabase-js@2/);
assert.match(page, /account\.js\?v=9/);
assert.match(account, /#account-dialog'\)\?\.close\(\)/);
assert.match(page, /id="online-name-label"/);
assert.match(account, /onlineName\.classList\.toggle\('hidden',!!snapshot\)/);
assert.match(account, /persistSession:true/);
assert.match(account, /function accountLoginEmail/);
assert.doesNotMatch(page, /id="account-email"/);
assert.match(account, /function lookupAccountProfile/);
assert.match(account, /report_match_result/);
assert.match(account, /MAIS USADO:/);
assert.match(account, /function loadLeaderboard/);
assert.match(account, /set_profile_style/);
assert.match(account, /profileIconUrl/);
assert.match(account, /function availableProfileIcons/);
assert.match(account, /Object\.values\(defs\)/);
assert.match(account, /Object\.values\(effects\)/);
assert.match(account, /function openPublicProfile/);
assert.match(account, /get_player_profile/);
assert.match(account, /recentWins\/matches\.length\*100/);
assert.match(account, /profileColor/);
assert.match(account, /applyProfileColor\(card,snapshot\?\.profileColor\)/);
assert.match(responsive, /\.setup-header \.account-card \.account-avatar\{background:var\(--profile-color/);
assert.match(responsive, /\.public-profile-dialog \.dialog-close\{color:#fff\}/);
assert.match(account, /FLUX/);
assert.doesNotMatch(account, /\bELO\b/i);
assert.doesNotMatch(page, /\bELO\b/i);
assert.doesNotMatch(page, /Daniel Moon/);
assert.doesNotMatch(page, /PERFIL DO JOGADOR|JOGO DE CARTAS TÁTICO|>LEADERBOARD</);
assert.match(page, /leaderboard-title[^>]*>[\s\S]*?RANKING GLOBAL/);
assert.doesNotMatch(page, /Escolha uma cor de arquétipo|<small>PERSONALIZAR PERFIL<\/small>/);
assert.doesNotMatch(account, /\$\{profile\.wins\}V\/\$\{profile\.losses\}D/);
assert.match(account, /function leaderboardWinRates\(/);
assert.doesNotMatch(account, /profile-color-grid[\s\S]*?<span>\$\{accountDeckNames\[color\]\}<\/span>/);
assert.match(responsive, /\.profile-icon-grid\{grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);
assert.match(responsive, /@media\(max-width:760px\)\{\.setup-header\{min-height:0[\s\S]*?\.setup-header \.setup-brand\{display:none\}/, 'no celular o cabeçalho deve reservar espaço somente para a conta');
assert.match(account, /p_deck:state\.players\[localPlayer\]\?\.archetype/);
assert.match(account, /reportedOnlineMatches/);
assert.match(network, /onlineAccounts=\{1:null,2:null\}/);
assert.match(network, /account:onlineAccounts\[localPlayer\]/);
assert.match(network, /verifyRemoteAccount\(other,packet\.account\)/);
assert.match(engine, /matchId:onlineMode\?createMatchId\(\):null/);
assert.match(engine, /account,archetype:key/);
assert.match(ui, /reportOnlineMatchResult\(winner,reason\)/);
assert.match(schema, /enable row level security/);
assert.match(schema, /primary key \(match_id, reporter\)/);
assert.match(schema, /on conflict \(match_id\) do nothing/);
assert.match(schema, /wins = wins \+ 1/);
assert.match(schema, /losses = losses \+ 1/);
assert.match(schema, /deck_usage = jsonb_set/);
assert.match(schema, /rating = rating \+ 30/);
assert.match(schema, /rating = greatest\(0,rating - 30\)/);
assert.match(schema, /profile_icon/);
assert.match(schema, /profile_color/);
assert.match(schema, /function public\.get_player_profile/);
assert.match(schema, /limit 10/);
assert.match(schema, /function public\.set_profile_style/);
assert.match(schema, /to anon, authenticated using \(true\)/);
console.log('account and persistent record tests passed');
