var accountClient=null,currentAccount=null,accountSession=null,accountInitialized=false;
const reportedOnlineMatches=new Set();
const profileIconDefaults=['flower-twirl','empty-chessboard','forest','orbit','evil-eyes','graveyard','gold-stack'];
const profileColors={xadria:'#7f4c91',wild:'#3f7b50',celestial:'#357aa4',abyss:'#8b315e',candy:'#c24f78',gold:'#b98b27'};

function accountConfig(){return window.CONFLUXO_SUPABASE||{}}
function accountConfigured(){let config=accountConfig();return /^https:\/\/.+\.supabase\.co$/i.test(config.url||'')&&!!config.publishableKey}
function normalizeAccountName(value){return String(value||'').trim().replace(/\s+/g,' ').slice(0,18)}
function accountNameKey(value){return normalizeAccountName(value).toLowerCase().replace(/[^a-z0-9]/g,'')}
function accountLoginEmail(value){return`${accountNameKey(value)}@players.confluxo.invalid`}
function validAccountName(value){return /^[A-Za-z0-9 ]{3,18}$/.test(normalizeAccountName(value))&&accountNameKey(value).length>=3}
const accountDeckNames={xadria:'XADRIA',wild:'SELVAGEM',celestial:'OBJETO CELESTE',abyss:'TERROR ABISSAL',candy:'MORTOS DOCES',gold:'ERA DOURADA'};
function escapeProfileText(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function safeProfileIcon(value){let icon=String(value||'flower-twirl').toLowerCase();return /^[a-z0-9-]{1,40}$/.test(icon)?icon:'flower-twirl'}
function profileIconUrl(value){return`assets/icons/${safeProfileIcon(value)}.svg`}
function iconNameFromArt(value){let match=String(value||'').match(/assets\/icons\/([a-z0-9-]+)\.svg/i);return match?.[1]||null}
function availableProfileIcons(){let icons=new Set(profileIconDefaults);if(typeof cardIcons!=='undefined')Object.values(cardIcons).forEach(icon=>icons.add(icon));if(typeof effectIcons!=='undefined')Object.values(effectIcons).forEach(icon=>icons.add(icon));if(typeof defs!=='undefined')Object.values(defs).forEach(card=>{let icon=iconNameFromArt(card?.art);if(icon)icons.add(icon)});if(typeof effects!=='undefined')Object.values(effects).forEach(card=>{let icon=iconNameFromArt(card?.art);if(icon)icons.add(icon)});return[...icons].sort()}
function safeProfileColor(value){return Object.hasOwn(profileColors,value)?value:'xadria'}
function profileColorHex(value){return profileColors[safeProfileColor(value)]}
function profileStyle(value){return`--profile-color:${profileColorHex(value)}`}
function applyProfileColor(element,value){if(element)element.style.setProperty('--profile-color',profileColorHex(value))}
function safeRating(value){let rating=Number(value);return Number.isFinite(rating)?Math.max(0,Math.round(rating)):1000}
function safeDeckUsage(value){let usage={};if(!value||typeof value!=='object'||Array.isArray(value))return usage;Object.keys(accountDeckNames).forEach(key=>{let count=Math.max(0,Math.floor(Number(value[key])||0));if(count)usage[key]=count});return usage}
function mostUsedDeck(value){let entries=Object.entries(safeDeckUsage(value));if(!entries.length)return null;entries.sort((a,b)=>b[1]-a[1]||Object.keys(accountDeckNames).indexOf(a[0])-Object.keys(accountDeckNames).indexOf(b[0]));return entries[0][0]}
function accountPublicSnapshot(){return currentAccount?{id:currentAccount.id,username:currentAccount.username,wins:Number(currentAccount.wins)||0,losses:Number(currentAccount.losses)||0,rating:safeRating(currentAccount.rating),profileIcon:safeProfileIcon(currentAccount.profileIcon),profileColor:safeProfileColor(currentAccount.profileColor),deckUsage:safeDeckUsage(currentAccount.deckUsage)}:null}
function safeAccountSnapshot(value){if(!value||typeof value!=='object'||!value.id)return null;return{id:String(value.id),username:normalizeAccountName(value.username)||'Duelista',wins:Math.max(0,Number(value.wins)||0),losses:Math.max(0,Number(value.losses)||0),rating:safeRating(value.rating),profileIcon:safeProfileIcon(value.profile_icon||value.profileIcon),profileColor:safeProfileColor(value.profile_color||value.profileColor),deckUsage:safeDeckUsage(value.deck_usage||value.deckUsage)}}
function accountRecordText(account){if(!account)return'CONVIDADO · PARTIDAS NÃO CONTABILIZADAS';let favorite=mostUsedDeck(account.deckUsage);return`${account.wins||0} VITÓRIAS · ${account.losses||0} DERROTAS · MAIS USADO: ${favorite?accountDeckNames[favorite]:'—'}`}
async function lookupAccountProfile(value){let candidate=safeAccountSnapshot(value);if(!candidate||!accountClient)return candidate;let {data,error}=await accountClient.from('profiles').select('id,username,wins,losses,rating,profile_icon,profile_color,deck_usage').eq('id',candidate.id).single();return error?null:safeAccountSnapshot(data)}
function setAccountMessage(text,kind=''){let el=document.querySelector('#account-message');if(!el)return;el.textContent=text;el.className=`account-message ${kind}`}
function setAccountBusy(busy){document.querySelectorAll('#account-dialog input,#account-dialog button').forEach(el=>{if(!el.classList.contains('dialog-close'))el.disabled=busy})}

function updateAccountUI(){
 let snapshot=accountPublicSnapshot(),card=document.querySelector('#account-card'),name=document.querySelector('#account-name'),flux=document.querySelector('#account-flux'),record=document.querySelector('#account-record'),avatar=document.querySelector('#account-avatar-image'),avatarButton=document.querySelector('#account-avatar'),button=document.querySelector('#account-open'),logout=document.querySelector('#account-logout'),onlineName=document.querySelector('#online-name'),onlineNameLabel=document.querySelector('#online-name-label');
 if(card)card.classList.toggle('signed-in',!!snapshot);if(name)name.textContent=snapshot?snapshot.username:'Jogar como convidado';if(flux)flux.textContent=snapshot?`${snapshot.rating} FLUX`:'SEM FLUX';if(record)record.textContent=accountRecordText(snapshot);if(avatar)avatar.src=profileIconUrl(snapshot?.profileIcon);applyProfileColor(avatarButton,snapshot?.profileColor);if(avatarButton)avatarButton.title=snapshot?'Personalizar perfil':'Entre para personalizar seu perfil';if(button)button.textContent=snapshot?'VER CONTA':'ENTRAR OU CRIAR CONTA';if(logout)logout.classList.toggle('hidden',!snapshot);
 if(onlineName){onlineName.classList.toggle('hidden',!!snapshot);onlineNameLabel?.classList.toggle('hidden',!!snapshot);if(snapshot){onlineName.value=snapshot.username;onlineName.readOnly=true;onlineName.title='O nome online está vinculado à sua conta.'}else{onlineName.readOnly=false;onlineName.title='';let saved=localStorage.getItem('confluxo-guest-name');if(!onlineName.value&&saved)onlineName.value=saved}}
 if(typeof onlineMode!=='undefined'&&onlineMode&&localPlayer&&typeof onlineAccounts!=='undefined'){onlineAccounts[localPlayer]=snapshot;if(snapshot)onlineNames[localPlayer]=snapshot.username;if(typeof sendDeckChoice==='function'&&dataChannel?.open)sendDeckChoice()}if(typeof renderLobbyParticipants==='function')renderLobbyParticipants()
}
async function loadCurrentProfile(){
 if(!accountClient)return null;let {data:{session}}=await accountClient.auth.getSession();accountSession=session||null;if(!session){currentAccount=null;updateAccountUI();return null}
 let {data,error}=await accountClient.from('profiles').select('id,username,wins,losses,rating,profile_icon,profile_color,deck_usage').eq('id',session.user.id).single();if(error){currentAccount=null;setAccountMessage('A conta existe, mas o perfil ainda não foi preparado no banco.','error');updateAccountUI();return null}currentAccount=safeAccountSnapshot(data);updateAccountUI();return currentAccount
}
async function initializeAccounts(){
 if(accountInitialized)return;accountInitialized=true;updateAccountUI();
 if(!accountConfigured()){setAccountMessage('Contas globais aguardando a conexão com o banco. O modo convidado continua disponível.','notice');return}
 if(!window.supabase?.createClient){setAccountMessage('Não foi possível carregar o serviço de contas. Tente recarregar a página.','error');return}
 let config=accountConfig();accountClient=window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});await loadCurrentProfile();await loadLeaderboard();accountClient.auth.onAuthStateChange(()=>setTimeout(async()=>{await loadCurrentProfile();await loadLeaderboard()},0))
}
function openAccountDialog(){if(currentAccount)return openPublicProfile(currentAccount.id);let dialog=document.querySelector('#account-dialog');if(!dialog)return;document.querySelector('#account-dialog-title').textContent='Sua conta Confluxo';document.querySelector('#account-fields').classList.remove('hidden');setAccountMessage(accountConfigured()?'Entre ou crie um nome único para seus duelos online.':'O banco de contas ainda não foi conectado.','notice');dialog.showModal()}
async function submitAccount(mode){
 if(!accountClient)return setAccountMessage('O serviço de contas ainda não está configurado.','error');let username=normalizeAccountName(document.querySelector('#account-username').value),password=document.querySelector('#account-password').value;
 if(!validAccountName(username))return setAccountMessage('Use de 3 a 18 letras, números ou espaços no nome.','error');if(password.length<6)return setAccountMessage('Use uma senha com pelo menos 6 caracteres.','error');let email=accountLoginEmail(username);setAccountBusy(true);setAccountMessage(mode==='signup'?'Criando conta…':'Entrando…','notice');
 try{let result=mode==='signup'?await accountClient.auth.signUp({email,password,options:{data:{username}}}):await accountClient.auth.signInWithPassword({email,password});if(result.error)throw result.error;await loadCurrentProfile();if(!currentAccount)throw new Error('Não foi possível carregar o perfil da conta.');setAccountMessage(`Bem-vindo, ${currentAccount.username}.`,'success');document.querySelector('#account-dialog')?.close()}catch(error){let message=String(error?.message||error);if(/duplicate|unique|database error|already registered/i.test(message))message='Esse nome já está em uso. Escolha outro.';else if(/invalid login/i.test(message))message='Nome ou senha incorretos.';setAccountMessage(message,'error')}finally{setAccountBusy(false)}
}
async function logoutAccount(){if(!accountClient)return;await accountClient.auth.signOut();currentAccount=null;accountSession=null;updateAccountUI();setAccountMessage('Você saiu da conta.','notice')}

function leaderboardRow(profile,index){let favorite=mostUsedDeck(profile.deckUsage),name=escapeProfileText(profile.username);return`<li class="leaderboard-row"><button class="leaderboard-profile" type="button" data-player-id="${profile.id}"><b class="leaderboard-rank">${index+1}</b><span class="leaderboard-icon" style="${profileStyle(profile.profileColor)}"><img src="${profileIconUrl(profile.profileIcon)}" alt=""></span><span><strong>${name}</strong><small>${favorite?accountDeckNames[favorite]:'SEM DECK'} · ${profile.wins}V/${profile.losses}D</small></span><em>${profile.rating}<small>FLUX</small></em></button></li>`}
async function loadLeaderboard(){let list=document.querySelector('#leaderboard-list');if(!list||!accountClient)return;if(!list.children.length)list.innerHTML='<li class="leaderboard-empty">Carregando ranking…</li>';let {data,error}=await accountClient.from('profiles').select('id,username,wins,losses,rating,profile_icon,profile_color,deck_usage').order('rating',{ascending:false}).order('wins',{ascending:false});if(error){list.innerHTML='<li class="leaderboard-empty">Ranking indisponível.</li>';return}let profiles=(data||[]).map(safeAccountSnapshot).filter(Boolean);list.innerHTML=profiles.length?profiles.map(leaderboardRow).join(''):'<li class="leaderboard-empty">Nenhum duelista cadastrado.</li>';list.querySelectorAll('.leaderboard-profile').forEach(button=>button.onclick=()=>openPublicProfile(button.dataset.playerId))}
function matchHistoryRow(match,playerId){let one=match?.playerOne||{},two=match?.playerTwo||{},mine=String(one.id)===String(playerId)?one:two,opponent=String(one.id)===String(playerId)?two:one,won=String(match?.winner)===String(playerId),date=match?.completedAt?new Date(match.completedAt).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit'}):'',mineDeck=accountDeckNames[mine.deck]||mine.deck||'SEM DECK',opponentDeck=accountDeckNames[opponent.deck]||opponent.deck||'SEM DECK';return`<li class="profile-match ${won?'won':'lost'}"><b>${won?'VITÓRIA':'DERROTA'}</b><span>contra <strong>${escapeProfileText(opponent.username||'Duelista')}</strong><small>${escapeProfileText(mine.username||'Perfil')}: ${escapeProfileText(mineDeck)} · ${escapeProfileText(opponent.username||'Adversário')}: ${escapeProfileText(opponentDeck)}</small></span><time>${date}</time></li>`}
async function openPublicProfile(playerId){let dialog=document.querySelector('#public-profile-dialog'),history=document.querySelector('#profile-view-history');if(!dialog||!accountClient)return;dialog.showModal();document.querySelector('#profile-view-name').textContent='Carregando perfil…';history.innerHTML='<li class="profile-history-empty">Buscando partidas recentes…</li>';document.querySelector('#profile-customize').classList.add('hidden');let {data,error}=await accountClient.rpc('get_player_profile',{p_user:playerId});if(error||!data?.profile){document.querySelector('#profile-view-name').textContent='Perfil indisponível';history.innerHTML='<li class="profile-history-empty">Não foi possível carregar este perfil.</li>';return}let profile=safeAccountSnapshot(data.profile),matches=Array.isArray(data.matches)?data.matches.slice(0,10):[],recentWins=matches.filter(match=>String(match.winner)===profile.id).length,winRate=matches.length?`${Math.round(recentWins/matches.length*100)}%`:'—',favorite=mostUsedDeck(profile.deckUsage),avatar=document.querySelector('#profile-view-avatar');document.querySelector('#profile-view-icon').src=profileIconUrl(profile.profileIcon);applyProfileColor(avatar,profile.profileColor);document.querySelector('#profile-view-name').textContent=profile.username;document.querySelector('#profile-view-flux').textContent=`${profile.rating} FLUX`;document.querySelector('#profile-view-record').textContent=`${profile.wins} VITÓRIAS · ${profile.losses} DERROTAS`;document.querySelector('#profile-view-rate').textContent=winRate;document.querySelector('#profile-view-deck').textContent=favorite?accountDeckNames[favorite]:'SEM HISTÓRICO';history.innerHTML=matches.length?matches.map(match=>matchHistoryRow(match,profile.id)).join(''):'<li class="profile-history-empty">Nenhuma partida registrada.</li>';document.querySelector('#profile-customize').classList.toggle('hidden',currentAccount?.id!==profile.id)}

function renderProfilePicker(){let grid=document.querySelector('#profile-icon-grid'),colors=document.querySelector('#profile-color-grid');grid.innerHTML=availableProfileIcons().map(icon=>`<button type="button" data-icon="${icon}" class="${icon===currentAccount.profileIcon?'selected':''}" style="${profileStyle(currentAccount.profileColor)}" title="${icon}"><img src="${profileIconUrl(icon)}" alt="${icon}"></button>`).join('');colors.innerHTML=Object.keys(profileColors).map(color=>`<button type="button" data-color="${color}" class="${color===currentAccount.profileColor?'selected':''}" style="${profileStyle(color)}" title="${accountDeckNames[color]}"><i></i><span>${accountDeckNames[color]}</span></button>`).join('');grid.querySelectorAll('button').forEach(button=>button.onclick=()=>saveProfileStyle(button.dataset.icon,currentAccount.profileColor));colors.querySelectorAll('button').forEach(button=>button.onclick=()=>saveProfileStyle(currentAccount.profileIcon,button.dataset.color))}
function openProfileIconDialog(){if(!currentAccount)return openAccountDialog();renderProfilePicker();document.querySelector('#public-profile-dialog')?.close();document.querySelector('#profile-icon-dialog').showModal()}
async function saveProfileStyle(icon,color){if(!accountClient||!currentAccount)return;icon=safeProfileIcon(icon);color=safeProfileColor(color);document.querySelectorAll('#profile-icon-dialog button').forEach(button=>button.disabled=true);let {error}=await accountClient.rpc('set_profile_style',{p_icon:icon,p_color:color});document.querySelectorAll('#profile-icon-dialog button').forEach(button=>button.disabled=false);if(error)return;currentAccount.profileIcon=icon;currentAccount.profileColor=color;updateAccountUI();renderProfilePicker();await loadLeaderboard()}
async function refreshOnlineAccounts(){await loadCurrentProfile();if(typeof onlineAccounts!=='undefined'&&localPlayer)onlineAccounts[localPlayer]=accountPublicSnapshot();if(state?.players&&localPlayer&&currentAccount)state.players[localPlayer].account=accountPublicSnapshot();if(typeof render==='function'&&state)render()}
async function reportOnlineMatchResult(winner,reason){
 if(!accountClient||!currentAccount||!onlineMode||onlineRole==='spectator'||!state?.matchId||!localPlayer)return false;let mine=safeAccountSnapshot(state.players?.[localPlayer]?.account),otherNumber=localPlayer===1?2:1,other=safeAccountSnapshot(state.players?.[otherNumber]?.account);if(!mine||!other||mine.id!==currentAccount.id||mine.id===other.id)return false;let matchKey=`${state.matchId}:${currentAccount.id}`;if(reportedOnlineMatches.has(matchKey))return false;reportedOnlineMatches.add(matchKey);
 let {data,error}=await accountClient.rpc('report_match_result',{p_match_id:state.matchId,p_opponent:other.id,p_winner:state.players[winner]?.account?.id||null,p_reason:reason||'duelo',p_deck:state.players[localPlayer]?.archetype});if(error){reportedOnlineMatches.delete(matchKey);console.warn('Resultado online não contabilizado:',error.message);return false}if(data){await refreshOnlineAccounts();await loadLeaderboard();if(typeof hint==='function')hint('Resultado confirmado: vencedor +30 Flux, derrotado −30 Flux.')}else{setTimeout(refreshOnlineAccounts,1800);setTimeout(refreshOnlineAccounts,4500)}return !!data
}

document.addEventListener('DOMContentLoaded',()=>{
 initializeAccounts();let onlineName=document.querySelector('#online-name');onlineName?.addEventListener('input',()=>{if(!currentAccount)localStorage.setItem('confluxo-guest-name',normalizeAccountName(onlineName.value))});document.querySelector('#account-avatar').onclick=openProfileIconDialog;document.querySelector('#account-open').onclick=openAccountDialog;document.querySelector('#account-logout').onclick=logoutAccount;document.querySelector('#account-login').onclick=()=>submitAccount('login');document.querySelector('#account-signup').onclick=()=>submitAccount('signup');document.querySelector('#profile-customize').onclick=openProfileIconDialog;document.querySelector('#account-dialog .dialog-close').onclick=()=>document.querySelector('#account-dialog').close();document.querySelector('#profile-icon-dialog .dialog-close').onclick=()=>document.querySelector('#profile-icon-dialog').close();document.querySelector('#public-profile-dialog .dialog-close').onclick=()=>document.querySelector('#public-profile-dialog').close()
});
