const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(`${__dirname}/combat-explainer.js`,'utf8');
const combatLogs=[];
const state={arena:null,animating:false,players:{1:{units:[]},2:{units:[]}}};
const context={document:{documentElement:{lang:'pt-BR'},querySelector:()=>null},renderCard(){},doAttack(){state.animating=true},logCombatResult(message,before){combatLogs.push({message,before})},effects:{moon:{name:'Lua'},goldArmor:{name:'Armadura'}},defs:{rider:{name:'Montador',atk:150},infantry:{name:'Infantaria'}},effectiveAtk:u=>u.total??u.atk,state,allUnits:()=>[],adjacent:()=>true,hasEffect:(u,k)=>u.kind===k,egyptianJointAttack:()=>null,calamityArenaFromAttack:()=>null,inMovementRadius:()=>true,escapeLogText:String};
vm.createContext(context);vm.runInContext(source,context);
const atk=context.attackExplanation({atk:250,bonusAtk:100,equipment:['moon'],total:225});
assert.equal(atk.total,225);
assert.equal(atk.rows.reduce((s,r)=>s+r.value,0),225,'a explicação deve fechar no ATK real mesmo com redução');
assert.equal(atk.rows.at(-1).value,-225);
const a={id:'a',name:'Infantaria',kind:'infantry',owner:1,row:1,col:1,atk:200},b={id:'b',name:'Cavalo',kind:'horse',owner:1,row:1,col:2,atk:250},d={id:'d',name:'Torre',owner:2,row:2,col:1,atk:400};
context.state.players[1].units=[a,b];context.state.players[2].units=[d];
let preview=context.combatPreviewData(a,d);
assert.equal(preview.attack,700,'ataque conjunto inclui o bônus real da Infantaria');assert.equal(preview.defense,400);
context.state.arena='tremblingEarth';context.allUnits=()=>[a,b,d];preview=context.combatPreviewData(a,d);
assert.equal(preview.attack,450,'Terra Tremula usa sua própria soma, sem bônus da rotina normal');
context.state.arena='volcanicHeat';assert.equal(context.combatPreviewData(a,d).changing,true,'não prometer resultado exato antes de efeitos de arena');
assert.equal(a.atk,200,'prévia não altera peões');assert.equal(b.atk,250);
assert.equal(context.combatSideSummary([{name:'Cavalo',atk:250}],250),'Cavalo 250 ATK','combate individual não deve repetir o mesmo ATK como total');
assert.equal(context.combatSideSummary([{name:'Infantaria',atk:200},{name:'Cavalo',atk:250}],700,'Infantaria',250),'Infantaria 200 ATK + Cavalo 250 ATK + Infantaria 250 ATK = 700 ATK','ataque conjunto deve manter a soma explicada');
context.state.arena=null;context.state.animating=false;context.doAttack(a,d);context.logCombatResult('Infantaria venceu (700 × 400).',{1:0,2:0});
assert.equal(combatLogs.length,1,'o combate deve gerar uma única explicação consolidada');
assert.match(combatLogs[0].message,/Infantaria 200 ATK \+ Cavalo 250 ATK \+ Infantaria 250 ATK = 700 ATK contra Torre 400 ATK/);
assert.doesNotMatch(combatLogs[0].message,/\(700 × 400\)/,'a comparação numérica antiga não deve ser repetida');
assert.doesNotMatch(source,/showModal|combatPreviewDialog|destroy=function/,'não deve haver prompt prévio nem log duplicado por destruição');
assert.doesNotMatch(source,/O saldo reúne efeitos|The net includes effects/,'os detalhes de ATK não devem exibir a observação removida');
console.log('Combat explanation tests passed');
