const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(`${__dirname}/combat-explainer.js`,'utf8');
const dialog={open:false,querySelector(){return{}},showModal(){this.open=true},close(){this.open=false}};
const context={document:{documentElement:{lang:'pt-BR'},createElement:()=>dialog,body:{append(){}}},renderCard(){},doAttack(){},destroy(){},effects:{moon:{name:'Lua'},goldArmor:{name:'Armadura'}},defs:{rider:{name:'Montador',atk:150}},effectiveAtk:u=>u.total??u.atk,state:{arena:null,players:{1:{units:[]},2:{units:[]}}},allUnits:()=>[],adjacent:()=>true,hasEffect:(u,k)=>u.kind===k,egyptianJointAttack:()=>null,calamityArenaFromAttack:()=>null,inMovementRadius:()=>true};
vm.createContext(context);vm.runInContext(source,context);
const atk=context.attackExplanation({atk:250,bonusAtk:100,equipment:['moon'],total:225});
assert.equal(atk.total,225);
assert.equal(atk.rows.reduce((s,r)=>s+r.value,0),225,'a explicação deve fechar no ATK real mesmo com redução');
assert.equal(atk.rows.at(-1).value,-225);
const a={id:'a',kind:'infantry',owner:1,row:1,col:1,atk:200},b={id:'b',kind:'horse',owner:1,row:1,col:2,atk:250},d={id:'d',owner:2,row:2,col:1,atk:400};
context.state.players[1].units=[a,b];context.state.players[2].units=[d];
let preview=context.combatPreviewData(a,d);
assert.equal(preview.attack,700,'ataque conjunto inclui o bônus real da Infantaria');assert.equal(preview.defense,400);
context.state.arena='tremblingEarth';context.allUnits=()=>[a,b,d];preview=context.combatPreviewData(a,d);
assert.equal(preview.attack,450,'Terra Tremula usa sua própria soma, sem bônus da rotina normal');
context.state.arena='volcanicHeat';assert.equal(context.combatPreviewData(a,d).changing,true,'não prometer resultado exato antes de efeitos de arena');
assert.equal(a.atk,200,'prévia não altera peões');assert.equal(b.atk,250);
console.log('Combat explanation tests passed');
