function isGoldUnit(u){return !!u?.types?.includes('OURO')}
function materialMatchesRequirement(u,req){return !!u&&(!req.kind||u.kind===req.kind)&&(!req.type||u.types?.includes(req.type))&&(!req.combined||!!u.fusion)&&(!req.normal||!u.fusion)}
function goldUnitHasReducedAttack(u){if(!isGoldUnit(u)||hasEffect(u,'goldWorshipper'))return false;if((u.goldAttackReduced||0)>0)return true;return allUnits().some(b=>b.owner!==u.owner&&hasEffect(b,'babel')&&inMovementRadius(b,u))}
function reduceGoldAttack(u,amount){if(!u||amount<=0||hasEffect(u,'goldWorshipper'))return 0;u.bonusAtk=(u.bonusAtk||0)-amount;if(isGoldUnit(u))u.goldAttackReduced=(u.goldAttackReduced||0)+amount;return amount}
function consumeGoldArmor(u){let index=u?.equipment?.indexOf('goldArmor');if(index<0)return false;u.equipment.splice(index,1);log(`A Armadura de Ouro de ${u.name} foi destruída e negou sua destruição.`,'effect');return true}
function resolveGoldenGoblin(victim,killer){if(!victim||!killer||!hasEffect(victim,'goldGoblin')||killer.row===null)return false;let inherited=effectiveAtk(victim,false);killer.atk=inherited;killer.bonusAtk=0;killer.goldAttackReduced=0;log(`${killer.name} derrotou ${victim.name} e teve seu ATK fixado em ${inherited}.`,'combat');return true}
function transferGoldAttack(first,second){if(!isGoldUnit(first)||!isGoldUnit(second)||first.id===second.id)return false;let firstAtk=effectiveAtk(first,false),secondAtk=effectiveAtk(second,false),donor=firstAtk<=secondAtk?first:second,receiver=donor===first?second:first,total=firstAtk+secondAtk;donor.atk=0;donor.bonusAtk=0;donor.goldAttackReduced=0;receiver.atk=total;receiver.bonusAtk=0;receiver.goldAttackReduced=0;log(`${donor.name} transferiu ${Math.min(firstAtk,secondAtk)} ATK para ${receiver.name}, que agora possui ${total} ATK.`,'effect');return true}
function gildUnit(u){if(!u)return false;u.baseTypes=[...new Set([...(u.baseTypes||u.types||[]),'OURO'])];u.types=[...new Set([...(u.types||[]),'OURO'])];u.goldConverted=true;return true}
function resolveAllOrNothing(target){if(!target)return 0;let drained=allUnits().filter(isGoldUnit).reduce((sum,u)=>sum+reduceGoldAttack(u,100),0);target.bonusAtk=(target.bonusAtk||0)+drained;log(`${target.name} retirou ${drained} ATK dos Peões OURO com Tudo ou Nada.`,'effect');return drained}
