const ROWS=8,COLS=6,GOAL=10;
const defs={
 infantry:{name:'Infantaria do Reino de Xadria',atk:200,movement:[[-2,0],[-1,0],[0,-1],[0,1],[1,0],[2,0]],types:['LUZ','TREVAS'],glyph:'◐',art:'cartas.png',artCrop:{scale:321,x:-150,y:-304},text:'No ataque conjunto, dobra o ATK de um dos participantes.'},
 tower:{name:'Torre Branca de Xadria',atk:150,movement:[[-3,0],[-2,0],[-1,0],[1,0],[2,0],[3,0]],types:['LUZ','PEDRA'],glyph:'▥',art:'cartas.png',artCrop:{scale:346,x:-142,y:-215},text:'Pode se sacrificar para negar um ataque contra aliado adjacente.'},
 jester:{name:'Bobo da Casa Branca de Xadria',atk:100,movement:[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],types:['LUZ'],glyph:'✦',text:'Habilidade: escolhe qualquer peão em campo e mantém o efeito copiado até o fim da partida.'},
 archer:{name:'Arqueiro da Casa Preta de Xadria',atk:250,movement:[[-3,-1],[-3,0],[-3,1],[-2,-2],[-2,2],[-1,-3],[-1,0],[-1,3],[0,-3],[0,-1],[0,1],[0,3],[1,-3],[1,0],[1,3],[2,-2],[2,2],[3,-1],[3,0],[3,1]],types:['LUZ'],glyph:'➹',text:'Só se move quando um Peão adversário estiver em seu caminho e pode atacar qualquer adversário nesse caminho, dentro do raio indicado pela carta.'},
 duck:{name:'Ave Eterna do Reino Xadria',atk:0,movement:[[-3,0],[-2,-1],[-2,0],[-2,1],[-1,-2],[-1,-1],[-1,0],[-1,1],[-1,2],[0,-3],[0,-2],[0,-1],[0,1],[0,2],[0,3],[1,-2],[1,-1],[1,0],[1,1],[1,2],[2,-1],[2,0],[2,1],[3,0]],types:['LUZ','TREVAS','NATURAL'],glyph:'◆',art:'cartas.png',artCrop:{scale:300,x:-193,y:-283},text:'Não é destruída por combate. Pode se mover uma vez por turno sem gastar a ação de movimento.'},
 horse:{name:'Cavalo da Casa Preta de Xadria',atk:250,movement:[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]],types:['TREVAS','NATURAL'],glyph:'♞',text:'Salta seguindo o alcance indicado em sua carta.'},
 rabbit:{name:'Coelho Selvagem',atk:200,movement:[[-3,0],[0,-3],[0,3],[3,0]],types:['NATURAL'],glyph:'●',text:'Salta para uma das quatro casas indicadas no alcance.'},
 rider:{name:'Montador Selvagem',atk:150,movement:[[-1,0],[0,-1],[0,1],[1,0]],types:['NATURAL'],glyph:'⟁',text:'Habilidade: monta um aliado Selvagem adjacente, somando ataque e alcance de ambos.'},
 babel:{name:'Torre Preta de Xadria: Babel',atk:400,movement:[[-3,0],[-2,0],[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1],[2,0],[3,0]],types:['TREVAS','PEDRA'],glyph:'⬟',fusion:2,materials:{kinds:['tower','infantry']},art:'cartas.png',artCrop:{scale:300,x:-27,y:-67},text:'Inimigos dentro das casas indicadas em seu alcance de movimento têm o ATK reduzido à metade.'},
 justice:{name:'Cavaleiro da Casa Branca: Justiça Alva',atk:300,movement:[[-2,0],[-1,-1],[-1,0],[-1,1],[0,-2],[0,-1],[0,1],[0,2],[1,-1],[1,0],[1,1],[2,0]],types:['LUZ'],glyph:'✧',fusion:2,materials:{type:'LUZ'},art:'cartas.png',artCrop:{scale:225,x:-17,y:-190},text:'Seu ATK cresce 100 por aliado derrotado no último turno.'},
 serpent:{name:'Serpente Selvagem',atk:500,movement:[[-2,-1],[-2,0],[-2,1],[-1,-1],[-1,0],[-1,1],[1,0]],types:['NATURAL','LUZ'],glyph:'≈',fusion:3,materials:{type:'NATURAL'},text:'Habilidade: cria um obstáculo NATURAL adjacente uma vez por turno.'},
 hawk:{name:'Gavião Selvagem',atk:250,movement:[[-2,-2],[-2,2],[-1,-1],[-1,1],[1,0],[2,0]],types:['NATURAL','LUZ'],glyph:'⌁',text:'Pode se mover duas vezes no mesmo turno.'},
 golem:{name:'Golem Selvagem',atk:400,movement:[[-1,0],[0,-2],[0,-1],[0,1],[0,2],[1,0]],types:['NATURAL','LUZ'],glyph:'▰',fusion:2,materials:{type:'NATURAL'},text:'Pode pisar em obstáculos NATURAIS para destruí-los e ganhar 200 ATK permanentemente.'}
};
const effects={
 retreat:{name:'Recuar!',type:'UTILIDADE',icon:'↩',text:'Escolha um peão; ele retorna ao local onde foi jogado.'},
 castle:{name:'Rocar Torre',type:'UTILIDADE',icon:'⇄',text:'Troque um peão com “Torre” no nome por outro peão aliado.'},
 sword:{name:'Espada Maldita',type:'EQUIPAMENTO',icon:'†',art:'cartas.png',artCrop:{scale:375,x:-271,y:-75},text:'O equipado destrói qualquer rival, mas também cai após o combate. O dono do peão destruído escolhe qualquer outro peão que esteja no campo para receber a espada.'},
 burn:{name:'Queimar Pertences',type:'UTILIDADE',icon:'♨',text:'Destrói todos os equipamentos do peão escolhido.'},
 roses:{name:'Campo das Rosas Pálidas',type:'ARENA',icon:'❀',text:'Sempre que um jogador ganha 1 ponto, ele compra uma carta de uma pilha aleatória: Peões ou Efeitos.'},
 camouflage:{name:'Camuflar-se na Selva',type:'UTILIDADE',icon:'◒',text:'Vira todos os peões aliados em campo para baixo.'},
 jungle:{name:'Selva Selvagem',type:'ARENA',icon:'♣',text:'No início de cada turno cria um obstáculo NATURAL ou, com 50% de chance, uma fruta. Quem pega a fruta ganha 100 ATK. Tudo que a Selva criou desaparece quando esta Arena é substituída.'},
 bow:{name:'Arco Selvagem',type:'EQUIPAMENTO',icon:'➶',text:'O equipado pode atacar inimigos nas casas indicadas em seu próprio alcance de movimento, além do ataque adjacente normal.'},
 pit:{name:'Poço sem Fundo',type:'UTILIDADE',icon:'◉',text:'Coloque um poço em qualquer casa livre da Arena. O peão que pisar nele é destruído, mas o poço permanece.'},
 push:{name:'Empurrão',type:'UTILIDADE',icon:'»',text:'Escolha um peão em campo e depois quantas casas para trás ele será empurrado.'}
};
const archetypes={
 xadria:{name:'Xadria',emblem:'◐',pawns:['infantry','tower','jester','archer','duck','horse'],fusions:['babel','justice'],starters:['infantry','tower','jester'],effects:['retreat','castle','sword','burn','roses','pit','push']},
 wild:{name:'Selvagem',emblem:'✿',pawns:['rabbit','rider','hawk'],fusions:['serpent','golem'],starters:['rabbit','rider','rabbit'],effects:['camouflage','jungle','bow','retreat','burn','pit','push']}
};
let selectedDecks={1:'xadria',2:'wild'};
let state,selected=null,selectedEffect=null,mode=null,targets=[],attackTargets=[],pendingCard=null,pendingPushTarget=null,castleFirst=null,fusionMaterials=[],gameVersion=0,botMode=false,botPlayer=2,botTimer=null,lastArenaVisual='none',arenaAnimationTimer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function uid(){return Math.random().toString(36).slice(2,9)}
function unit(kind,owner){let d=defs[kind];return{id:uid(),kind,owner,row:null,col:null,origin:null,faceDown:false,flippedTurn:0,movedTurn:0,attackedTurn:0,equipment:[],abilityTurn:0,mounted:null,...d}}
function artStyle(item){let crop=item?.artCrop;return crop?` style="--art-scale:${crop.scale}%;--art-x:${crop.x}%;--art-y:${crop.y}%"`:''}
function artVisual(item,context=''){return item?.art?`<span class="art-crop ${context}"><img src="${item.art}" alt="Arte de ${item.name}"${artStyle(item)}></span>`:''}
function unitVisual(u,context=''){let visual=u.art?artVisual(u,context):`<span class="glyph">${u.glyph}</span>`;return visual+(u.fruitPickup&&context==='board-art'?'<span class="fruit-pickup" aria-label="Fruta coletada">✦<i>+100</i></span>':'')}
function rawMovementOffsets(u){let offsets=[...(u.movement||[])];if(u.mounted)offsets.push(...(defs[u.mounted].movement||[]));let seen=new Set;return offsets.filter(([dr,dc])=>{let key=`${dr},${dc}`;if(seen.has(key))return false;seen.add(key);return true})}
function movementOffsets(u){let direction=u.owner===2?-1:1;return rawMovementOffsets(u).map(([dr,dc])=>[dr*direction,dc*direction])}
function movementPreview(u){let active=new Set(rawMovementOffsets(u).map(([dr,dc])=>`${dr},${dc}`)),cells=[];for(let dr=-3;dr<=3;dr++)for(let dc=-3;dc<=3;dc++)cells.push(`<span class="${dr===0&&dc===0?'origin':active.has(`${dr},${dc}`)?'reach':''}"></span>`);return `<div class="movement-label">ALCANCE</div><div class="movement-preview" aria-label="Alcance de movimento">${cells.join('')}</div>`}
function fusionRequirementLabel(card,short=false){if(!card?.fusion)return'';if(card.materials?.kinds){let names=card.materials.kinds.map(k=>short?(k==='tower'?'TORRE':'INF'):defs[k].name);return names.join(short?'+':' + ')}let type=card.materials?.type||'PEÃO';return `${card.fusion}×${short&&type==='NATURAL'?'NAT':type}`}
function fusionRequirementVisual(card){if(!card?.fusion)return'';let field=state?.players?.[card.owner]?.units?.filter(u=>u.row!==null)||[],chips='',status='';if(card.materials?.kinds){chips=card.materials.kinds.map(kind=>{let found=field.some(u=>u.kind===kind);return`<span class="material-chip ${found?'ready':'missing'}"><i>${defs[kind].glyph}</i><b>${defs[kind].name.replace(' do Reino de Xadria','').replace(' de Xadria','')}</b><em>${found?'EM CAMPO':'FALTA'}</em></span>`}).join('');status=card.materials.kinds.every(kind=>field.some(u=>u.kind===kind))?'Materiais disponíveis — aproxime-os para combinar.':'Coloque os peões indicados no campo.'}else{let type=card.materials?.type,count=field.filter(u=>u.types.includes(type)).length,shown=Math.min(count,card.fusion);chips=Array.from({length:card.fusion},(_,i)=>`<span class="material-chip ${i<shown?'ready':'missing'}"><i>${type==='LUZ'?'✦':'✿'}</i><b>PEÃO ${type}</b><em>${i<shown?'EM CAMPO':'FALTA'}</em></span>`).join('');status=count>=card.fusion?'Materiais disponíveis — mantenha-os em contato.':`${shown}/${card.fusion} materiais no campo.`}return`<div class="fusion-requirements"><small>PEÕES NECESSÁRIOS</small><div>${chips}</div><p>${status}</p></div>`}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makePawnDeck(owner,key){let arc=archetypes[key],fusionSlots=key==='xadria'?4:3,commonSlots=18-fusionSlots,cards=Array.from({length:commonSlots},(_,i)=>unit(arc.pawns[i%arc.pawns.length],owner));for(let i=0;i<fusionSlots;i++)cards.push(unit(arc.fusions[i%arc.fusions.length],owner));return shuffle(cards)}
function makeEffectDeck(key){let pool=archetypes[key].effects;return shuffle(Array.from({length:20},(_,i)=>pool[i%pool.length]))}
function newGame(){
 let version=++gameVersion;
 if($('#winner-dialog')?.open)$('#winner-dialog').close();
 selected=null;selectedEffect=null;
 state={turn:1,current:1,players:{},obstacles:[],pits:[],log:[],animating:false,initialDeal:true,awaitingDraw:false,arena:null,arenaOwner:null,arenaDefeatedStart:0,swordQueue:[],defeatedCount:0,placementPhase:true,placementPlayer:1,passPurpose:null,forfeitWinner:null};
 clearTimeout(botTimer);botTimer=null;clearTimeout(arenaAnimationTimer);arenaAnimationTimer=null;lastArenaVisual='none';
 for(let p=1;p<=2;p++){let key=selectedDecks[p],player=state.players[p]={name:botMode&&p===botPlayer?'Bot':`Duelista ${p}`,archetype:key,score:0,units:[],initialUnits:[],hand:[],reserve:[],arena:null,drawn:true,deployed:false,moved:false,lastLosses:0,lossesThisTurn:0,pawnDeck:makePawnDeck(p,key),effectDeck:makeEffectDeck(key)};for(let i=0;i<3;i++)player.hand.push(player.effectDeck.pop());archetypes[key].starters.forEach(kind=>{let index=player.pawnDeck.findIndex(u=>u.kind===kind),u=index>=0?player.pawnDeck.splice(index,1)[0]:unit(kind,p);u.initial=true;player.initialUnits.push(u)})}
 log('Preparação: escolha onde posicionar os três peões iniciais.');clearAction();render();beginInitialPlacement(1);setTimeout(()=>{if(version!==gameVersion)return;state.initialDeal=false;renderHands()},1300);
}
function initialTargetsFor(player){let rows=player===1?[ROWS-2,ROWS-1]:[0,1],out=[];for(let r of rows)for(let c=0;c<COLS;c++)if(!at(r,c)&&!obstacleAt(r,c)&&!pitAt(r,c))out.push({r,c});return out}
function beginInitialPlacement(player){state.current=player;state.placementPlayer=player;state.placementPhase=true;selectedEffect=null;selected=state.players[player].initialUnits[0]||null;clearAction();mode='initial-deploy';targets=initialTargetsFor(player);render();hint(`${state.players[player].name}: escolha uma casa destacada para cada peão inicial.`)}
function placeInitialPawn(r,c){let p=state.players[state.placementPlayer],u=selected,version=gameVersion;if(!u||!u.initial||u.owner!==state.placementPlayer)return;place(u,r,c);u.initial=false;u.deployed=true;p.initialUnits=p.initialUnits.filter(x=>x.id!==u.id);p.units.push(u);collectFruit(u,r,c);log(`${p.name} posicionou ${u.name} em ${boardCoordinate(r,c)}.`);if(p.initialUnits.length){selected=p.initialUnits[0];targets=initialTargetsFor(state.placementPlayer);render();hint(`Posicione os ${p.initialUnits.length} peões iniciais restantes.`);setTimeout(()=>{if(version!==gameVersion)return;u.deployed=false;renderBoard()},650);return}selected=null;clearAction();render();hint(`${p.name} concluiu sua preparação.`);setTimeout(()=>{if(version!==gameVersion)return;u.deployed=false;if(state.placementPlayer===1){state.placementPlayer=2;state.current=2;render();showPass(2,'placement')}else{state.placementPhase=false;state.current=1;render();showPass(1,'start')}},620)}
function showPass(player,purpose){let p=state.players[player],a=archetypes[p.archetype];state.passPurpose=purpose;if(onlineMode){render();syncOnlineState(true);if(player===localPlayer){if(purpose==='placement')beginInitialPlacement(player);else beginTurn()}else updateOnlineLock();return}if(botMode){$('#pass').classList.add('hidden');if(player===botPlayer&&purpose==='placement'){beginInitialPlacement(player);scheduleBot(botPlaceInitial,500)}else beginTurn();return}$('#pass-name').textContent=`${p.name} · ${a.name}`;$('#pass .crest').textContent=a.emblem;$('#pass').classList.remove('hidden')}
function beginTurn(){let p=state.players[state.current];state.passPurpose=null;if(state.arena==='jungle')spawnJungleFeature();if(state.turn===1){state.awaitingDraw=false;p.drawn=true;render();hint(botMode&&state.current===botPlayer?'O Bot está pensando…':'Rodada 1: nenhum jogador compra cartas ou peões.')}else if(botMode&&state.current===botPlayer){botDraw();render()}else{p.drawn=false;openDrawChoice()}if(botMode&&state.current===botPlayer)scheduleBot(botTakeTurn,650)}
function place(u,r,c){u.row=r;u.col=c;if(!u.origin)u.origin={row:r,col:c}}
function boardCoordinate(r,c){return `${String.fromCharCode(65+c)}${r+1}`}
function allUnits(){return[...state.players[1].units,...state.players[2].units]}
function at(r,c){return allUnits().find(u=>u.row===r&&u.col===c)}
function featureAt(r,c){return (state.obstacles||[]).find(o=>o.row===r&&o.col===c)}
function obstacleAt(r,c){let feature=featureAt(r,c);return feature?.type!=='FRUIT'?feature:null}
function fruitAt(r,c){let feature=featureAt(r,c);return feature?.type==='FRUIT'?feature:null}
function pitAt(r,c){return (state.pits||[]).find(p=>p.row===r&&p.col===c)}
function collectFruit(u,r,c){let fruit=fruitAt(r,c);if(!u||!fruit)return false;state.obstacles=state.obstacles.filter(x=>x!==fruit);u.bonusAtk=(u.bonusAtk||0)+100;u.fruitPickup=true;log(`${u.name} pegou uma fruta em ${boardCoordinate(r,c)} e ganhou 100 ATK.`);let version=gameVersion;setTimeout(()=>{if(version!==gameVersion)return;delete u.fruitPickup;renderBoard();if(onlineMode)syncOnlineState(true)},760);return true}
function own(u){return u&&u.owner===state.current}
function viewPlayerNumber(){return botMode?1:onlineMode&&localPlayer?localPlayer:state.current}
function perspectivePlayer(){return botMode?1:onlineMode&&localPlayer?localPlayer:state.current}
function canLocalAct(){if(state?.animating)return false;if(botMode)return state.swordQueue?.length?state.swordQueue[0]!==botPlayer:state.current!==botPlayer;return !onlineMode||(state.swordQueue?.length?state.swordQueue[0]===localPlayer:state.current===localPlayer)}
