/* Regras do arquétipo Chamas Egípcias, sincronizadas com Cartas.md. */
const FLAME_TEMPLE_RANGE=[[-3,0],[-2,-1],[-2,0],[-2,1],[-1,-2],[-1,-1],[-1,0],[-1,1],[-1,2],[0,-3],[0,-2],[0,-1],[0,1],[0,2],[0,3],[1,-2],[1,-1],[1,0],[1,1],[1,2],[2,-1],[2,0],[2,1],[3,0]];
function isFireUnit(u){return !!u?.types?.includes('FOGO')}
function flameTempleAt(r,c){return (state.fireTemples||[]).find(t=>t.row===r&&t.col===c)}
function inFlameTempleRange(temple,target){return FLAME_TEMPLE_RANGE.some(([dr,dc])=>temple.row+dr===target.row&&temple.col+dc===target.col)}
function affectingFlameTemples(u){return (state.fireTemples||[]).filter(t=>inFlameTempleRange(t,u))}
function transformIntoGrayMummy(u,reason='efeito'){if(!u||u.row===null||u.kind==='grayMummy'||u.kind==='ra')return false;let mummy=defs.grayMummy,old=u.name;u.kind='grayMummy';u.name=mummy.name;u.atk=mummy.atk;u.bonusAtk=0;u.movement=[...mummy.movement];u.types=[...mummy.types];u.baseTypes=[...mummy.types];u.glyph=mummy.glyph;u.art=mummy.art;u.artCrop=mummy.artCrop;u.artCredit=mummy.artCredit;u.iconTone=mummy.iconTone;u.text=mummy.text;u.fusion=false;u.pointValue=1;u.mounted=null;u.copiedKind=null;u.equipment=[];delete u.mummyTransformPending;log(`${old} transformou-se em ${mummy.name} por ${reason}.`,'effect');return true}
function egyptianBeforeDestroy(u,scorer,reason){if(reason==='combate'&&hasEffect(u,'firePrince')){let slave=state.players[u.owner].units.filter(v=>v.id!==u.id&&v.row!==null&&hasEffect(v,'fireSlave')).sort((a,b)=>effectiveAtk(b,false)-effectiveAtk(a,false))[0];if(slave){let gained=Math.floor(effectiveAtk(slave,false)/2),slaveName=slave.name;state.fireSlaveDestroyedTurn=state.turn;destroy(slave,scorer,'sacrifício do Príncipe');u.bonusAtk=(u.bonusAtk||0)+gained;log(`${slaveName} foi sacrificado no lugar de ${u.name}, que ganhou ${gained} ATK.`,'combat');return true}}let anubis=state.players[u.owner].units.find(v=>v.row!==null&&hasEffect(v,'anubis'));if(anubis&&isFireUnit(u)&&u.kind!=='grayMummy'){transformIntoGrayMummy(u,`efeito de ${anubis.name}`);return true}return false}
function noteEgyptianDestruction(u){if(u?.kind==='fireSlave')state.fireSlaveDestroyedTurn=state.turn}
function egyptianAttackValue(u,atk,dynamicDepth=0){if(!dynamicDepth&&u.row!==null&&u.kind!=='ra'){let ra=allUnits().find(v=>v.row!==null&&hasEffect(v,'ra')&&adjacent(v,u));if(ra)atk=effectiveAtk(ra,false,dynamicDepth+1)}if(isFireUnit(u)&&affectingFlameTemples(u).length)atk+=150;return atk}
function egyptianJointAttack(allies){let ra=allies.find(u=>hasEffect(u,'ra'));if(!ra)return null;return effectiveAtk(ra,false,1)*allies.length}
function prepareMummyCombat(allies,defender){let involved=[...allies,defender];if(!involved.some(u=>hasEffect(u,'grayMummy')))return false;involved.filter(u=>u.kind!=='ra'&&u.kind!=='grayMummy').forEach(u=>u.mummyTransformPending=true);log('A Múmia Cinzenta marcou os envolvidos para se transformarem ao final do turno.','effect');return true}
function attachFireScarab(scarab,target){if(!hasEffect(scarab,'fireScarab')||scarab.row===null||target.row===null)return false;scarab.attachedTo=target.id;scarab.attachedOffset={dr:scarab.row-target.row,dc:scarab.col-target.col};log(`${scarab.name} perdeu o combate, mas ficou preso a ${target.name}.`,'combat');return true}
function followAttachedScarabs(target,fromRow,fromCol){allUnits().filter(u=>u.attachedTo===target.id&&u.row!==null).forEach(scarab=>{let dr=scarab.row-fromRow,dc=scarab.col-fromCol,r=target.row+dr,c=target.col+dc;if(r>=0&&r<ROWS&&c>=0&&c<COLS&&!at(r,c)&&!featureAt(r,c)&&!pitAt(r,c)){scarab.row=r;scarab.col=c}else delete scarab.attachedTo})}
function resolveAmmitContacts(){allUnits().filter(u=>u.row!==null&&hasEffect(u,'ammit')).forEach(ammit=>{let victims=allUnits().filter(v=>v.id!==ammit.id&&v.row!==null&&adjacent(ammit,v)&&effectiveAtk(v,false)<=100);victims.forEach(v=>{let power=effectiveAtk(v,false),name=v.name;if(destroy(v,ammit.owner,'efeito de Ammit')){ammit.bonusAtk=(ammit.bonusAtk||0)+power;log(`${ammit.name} devorou ${name} e ganhou ${power} ATK.`,'combat')}})})}
function resolveEgyptianEndTurn(){allUnits().filter(u=>u.row!==null&&hasEffect(u,'fireSlave')).forEach(u=>u.bonusAtk=(u.bonusAtk||0)+25);allUnits().filter(u=>u.row!==null&&u.attachedTo).forEach(scarab=>{let target=allUnits().find(v=>v.id===scarab.attachedTo&&v.row!==null);if(target){let lost=reduceGoldAttack(target,100);if(lost)log(`${target.name} perdeu ${lost} ATK pelo Escaravelho em Chamas.`,'effect')}else delete scarab.attachedTo});if(state.arena==='burningDesert')allUnits().filter(u=>u.row!==null&&!isFireUnit(u)).forEach(u=>reduceGoldAttack(u,25));allUnits().filter(u=>u.row!==null&&u.mummyTransformPending).forEach(u=>transformIntoGrayMummy(u,'combate com a Múmia Cinzenta'));(state.fireTemples||[]).forEach(t=>t.turnsLeft--);let expired=(state.fireTemples||[]).filter(t=>t.turnsLeft<=0);state.fireTemples=(state.fireTemples||[]).filter(t=>t.turnsLeft>0);expired.forEach(t=>log(`O Templo das Chamas em ${boardCoordinate(t.row,t.col)} foi destruído após 3 turnos.`,'effect'))}
function applyBurningDesertCombat(winner,losingAtk){if(state.arena!=='burningDesert'||!winner||winner.row===null)return;let lost=reduceGoldAttack(winner,losingAtk);if(lost)log(`${winner.name} perdeu ${lost} ATK pelas Areias do Deserto em Chamas.`,'arena')}
function resolveQuickHands(player,index){let p=state.players[player],opponent=state.players[player===1?2:1],choices=opponent.hand.map((key,i)=>({key,i})).filter(item=>effects[item.key]);p.hand.splice(index,1);if(choices.length){let stolen=choices[Math.floor(Math.random()*choices.length)];opponent.hand.splice(stolen.i,1);p.hand.push(stolen.key);log(`${p.name} usou Mãos Rápidas e tomou ${effects[stolen.key].name} da mão adversária.`,'effect')}else{opponent.effectLockPending=true;log(`${p.name} usou Mãos Rápidas: o adversário não poderá usar Efeitos no próximo turno.`,'effect')}}
function processRepugniumTurn(){let victims=[...state.players[state.current].units].filter(u=>u.row!==null&&allUnits().some(rep=>rep.owner!==u.owner&&hasEffect(rep,'repugnium')&&inMovementRadius(rep,u)));victims.forEach(u=>{let jailer=allUnits().find(rep=>rep.owner!==u.owner&&hasEffect(rep,'repugnium')&&inMovementRadius(rep,u)),atk=effectiveAtk(u,false);if(atk<=150){let name=u.name;destroy(u,jailer.owner,'efeito de Repugnium');log(`${jailer.name} destruiu ${name}, que tinha 150 ATK ou menos em seu raio.`,'combat')}else{let lost=reduceGoldAttack(u,150);if(lost)log(`${u.name} perdeu ${lost} ATK por permanecer no raio de ${jailer.name}.`,'effect')}})}
function botUseEgyptianEffects(player,p){if(p.effectLocked)return false;let opponent=state.players[player===1?2:1],mummify=p.hand.indexOf('emberMummify'),target=opponent.units.filter(u=>u.row!==null&&u.kind!=='grayMummy'&&u.kind!=='ra').sort((a,b)=>effectiveAtk(b,false)-effectiveAtk(a,false))[0];if(mummify>=0&&target&&effectiveAtk(target,false)>150){p.hand.splice(mummify,1);transformIntoGrayMummy(target,effects.emberMummify.name);copyEquipmentForRavens('emberMummify');render();return true}let templeIndex=p.hand.indexOf('flameTemple'),fires=p.units.filter(u=>u.row!==null&&isFireUnit(u));if(templeIndex>=0&&fires.length){let cells=[];fires.forEach(u=>[[-1,0],[1,0],[0,-1],[0,1]].forEach(([dr,dc])=>{let r=u.row+dr,c=u.col+dc;if(r>=0&&r<ROWS&&c>=0&&c<COLS&&!at(r,c)&&!featureAt(r,c)&&!pitAt(r,c))cells.push({r,c})}));let cell=cells.sort((a,b)=>Math.abs(a.r-(ROWS-1)/2)-Math.abs(b.r-(ROWS-1)/2))[0];if(cell){p.hand.splice(templeIndex,1);state.fireTemples.push({row:cell.r,col:cell.c,owner:player,turnsLeft:3});log(`${p.name} ergueu o Templo das Chamas em ${boardCoordinate(cell.r,cell.c)}.`,'effect');render();return true}}let quick=p.hand.indexOf('quickHands');if(quick>=0&&(opponent.hand.length||Math.random()<.35)){resolveQuickHands(player,quick);render();return true}return false}
