function completeSwordTransfer(owner,id){if(state.swordQueue[0]!==owner)return;let p=state.players[owner],target=allUnits().find(u=>u.id===id&&u.row!==null);if(!target)return hint('A Espada Maldita só pode passar para um peão que esteja no campo.');target.equipment.push('sword');state.swordQueue.shift();$('#sword-transfer').classList.add('hidden');log(`${p.name} passou a Espada Maldita para ${target.name}.`);render();if(onlineMode)syncOnlineState();if(state.swordQueue.length)setTimeout(openSwordTransfer,180);else if(botControls(state.current))scheduleBot(botFinishTurn,260)}
function animateDraw(source,target,kind){if(!source||!target)return;let a=source.getBoundingClientRect(),b=target.getBoundingClientRect(),ghost=document.createElement('div');ghost.className=`flying-card ${kind}`;ghost.textContent=kind==='pawn'?'⬢':'✦';Object.assign(ghost.style,{left:`${a.left+a.width/2-25}px`,top:`${a.top+a.height/2-34}px`});document.body.append(ghost);source.classList.add('drawing');let animation=ghost.animate([{transform:'translate(0,0) rotateY(0) scale(.8)',opacity:.4},{transform:`translate(${b.left+b.width/2-a.left-a.width/2}px,${b.top+b.height/2-a.top-a.height/2}px) rotateY(540deg) scale(1)`,opacity:1}],{duration:620,easing:'cubic-bezier(.2,.8,.2,1)'});animation.onfinish=()=>{ghost.remove();source.classList.remove('drawing');target.animate([{transform:'scale(.8)'},{transform:'scale(1.12)'},{transform:'scale(1)'}],{duration:280})}}
function openDrawChoice(){if(onlineMode&&state.current!==localPlayer)return;let p=state.players[state.current],a=archetypes[p.archetype];state.awaitingDraw=true;$('#draw-choice-name').textContent=`${p.name} · ${a.name}`;$('#choice-pawn-count').textContent=p.pawnDeck.length;$('#choice-effect-count').textContent=p.effectDeck.length;$('#choice-pawn').disabled=!p.pawnDeck.length;$('#choice-effect').disabled=!p.effectDeck.length;$('#skip-draw').classList.toggle('hidden',!!(p.pawnDeck.length||p.effectDeck.length));$('#turn-draw').classList.remove('hidden');renderHeader()}
function finishDrawChoice(){state.awaitingDraw=false;$('#turn-draw').classList.add('hidden')}
function drawPawn(source=$('#draw-pawn')){let p=state.players[state.current];if(p.drawn||!p.pawnDeck.length)return;p.reserve.push(p.pawnDeck.pop());p.drawn=true;log(`${p.name} escolheu a pilha de Peões.`);render();animateDraw(source,$('#pawn-hand .reserve-piece:last-child'),'pawn');finishDrawChoice();renderHeader();if(state.swordQueue[0]===state.current)setTimeout(openSwordTransfer,180)}
function drawEffect(source=$('#draw-effect')){let p=state.players[state.current];if(p.drawn||!p.effectDeck.length)return;p.hand.push(p.effectDeck.pop());p.drawn=true;log(`${p.name} escolheu a pilha de Efeitos.`);render();animateDraw(source,$('#effect-hand .effect-card:last-child'),'effect');finishDrawChoice();renderHeader()}
function playCard(i){
 if(!canLocalAct())return hint('Aguarde seu turno.');if(state.placementPhase)return hint('Termine de posicionar os peões iniciais primeiro.');let p=state.players[state.current],k=p.hand[i];if(!k)return;hideMobileDetails();selectedEffect=null;pendingCard={key:k,index:i};selected=null;clearAction();pendingCard={key:k,index:i};
 if(effects[k].type==='ARENA'){let xadriaPair=new Set(['roses','blackRoses']);if(state.arena===k||state.arena==='kingdom'&&xadriaPair.has(k)){pendingCard=null;hint(`${effects[k].name} já está ativa — a carta permaneceu na sua mão.`);log(`A Arena repetida de ${p.name} não foi gasta.`);render();return}if(state.arena==='jungle')clearJungleFeatures();let previous=state.arena;state.arena=xadriaPair.has(previous)&&xadriaPair.has(k)&&previous!==k?'kingdom':k;state.arenaOwner=state.current;state.arenaDefeatedStart=state.defeatedCount||0;p.hand.splice(i,1);log(state.arena==='kingdom'?`${effects[previous].name} e ${effects[k].name} convergiram no Reino de Xadria.`:`${p.name} substituiu a Arena por ${effects[k].name}.`);if(state.arena==='abyss')allUnits().filter(u=>u.faceDown).forEach(u=>destroy(u,u.owner===1?2:1,'arena'));pendingCard=null;render();return}
 if(k==='peace'){playPeaceTreaty(p,i);return}
 if(k==='camouflage'){let eligible=p.units.filter(u=>u.row!==null&&u.attackedTurn!==state.turn);if(!eligible.length){pendingCard=null;hint('Nenhum peão pode ser camuflado após atacar — a carta permaneceu na mão.');render();return}eligible.forEach(u=>u.faceDown=true);let abyssVictims=eligible.filter(destroyIfHiddenInAbyss).length;p.hand.splice(i,1);pendingCard=null;let blocked=p.units.filter(u=>u.row!==null&&u.attackedTurn===state.turn).length;log(abyssVictims?`O Abismo do Terror destruiu ${abyssVictims} peão${abyssVictims>1?'ões':''} camuflado${abyssVictims>1?'s':''}.`:`${p.name} camuflou ${eligible.length} peão${eligible.length>1?'ões':''}${blocked?`; ${blocked} que já ${blocked>1?'atacaram permaneceram':'atacou permaneceu'} para cima`:''}.`);render();checkWin();return}
 if(k==='noEscape'){let opponent=state.current===1?2:1;state.players[opponent].moveLocked=true;p.hand.splice(i,1);pendingCard=null;log(`${p.name} jogou Não Há Escapatória: o rival não poderá mover peões no próximo turno.`);render();return}
 if(['pit','blackHole','tunnel'].includes(k)){mode=k;targets=[];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(!at(r,c)&&!featureAt(r,c)&&!pitAt(r,c)&&!(state.blackHoles||[]).some(x=>x.row===r&&x.col===c))targets.push({r,c});hint(cardPrompt(k));renderBoard();return}
 if(k==='reveal'){mode='reveal';targets=allUnits().filter(u=>u.faceDown).map(u=>({r:u.row,c:u.col}));if(!targets.length){pendingCard=null;render();return hint('Não há peões virados para baixo; a carta permaneceu na mão.')}hint(cardPrompt(k));renderBoard();return}
 hint(cardPrompt(k));render()
}
function cardPrompt(k){return{retreat:'Escolha qualquer peão para recuar.',castle:'Escolha uma Torre sua; depois, outro aliado.',sword:'Escolha um peão para equipar.',crown:'Escolha uma Infantaria para receber a Coroa.',bow:'Escolha um peão para equipar com o Arco Primitivo.',asteroid:'Escolha um peão para proteger com o Cinturão de Asteroides.',moon:'Escolha a Terra que receberá a Lua.',eyes:'Escolha um peão para receber os Olhos.',burn:'Escolha um peão para queimar seus equipamentos.',pit:'Escolha uma casa livre para abrir o Poço sem Fundo.',blackHole:'Escolha uma casa livre para o Buraco Negro.',tunnel:'Escolha a primeira entrada do túnel.',reveal:'Escolha um peão virado para baixo.',push:'Escolha o peão que será empurrado.'}[k]}
function equipmentTargetAllowed(key,u,owner=state.current){let restriction=effects[key]?.equipOnly;return !!u&&u.owner===owner&&(!restriction||u.kind===restriction)}
function copyEquipmentForRavens(key){allUnits().filter(raven=>raven.row!==null&&hasEffect(raven,'raven')).forEach(raven=>{state.players[raven.owner].hand.push(key);log(`${raven.name} criou uma cópia de ${effects[key].name}.`)})}
function pushTargets(u){let out=[],dr=u.owner===1?1:-1;for(let r=u.row+dr;r>=0&&r<ROWS;r+=dr){if(at(r,u.col)||obstacleAt(r,u.col))break;out.push({r,c:u.col});if(pitAt(r,u.col))break}return out}
function cardTarget(u,r,c){
 let p=state.players[state.current],{key,index}=pendingCard;
 if(key==='pit'||key==='devotee-pit'){if(u||featureAt(r,c)||pitAt(r,c))return hint('Escolha uma casa completamente livre.');state.pits??=[];state.pits.push({row:r,col:c});log(`${p.name} abriu um Poço sem Fundo em ${boardCoordinate(r,c)}.`)}else if(key==='blackHole'){state.blackHoles??=[];state.blackHoles.push({row:r,col:c,owner:state.current,armedFor:state.current===1?2:1});log(`${p.name} criou um Buraco Negro em ${boardCoordinate(r,c)}.`)}else if(key==='tunnel'){state.tunnelDraft??=[];state.tunnelDraft.push({row:r,col:c,owner:state.current});if(state.tunnelDraft.length===1){targets=targets.filter(t=>!(t.r===r&&t.c===c));hint('Agora escolha a segunda entrada do túnel.');renderBoard();return}state.tunnels??=[];state.tunnels.push(state.tunnelDraft);state.tunnelDraft=[];log(`${p.name} conectou duas entradas de túnel.`)}else if(key==='reveal'){if(!u?.faceDown)return hint('Escolha um peão virado para baixo.');u.faceDown=false;log(`${u.name} foi revelado.`)}else if(key==='push'&&pendingPushTarget){if(!isValidCell(r,c))return hint('Escolha uma das casas destacadas atrás do peão.');let pushed=pendingPushTarget,from=boardCoordinate(pushed.row,pushed.col),fruit=fruitAt(r,c),pit=pitAt(r,c);place(pushed,r,c);if(fruit)collectFruit(pushed,r,c);if(pit)destroy(pushed,pushed.owner===1?2:1,'poço');log(`${pushed.name} foi empurrado de ${from} para ${boardCoordinate(r,c)}${pit?' e caiu no Poço sem Fundo':''}.`)}else{
  if(!u)return hint('Essa carta exige um peão como alvo.');
  if(key==='push'){pendingPushTarget=u;selected=u;mode='push';targets=pushTargets(u);if(!targets.length){pendingPushTarget=null;mode=null;return hint('Este peão não possui nenhuma casa livre atrás dele.')}render();hint('Escolha quantas casas para trás o peão será empurrado.');return}else if(key==='retreat'){if(u.faceDown)return hint('Peões virados para baixo não podem ser movidos por Recuar.');let row=Number(u.origin?.row),col=Number(u.origin?.col);if(!Number.isInteger(row)||!Number.isInteger(col)||row<0||row>=ROWS||col<0||col>=COLS)return hint('A origem deste peão não é válida.');let occupant=at(row,col);if(occupant&&occupant.id!==u.id)return hint('A casa original está ocupada.');let retreatObstacle=obstacleAt(row,col),retreatPit=pitAt(row,col);if(retreatObstacle)state.obstacles=state.obstacles.filter(x=>x!==retreatObstacle);u.row=row;u.col=col;selected=u;if(retreatPit){destroy(u,u.owner===1?2:1,'poço');log(`${u.name} recuou para ${boardCoordinate(row,col)}${retreatObstacle?', destruiu o obstáculo NATURAL':''}, caiu no Poço sem Fundo e concedeu pontos ao adversário.`)}else log(`${u.name} recuou exatamente para ${boardCoordinate(row,col)}${retreatObstacle?', destruindo o obstáculo NATURAL que ocupava a casa.':'.'}`)}else if(['sword','bow','asteroid','crown','moon','eyes'].includes(key)){if(!equipmentTargetAllowed(key,u))return hint(effects[key].equipOnly?`${effects[key].name} só pode ser equipada em ${defs[effects[key].equipOnly].name} do próprio jogador.`:'Equipamentos só podem ser colocados em seus próprios peões.');u.equipment.push(key);copyEquipmentForRavens(key);log(`${u.name} recebeu ${effects[key].name}.`)}else if(key==='burn'){u.equipment=[];log(`Os equipamentos de ${u.name} foram destruídos.`)}else if(key==='castle'){if(!castleFirst){if(!own(u)||!u.name.includes('Torre'))return hint('Primeiro selecione uma Torre sua.');if(u.faceDown)return hint('Uma Torre virada para baixo não pode realizar o roque.');castleFirst=u;hint('Agora selecione outro peão aliado.');return}else{if(!own(u)||u.id===castleFirst.id)return hint('Selecione outro aliado.');if(u.faceDown)return hint('Peões virados para baixo não podem participar do roque.');let oldRow=castleFirst.row,oldCol=castleFirst.col,towerFrom=boardCoordinate(oldRow,oldCol),allyFrom=boardCoordinate(u.row,u.col);castleFirst.row=u.row;castleFirst.col=u.col;u.row=oldRow;u.col=oldCol;log(`${castleFirst.name} foi de ${towerFrom} para ${allyFrom}; ${u.name} foi para ${towerFrom} no roque.`)}}
 }
 if(!pendingCard?.free)p.hand.splice(index,1);pendingCard=null;castleFirst=null;clearAction();render();checkWin();if(key==='devotee-pit'&&initialPlacementResume){let resume=initialPlacementResume;initialPlacementResume=null;continueInitialPlacement(resume.unit,resume.version)}
}
function fusionMaterialFits(card,u,chosen=fusionMaterials){if(!u||u.row===null||chosen.some(x=>x.id===u.id))return false;let abyssMaterial=card.materials?.archetype==='abyss',enemyAllowed=abyssMaterial&&u.owner!==state.current&&state.players[state.current].units.some(d=>hasEffect(d,'devotee')&&adjacent(d,u));if(u.owner!==state.current&&!enemyAllowed)return false;if(card.materials?.requirements){let open=card.materials.requirements.filter(req=>!chosen.some(x=>req.kind?x.kind===req.kind:x.types.includes(req.type)));if(!open.some(req=>req.kind?u.kind===req.kind:u.types.includes(req.type)))return false}else if(card.materials?.kinds&&(!card.materials.kinds.includes(u.kind)||chosen.some(x=>x.kind===u.kind)))return false;else if(card.materials?.type&&!u.types.includes(card.materials.type))return false;else if(abyssMaterial&&archetypeOfUnit(u)!=='abyss'&&!enemyAllowed)return false;return !chosen.length||chosen.some(x=>fusionLinked(x,u))}
function fusionTargets(card){return allUnits().filter(u=>fusionMaterialFits(card,u)).map(u=>({r:u.row,c:u.col}))}
function validFusionSet(card,parts){if(parts.length<card.fusion||!card.variableFusion&&parts.length!==card.fusion)return false;if(card.materials?.requirements&&!card.materials.requirements.every(req=>parts.some(u=>req.kind?u.kind===req.kind:u.types.includes(req.type))))return false;if(card.materials?.kinds&&!card.materials.kinds.every(kind=>parts.some(u=>u.kind===kind)))return false;if(card.materials?.archetype==='abyss'&&parts.filter(u=>archetypeOfUnit(u)==='abyss').length<card.fusion)return false;return fusionSetConnected(parts)}
function beginFusion(card=selected){if(!canLocalAct())return hint('Aguarde seu turno.');let p=state.players[state.current];if(!card?.fusion||card.row!==null||!p.reserve.some(u=>u.id===card.id))return hint('Selecione um Peão Combinado na sua mão de Peões.');if(card.condition==='destroyed-this-turn'&&state.destroyedTurn!==state.turn)return hint('Repugnium exige que um peão tenha sido destruído neste turno.');if(card.condition==='pit-this-turn'&&state.pitDestroyedTurn!==state.turn)return hint('Anssiedium exige que um peão tenha caído em um Poço neste turno.');clearAction();selected=card;mode='combinar';targets=fusionTargets(card);if(!targets.length){clearAction();render();return hint('Não há materiais válidos em campo para iniciar esta combinação.')}render();hint(card.variableFusion?`Escolha ${card.fusion} ou mais materiais em contato; depois clique novamente na Amálgama para combinar · 0 selecionados.`:`Escolha ${card.fusion} materiais em contato · 0/${card.fusion}.`)}
function toggleFusionMaterial(u){let card=selected,index=fusionMaterials.findIndex(x=>x.id===u.id);if(index>=0)fusionMaterials.splice(index,1);else if(fusionMaterialFits(card,u))fusionMaterials.push(u);if(!card.variableFusion&&fusionMaterials.length===card.fusion){if(validFusionSet(card,fusionMaterials))return completeFusion(card,[...fusionMaterials]);fusionMaterials.pop();hint('Esses materiais não formam uma sequência em contato.')}targets=fusionTargets(card);renderBoard();hint(card.variableFusion&&fusionMaterials.length>=card.fusion?`${fusionMaterials.length} materiais selecionados · clique novamente na carta Amálgama para combinar ou escolha mais um.`:card.variableFusion?`Escolha ao menos ${card.fusion} materiais em contato · ${fusionMaterials.length} selecionado${fusionMaterials.length===1?'':'s'}.`:`Escolha ${card.fusion} materiais em contato · ${fusionMaterials.length}/${card.fusion}.`)}
function resolveCombination(f,parts,pos,p,version){if(version!==gameVersion)return;clearAnimationMarks(parts);if(hasEffect(f,'amalgam')){f.atk=parts.reduce((sum,u)=>sum+effectiveAtk(u,false),0);f.movement=[...new Map(parts.flatMap(rawMovementOffsets).map(offset=>[offset.join(','),offset])).values()];f.fusion=parts.length}for(let owner of[1,2])state.players[owner].units=state.players[owner].units.filter(u=>!parts.some(x=>x.id===u.id));p.reserve=p.reserve.filter(u=>u.id!==f.id);f.combinedEntry=true;place(f,pos.row,pos.col);p.units.push(f);state.animating=false;clearAction();selected=f;log(`${f.name} foi criado em ${boardCoordinate(pos.row,pos.col)} ao combinar ${parts.length} materiais ${state.arena==='project'?'em contato ou dentro de seus raios':'em contato'}.`);render();if(hasEffect(f,'sun'))triggerSolarVictory(f.owner);else checkWin();if(onlineMode)syncOnlineState();setTimeout(()=>{if(version!==gameVersion)return;f.combinedEntry=false;renderBoard()},720)}
function completeSolarFusion(f,parts){let p=state.players[state.current],opponent=state.current===1?2:1,pos={row:parts[0].row,col:parts[0].col},version=gameVersion,ordered=(f.materials?.kinds||[]).map(kind=>parts.find(u=>u.kind===kind)).filter(Boolean),absorbStep=300;state.animating=true;clearAction();selected=f;ordered.forEach((u,index)=>{u.solarAbsorbing=true;u.solarDelay=index*absorbStep;u.combineDx=pos.col-u.col;u.combineDy=pos.row-u.row});render();hint('Os oito astros estão convergindo para formar o SOL…');if(onlineMode)syncOnlineAnimationState();setTimeout(()=>{if(version!==gameVersion)return;clearAnimationMarks(parts);p.units=p.units.filter(u=>!parts.some(x=>x.id===u.id));p.reserve=p.reserve.filter(u=>u.id!==f.id);f.solarBirth=true;place(f,pos.row,pos.col);p.units.push(f);selected=f;log(`${f.name} nasceu em ${boardCoordinate(pos.row,pos.col)} após absorver os oito astros, um a um.`);render();if(onlineMode)syncOnlineAnimationState();setTimeout(()=>{if(version!==gameVersion)return;delete f.solarBirth;let defeated=state.players[opponent].units.filter(u=>u.row!==null);defeated.forEach((u,index)=>{u.solarEvaporating=true;u.solarEvaporateDelay=index*90});hint('A luz do SOL está evaporando todos os peões adversários…');render();if(onlineMode)syncOnlineAnimationState();setTimeout(()=>{if(version!==gameVersion)return;state.players[opponent].units=state.players[opponent].units.filter(u=>u.row===null);clearAnimationMarks([f,...defeated]);state.animating=false;clearAction();selected=f;triggerSolarVictory(f.owner);if(onlineMode)syncOnlineState(true)},900+defeated.length*90)},900)},ordered.length*absorbStep+640)}
function completeFusion(f,parts){if(state.animating)return;if(hasEffect(f,'sun'))return completeSolarFusion(f,parts);let p=state.players[state.current],pos={row:parts[0].row,col:parts[0].col},version=gameVersion;state.animating=true;clearAction();selected=f;parts.forEach(u=>{u.combining=true;u.combineDx=pos.col-u.col;u.combineDy=pos.row-u.row});render();hint(`Combinando ${parts.length} materiais…`);if(onlineMode)sendPacket({type:'visual',kind:'combine',materials:parts.map(u=>u.id),pos});setTimeout(()=>resolveCombination(f,parts,pos,p,version),760)}
function useAbility(){
 if(!own(selected)||selected.row===null)return hint('Selecione um peão seu com habilidade utilizável.');if(selected.faceDown)return hint('Revele o peão antes de usar sua habilidade.');if(hasEffect(selected,'neptune')&&neptuneUsedThisTurn(selected.owner))return hint('A habilidade de Netuno já foi usada por este jogador neste turno.');if(selected.abilityTurn===state.turn&&!hasEffect(selected,'atra'))return hint('Esta habilidade já foi usada neste turno.');if(hasEffect(selected,'rider')&&selected.mounted)return hint('Um Montador que já está montado não pode montar outro peão.');
 if(hasEffect(selected,'serpent')){mode='serpent';targets=[];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(!at(r,c)&&!featureAt(r,c)&&!pitAt(r,c))targets.push({r,c});hint('Escolha qualquer casa livre para criar o obstáculo NATURAL.')}else if(selected.kind==='jester'&&!selected.copiedKind){mode='copy';targets=allUnits().filter(u=>u.id!==selected.id&&u.row!==null).map(u=>({r:u.row,c:u.col}));hint('Escolha qualquer peão em campo para copiar seu efeito até o fim da partida.')}else if(hasEffect(selected,'rider')){mode='mount';targets=state.players[state.current].units.filter(u=>u.id!==selected.id&&effectContact(selected,u)&&archetypeOfUnit(u)==='wild'&&!u.mounted).map(u=>({r:u.row,c:u.col}));hint(`Escolha um aliado Selvagem ${state.arena==='project'?'em seu raio':'adjacente'} para montar.`)}else if(hasEffect(selected,'neptune'))return beginNeptuneAbility(selected);else if(hasEffect(selected,'monkey')){mode='monkey-pawn';targets=state.players[state.current].units.filter(u=>u.id!==selected.id&&u.types.includes('NATURAL')&&effectContact(selected,u)).map(u=>({r:u.row,c:u.col}));hint('Escolha um aliado NATURAL em contato.')}else if(hasEffect(selected,'impoluto')){if(effectiveAtk(selected,false)<100)return hint('Impoluto precisa ter ao menos 100 ATK para usar a habilidade.');mode='impoluto';targets=allUnits().filter(u=>u.id!==selected.id&&inMovementRadius(selected,u)).map(u=>({r:u.row,c:u.col}));hint('Escolha outro peão dentro do raio para receber 200 ATK.')}else if(hasEffect(selected,'atra')){mode='atra-sacrifice';targets=state.players[state.current].units.filter(u=>u.id!==selected.id&&inMovementRadius(selected,u)).map(u=>({r:u.row,c:u.col}));hint('Escolha um aliado no raio para sacrificar.')}else return hint(selected.kind==='jester'?'O Bobo já mantém o efeito copiado até o fim da partida.':'A habilidade deste peão é automática.');if(!targets.length){clearAction();return hint('Não há um alvo válido para esta habilidade.')}renderBoard()
}
function beginMonkeyDestination(monkey,target){pendingAbilityTarget=target;mode='monkey-dest';targets=movementOffsets(monkey).map(([dr,dc])=>({r:monkey.row+dr,c:monkey.col+dc})).filter(pos=>pos.r>=0&&pos.r<ROWS&&pos.c>=0&&pos.c<COLS&&!at(pos.r,pos.c)&&!obstacleAt(pos.r,pos.c));hint(`Escolha para onde ${target.name} será levado.`);renderBoard()}
function moveWithMonkey(monkey,target,r,c){let from=boardCoordinate(target.row,target.col);place(target,r,c);monkey.abilityTurn=state.turn;log(`${monkey.name} moveu ${target.name} de ${from} para ${boardCoordinate(r,c)}.`);clearAction();selected=monkey;render()}
function grantImpolutoPower(source,target){source.bonusAtk=(source.bonusAtk||0)-100;target.bonusAtk=(target.bonusAtk||0)+200;source.abilityTurn=state.turn;log(`${source.name} concedeu 200 ATK a ${target.name} e perdeu 100 ATK.`);clearAction();selected=source;render()}
function sacrificeForAtra(source,target){destroy(target,null,'sacrifício');source.atraExtraMoves=(source.atraExtraMoves||0)+1;source.atraExtraAttacks=(source.atraExtraAttacks||0)+1;state.players[source.owner].moved=false;source.attackedTurn=0;source.attackUsageTurn=0;source.attacksUsed=0;log(`${source.name} sacrificou ${target.name} e ganhou um movimento e um ataque extras neste turno.`);clearAction();selected=source;render()}
function createObstacle(u,r,c){state.obstacles.push({row:r,col:c,type:'NATURAL',owner:u.owner});u.abilityTurn=state.turn;log(`${u.name} criou um obstáculo NATURAL.`);clearAction();render()}
function clearJungleFeatures(){let before=state.obstacles.length;state.obstacles=state.obstacles.filter(feature=>feature.source!=='jungle');let removed=before-state.obstacles.length;if(removed)log(`A Selva Selvagem saiu de campo e removeu ${removed} obstáculo${removed>1?'s':''} ou fruta${removed>1?'s':''}.`)}
function jungleSpawnBlocked(r,c){return !!(at(r,c)||featureAt(r,c)||pitAt(r,c)||(state.blackHoles||[]).some(item=>item.row===r&&item.col===c)||(state.tunnels||[]).flat().some(item=>item.row===r&&item.col===c)||(state.tunnelDraft||[]).some(item=>item.row===r&&item.col===c))}
function spawnJungleFeature(){let free=[],jungleFeatures=state.obstacles.filter(feature=>feature.source==='jungle');for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(!jungleSpawnBlocked(r,c))free.push({r,c});if(!free.length||jungleFeatures.length>=free.length)return;let pos=free[Math.floor(Math.random()*free.length)],fruit=Math.random()<.5;state.obstacles.push({row:pos.r,col:pos.c,type:fruit?'FRUIT':'NATURAL',owner:state.arenaOwner,source:'jungle'});log(`A Selva Selvagem criou ${fruit?'uma fruta':'um obstáculo NATURAL'} em ${boardCoordinate(pos.r,pos.c)}.`)}
function copyEffect(jester,target){jester.copiedKind=target.kind;jester.abilityTurn=state.turn;log(`${jester.name} copiou o efeito de ${target.name} até o fim da partida.`);clearAction();render()}
function mountRider(rider,target){if(!rider||rider.mounted||!hasEffect(rider,'rider')||!target||target.mounted||!effectContact(rider,target))return hint('Este Montador ou alvo não pode realizar uma nova montagem.');state.players[rider.owner].units=state.players[rider.owner].units.filter(u=>u.id!==rider.id);target.mounted='rider';target.abilityTurn=state.turn;selected=target;log(`${rider.name} montou ${target.name}; seus ataques foram somados.`);clearAction();render()}
function recoverBotTurn(error){console.error('Falha durante o turno automático',error);if(!botMode||!botControls(state.current))return;state.animating=false;clearAnimationMarks(allUnits());clearAction();log(`${state.players[state.current].name} descartou uma jogada inválida e continuará o turno.`);render();scheduleBot(botFinishTurn,180)}
function armBotWatchdog(){clearTimeout(botWatchdogTimer);let version=gameVersion,player=state?.current,turn=state?.turn;botWatchdogTimer=setTimeout(()=>{if(!botMode||version!==gameVersion||state?.current!==player||state?.turn!==turn||state?.forfeitWinner||$('#winner-dialog')?.open||!botControls(player))return;state.animating=false;clearAnimationMarks(allUnits());clearAction();log(`${state.players[player].name} retomou o turno após uma jogada automática ficar sem continuação.`);render();scheduleBot(state.placementPhase?botPlaceInitial:botFinishTurn,180)},6000)}
function scheduleBot(action,delay=450){clearTimeout(botTimer);armBotWatchdog();let version=gameVersion;botTimer=setTimeout(()=>{if(!botMode||version!==gameVersion||state?.forfeitWinner||$('#winner-dialog')?.open)return;try{action()}catch(error){recoverBotTurn(error)}},delay)}
function botPlaceInitial(){let player=state.placementPlayer;if(!botControls(player)||!state.placementPhase)return;let p=state.players[player];if(pendingCard?.key==='devotee-pit'){let target=[...targets].sort((a,b)=>Math.abs(a.r-(ROWS-1)/2)+Math.abs(a.c-(COLS-1)/2)-Math.abs(b.r-(ROWS-1)/2)-Math.abs(b.c-(COLS-1)/2))[0];if(target)cardTarget(at(target.r,target.c),target.r,target.c);if(p.initialUnits.length)scheduleBot(botPlaceInitial,720);return}let u=p.initialUnits[0];if(!u)return;selected=u;mode='initial-deploy';targets=initialTargetsFor(player);let towardCenter=player===1?(a,b)=>a.r-b.r:(a,b)=>b.r-a.r,target=[...targets].sort((a,b)=>towardCenter(a,b)||Math.abs(a.c-(COLS-1)/2)-Math.abs(b.c-(COLS-1)/2))[0];if(!target)return;placeInitialPawn(target.r,target.c);if(p.initialUnits.length||pendingCard?.key==='devotee-pit')scheduleBot(botPlaceInitial,720)}
function botStrategicPowerValue(attack,immortalBlocker=false){return immortalBlocker?600:attack}
function botGameAdvantageValue(scoreDiff,unitDiff,powerDiff){return scoreDiff*2000+unitDiff*350+powerDiff}
function botGameAdvantageScore(player=botActor()){let opponent=botOpponent(player),field=owner=>state.players[owner].units.filter(u=>u.row!==null),power=owner=>field(owner).reduce((sum,u)=>sum+botStrategicPowerValue(effectiveAtk(u,false),state.players[owner].archetype==='xadria'&&hasEffect(u,'duck')),0),p=state.players[player],rival=state.players[opponent];return botGameAdvantageValue(p.score-rival.score,field(player).length-field(opponent).length,power(player)-power(opponent))}
function botFusionMaterials(card,p){return p.units.filter(u=>u.row!==null&&(card.materials?.kinds?.includes(u.kind)||card.materials?.type&&u.types.includes(card.materials.type)))}
function botFusionCoverage(card,p){let materials=botFusionMaterials(card,p);return card.materials?.kinds?card.materials.kinds.filter(kind=>materials.some(u=>u.kind===kind)).length:Math.min(card.fusion,materials.length)}
function botFusionMissingCount(p){let plans=p.reserve.filter(card=>card.fusion);return plans.length?Math.min(...plans.map(card=>Math.max(0,card.fusion-botFusionCoverage(card,p)))):0}
function botFusionSetupScore(p){return Math.max(0,...p.reserve.filter(card=>card.fusion).map(card=>{let materials=botFusionMaterials(card,p),coverage=botFusionCoverage(card,p),links=0;for(let i=0;i<materials.length;i++)for(let j=i+1;j<materials.length;j++)if(effectContact(materials[i],materials[j]))links++;return coverage*30000+Math.min(card.fusion-1,links)*45000}))}
function botFusionMaterialPriority(p,u){return Math.max(0,...p.reserve.filter(card=>card.fusion).map(card=>{let field=botFusionMaterials(card,p),needed=card.materials?.kinds?card.materials.kinds.includes(u.kind)&&!field.some(x=>x.kind===u.kind):card.materials?.type&&u.types.includes(card.materials.type)&&field.length<card.fusion;return needed?card.fusion*2500+card.atk-botStrategicPowerValue(effectiveAtk(u,false),p.archetype==='xadria'&&hasEffect(u,'duck')):0}))}
function botDraw(){let player=botActor(),p=state.players[player];if(p.drawn)return;let ahead=botGameAdvantageScore(player)>0,needsFusionMaterial=botFusionMissingCount(p)>0,drawPawnNow=p.pawnDeck.length&&(needsFusionMaterial||!ahead&&(p.reserve.filter(u=>!u.fusion).length<2||!p.effectDeck.length));if(drawPawnNow){p.reserve.push(p.pawnDeck.pop());log(`${p.name} comprou um Peão${needsFusionMaterial?' procurando materiais para combinar':''}.`)}else if(p.effectDeck.length){p.hand.push(p.effectDeck.pop());log(`${p.name} comprou uma carta de Efeito.`)}else if(p.pawnDeck.length){p.reserve.push(p.pawnDeck.pop());log(`${p.name} comprou um Peão.`)}p.drawn=true;state.awaitingDraw=false}
function botUsePushEffect(player,p,requirePit=false){let index=p.hand.indexOf('push');if(index<0)return false;let enemies=state.players[botOpponent(player)].units.filter(u=>u.row!==null&&!u.faceDown),choices=[];enemies.forEach(unit=>pushTargets(unit).forEach((target,step)=>choices.push({unit,target,step,pit:!!pitAt(target.r,target.c)})));if(requirePit)choices=choices.filter(choice=>choice.pit);let choice=choices.sort((a,b)=>Number(b.pit)-Number(a.pit)||b.step-a.step)[0];if(!choice)return false;let from=boardCoordinate(choice.unit.row,choice.unit.col),fruit=fruitAt(choice.target.r,choice.target.c),pit=pitAt(choice.target.r,choice.target.c);place(choice.unit,choice.target.r,choice.target.c);if(fruit)collectFruit(choice.unit,choice.target.r,choice.target.c);if(pit)destroy(choice.unit,player,'poço');p.hand.splice(index,1);log(`${p.name} usou Empurrão em ${choice.unit.name}: ${from} → ${boardCoordinate(choice.target.r,choice.target.c)}${pit?' e o lançou no Poço sem Fundo':''}.`);render();checkWin();return true}
function botUsePitEffect(player,p){let index=p.hand.indexOf('pit');if(index<0)return false;let enemies=state.players[botOpponent(player)].units.filter(u=>u.row!==null),free=[];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(!at(r,c)&&!featureAt(r,c)&&!pitAt(r,c))free.push({r,c});if(!free.length||!enemies.length)return false;let movement=new Set,forced=new Set;enemies.forEach(enemy=>{if(!enemy.faceDown)moveTargets(enemy).forEach(cell=>movement.add(`${cell.r},${cell.c}`));pushTargets(enemy).forEach(cell=>forced.add(`${cell.r},${cell.c}`))});let choice=free.map(cell=>{let key=`${cell.r},${cell.c}`,distance=Math.min(...enemies.map(enemy=>Math.abs(cell.r-enemy.row)+Math.abs(cell.c-enemy.col)));return{...cell,score:(forced.has(key)?3000:0)+(movement.has(key)?1500:0)-distance*20-Math.abs(cell.c-(COLS-1)/2)}}).sort((a,b)=>b.score-a.score)[0];state.pits??=[];state.pits.push({row:choice.r,col:choice.c});p.hand.splice(index,1);log(`${p.name} abriu um Poço sem Fundo em ${boardCoordinate(choice.r,choice.c)}.`);render();return true}
function botUseRetreatEffect(player,p){let index=p.hand.indexOf('retreat');if(index<0)return false;let enemies=state.players[botOpponent(player)].units.filter(u=>u.row!==null&&!u.faceDown&&Number.isInteger(u.origin?.row)&&Number.isInteger(u.origin?.col)&&!at(u.origin.row,u.origin.col)).map(u=>({u,distance:Math.abs(u.row-u.origin.row)+Math.abs(u.col-u.origin.col)})).filter(choice=>choice.distance>0).sort((a,b)=>b.distance-a.distance);let choice=enemies[0];if(!choice)return false;let u=choice.u,row=u.origin.row,col=u.origin.col,from=boardCoordinate(u.row,u.col),obstacle=obstacleAt(row,col),pit=pitAt(row,col);if(obstacle)state.obstacles=state.obstacles.filter(x=>x!==obstacle);place(u,row,col);if(pit)destroy(u,player,'poço');p.hand.splice(index,1);log(`${p.name} usou Recuar! em ${u.name}: ${from} → ${boardCoordinate(row,col)}${obstacle?', destruindo o obstáculo':''}${pit?' e fazendo-o cair no Poço sem Fundo':''}.`);render();checkWin();return true}
function botUseCamouflageEffect(player,p){let index=p.hand.indexOf('camouflage');if(index<0||state.arena==='abyss')return false;let eligible=p.units.filter(u=>u.row!==null&&!u.faceDown&&u.attackedTurn!==state.turn),threatened=eligible.some(u=>botMoveRisk(u)>0);if(!eligible.length||!threatened)return false;eligible.forEach(u=>u.faceDown=true);p.hand.splice(index,1);log(`${p.name} camuflou ${eligible.length} peão${eligible.length>1?'ões':''} ameaçado${eligible.length>1?'s':''}.`);render();return true}
function botUseEyesEffect(player,p){let index=p.hand.indexOf('eyes');if(index<0)return false;let targets=state.players[botOpponent(player)].units.filter(u=>u.row!==null&&!u.equipment.includes('eyes')).map(u=>({u,canMove:moveTargets(u).length>0,value:(u.fusion||1)*10000+effectiveAtk(u,false)})).sort((a,b)=>Number(b.canMove)-Number(a.canMove)||b.value-a.value),target=targets[0]?.u;if(!target)return false;p.hand.splice(index,1);target.equipment.push('eyes');copyEquipmentForRavens('eyes');log(`${p.name} equipou ${effects.eyes.name} no peão adversário ${target.name}.`);render();return true}
function botCastleSwapValue(riskBefore,riskAfter,fusionGain,attackGain,guardGain){return(riskBefore-riskAfter)*5+fusionGain*5+attackGain*30+guardGain*2}
function botCastleGuardValue(tower,p){return p.units.filter(u=>u.id!==tower.id&&u.row!==null&&!u.faceDown&&effectContact(tower,u)).reduce((sum,u)=>sum+(u.fusion||1)*1200+effectiveAtk(u,true),0)}
function botPrepareCastle(){let p=state.players[botActor()];if(p.archetype!=='xadria'||!p.hand.includes('castle')||p.botCastleTurn===state.turn||p.botCastleRevealTurn===state.turn)return false;let ally=p.units.some(u=>u.row!==null&&!u.faceDown),tower=p.units.find(u=>u.row!==null&&u.faceDown&&u.name.includes('Torre')&&u.attackedTurn!==state.turn&&u.flippedTurn!==state.turn);if(!ally||!tower)return false;p.botCastleRevealTurn=state.turn;return botSetFaceDown(tower,false)}
function botUseCastleEffect(player,p){let index=p.hand.indexOf('castle');if(index<0||p.archetype!=='xadria'||p.botCastleTurn===state.turn)return false;let towers=p.units.filter(u=>u.row!==null&&!u.faceDown&&u.name.includes('Torre')),allies=p.units.filter(u=>u.row!==null&&!u.faceDown),fusionBefore=botFusionSetupScore(p),attackBefore=botAttackChoices()[0]?.value||0,choices=[];towers.forEach(tower=>allies.filter(ally=>ally.id!==tower.id).forEach(ally=>{let towerRow=tower.row,towerCol=tower.col,allyRow=ally.row,allyCol=ally.col,riskBefore=botProjectedEnemyRisk(tower)+botProjectedEnemyRisk(ally),guardBefore=botCastleGuardValue(tower,p);tower.row=allyRow;tower.col=allyCol;ally.row=towerRow;ally.col=towerCol;let riskAfter=botProjectedEnemyRisk(tower)+botProjectedEnemyRisk(ally),fusionGain=botFusionSetupScore(p)-fusionBefore,attackGain=(botAttackChoices()[0]?.value||0)-attackBefore,guardGain=botCastleGuardValue(tower,p)-guardBefore,score=botCastleSwapValue(riskBefore,riskAfter,fusionGain,attackGain,guardGain);tower.row=towerRow;tower.col=towerCol;ally.row=allyRow;ally.col=allyCol;if(score>0)choices.push({tower,ally,score})}));let choice=choices.sort((a,b)=>b.score-a.score)[0];if(!choice)return false;let towerFrom=boardCoordinate(choice.tower.row,choice.tower.col),allyFrom=boardCoordinate(choice.ally.row,choice.ally.col),row=choice.tower.row,col=choice.tower.col;choice.tower.row=choice.ally.row;choice.tower.col=choice.ally.col;choice.ally.row=row;choice.ally.col=col;p.hand.splice(index,1);p.botCastleTurn=state.turn;log(`${p.name} usou Rocar Torre: ${choice.tower.name} foi de ${towerFrom} para ${allyFrom}, protegendo a formação.`);render();return true}
function botPlayEffect(){
 let player=botActor(),opponent=botOpponent(player),p=state.players[player];
 if(botUsePushEffect(player,p,true)||botUseCastleEffect(player,p)||botUsePitEffect(player,p)||botUsePushEffect(player,p)||botUseEyesEffect(player,p))return true;
 let xadriaPair=new Set(['roses','blackRoses']),arenaIndex=p.hand.findIndex(k=>effects[k].type==='ARENA'&&state.arena!==k&&!(state.arena==='kingdom'&&xadriaPair.has(k)));
 if(arenaIndex>=0){let key=p.hand.splice(arenaIndex,1)[0],previous=state.arena;if(previous==='jungle')clearJungleFeatures();state.arena=xadriaPair.has(previous)&&xadriaPair.has(key)&&previous!==key?'kingdom':key;state.arenaOwner=player;state.arenaDefeatedStart=state.defeatedCount||0;log(state.arena==='kingdom'?`${effects[previous].name} e ${effects[key].name} convergiram no Reino de Xadria.`:`${p.name} ativou a Arena ${effects[key].name}.`);if(state.arena==='abyss')allUnits().filter(u=>u.faceDown).forEach(u=>destroy(u,u.owner===1?2:1,'arena'));render();return true}
 let burnIndex=p.hand.indexOf('burn'),burnTarget=state.players[opponent].units.find(u=>u.row!==null&&u.equipment.length);if(burnIndex>=0&&burnTarget){p.hand.splice(burnIndex,1);burnTarget.equipment=[];log(`${p.name} destruiu os equipamentos de ${burnTarget.name}.`);render();return true}
 let equipmentIndex=p.hand.findIndex(k=>k!=='eyes'&&effects[k].type==='EQUIPAMENTO'&&p.units.some(u=>u.row!==null&&equipmentTargetAllowed(k,u,player)&&!u.equipment.includes(k))),equipmentKey=equipmentIndex>=0?p.hand[equipmentIndex]:null,bearer=p.units.filter(u=>u.row!==null&&equipmentKey&&equipmentTargetAllowed(equipmentKey,u,player)&&!u.equipment.includes(equipmentKey)).sort((a,b)=>effectiveAtk(b,false)-effectiveAtk(a,false))[0];if(equipmentIndex>=0&&bearer){let key=p.hand.splice(equipmentIndex,1)[0];bearer.equipment.push(key);copyEquipmentForRavens(key);log(`${p.name} equipou ${effects[key].name} em ${bearer.name}.`);render();return true}
 if(botUseRetreatEffect(player,p)||botUseCamouflageEffect(player,p))return true;let peaceIndex=p.hand.indexOf('peace'),winningAttack=botAttackChoices().some(choice=>choice.outcome==='win');if(peaceIndex>=0&&!winningAttack&&!playerAttackedThisTurn(player))return playPeaceTreaty(p,peaceIndex);return false
}
function botDeployPawn(){let player=botActor(),p=state.players[player];if(p.deployed)return false;let normal=p.reserve.filter(card=>!card.fusion),fusionMaterial=[...normal].map(card=>({card,priority:botFusionMaterialPriority(p,card)})).sort((a,b)=>b.priority-a.priority)[0],u=fusionMaterial?.priority?fusionMaterial.card:p.archetype==='xadria'?normal.find(card=>hasEffect(card,'duck'))||normal[0]:normal[0];if(!u)return false;let cells=[],rows=player===1?[ROWS-2,ROWS-1]:[0,1];for(let r of rows)for(let c=0;c<COLS;c++)if(!at(r,c)&&!obstacleAt(r,c)&&!pitAt(r,c))cells.push({r,c});let towardCenter=player===1?(a,b)=>a.r-b.r:(a,b)=>b.r-a.r,target=cells.sort((a,b)=>towardCenter(a,b)||Math.abs(a.c-(COLS-1)/2)-Math.abs(b.c-(COLS-1)/2))[0];if(!target)return false;selected=u;doDeploy(u,target.r,target.c);return true}
function combinationsOf(items,size,start=0,picked=[],out=[]){if(picked.length===size){out.push([...picked]);return out}for(let i=start;i<=items.length-(size-picked.length);i++){picked.push(items[i]);combinationsOf(items,size,i+1,picked,out);picked.pop()}return out}
function botFusionCandidateSets(card,candidates,limit=64){let out=[];function visit(start,picked){if(out.length>=limit)return;if(picked.length===card.fusion){if(validFusionSet(card,picked))out.push([...picked]);return}for(let i=start;i<=candidates.length-(card.fusion-picked.length)&&out.length<limit;i++){let candidate=candidates[i];if(!fusionMaterialFits(card,candidate,picked))continue;picked.push(candidate);visit(i+1,picked);picked.pop()}}visit(0,[]);return out}
function botCombinationWinsNow(card,parts){let owner=botActor();if(hasEffect(card,'sun'))return true;if(attacksLocked(owner))return false;let needed=(state.pointGoal||10)-state.players[owner].score;if(needed<=0)return true;let enemies=state.players[botOpponent(owner)].units.filter(u=>u.row!==null&&!u.faceDown&&!hasEffect(u,'duck')&&!hasEquipment(u,'asteroid')&&(u.mounted?1:u.fusion||1)>=needed);return parts.some(material=>{let preview={...card,owner,row:material.row,col:material.col,faceDown:false,equipment:[],mounted:null};return enemies.some(enemy=>canAttackTarget(preview,enemy)&&effectiveAtk(preview,false)>effectiveAtk(enemy,true)&&!state.players[enemy.owner].units.some(tower=>tower.id!==enemy.id&&hasEffect(tower,'tower')&&effectContact(tower,enemy)))})}
function botCombinePawn(){let p=state.players[botActor()],options=[],fusionCards=[...new Map(p.reserve.filter(card=>card.fusion).map(card=>[card.kind,card])).values()];fusionCards.forEach(card=>{let candidates=p.units.filter(u=>fusionMaterialFits(card,u,[])).sort((a,b)=>Number(!!a.fusion)-Number(!!b.fusion)||a.equipment.length-b.equipment.length||effectiveAtk(a,false)-effectiveAtk(b,false));botFusionCandidateSets(card,candidates).forEach(parts=>options.push({card,parts,usesCombined:parts.some(u=>u.fusion),value:card.fusion*1000+card.atk-parts.reduce((sum,u)=>sum+botStrategicPowerValue(effectiveAtk(u,false),p.archetype==='xadria'&&hasEffect(u,'duck'))+u.equipment.length*300,0)}))});let normalOptions=options.filter(option=>!option.usesCombined),winningExceptions=options.filter(option=>option.usesCombined&&botCombinationWinsNow(option.card,option.parts)),choice=(normalOptions.length?normalOptions:winningExceptions).sort((a,b)=>b.value-a.value)[0];if(!choice)return false;selected=choice.card;completeFusion(choice.card,choice.parts);return true}
function botUseMount(){let p=state.players[botActor()],choices=[];p.units.filter(u=>u.kind==='rider'&&u.row!==null&&!u.mounted).forEach(rider=>p.units.filter(target=>target.id!==rider.id&&target.row!==null&&effectContact(rider,target)&&target.name.includes('Selvagem')&&!target.mounted).forEach(target=>choices.push({rider,target,value:effectiveAtk(target,false)+rawMovementOffsets(target).length*10})));let choice=choices.sort((a,b)=>b.value-a.value)[0];if(!choice)return false;mountRider(choice.rider,choice.target);return true}
function botUseNeptune(){let player=botActor();if(neptuneUsedThisTurn(player))return false;let p=state.players[player],choices=[];p.units.filter(u=>u.row!==null&&hasEffect(u,'neptune')).forEach(neptune=>allUnits().filter(target=>target.row!==null&&neptuneLanding(neptune,target)).forEach(target=>choices.push({neptune,target,value:(target.owner===player?-1:1)*effectiveAtk(target,false)})));let choice=choices.sort((a,b)=>b.value-a.value)[0];if(!choice)return false;selected=choice.neptune;return activateNeptunePush(choice.neptune,choice.target)}
function attackGroup(attacker,defender){return[attacker,...state.players[attacker.owner].units.filter(u=>u.id!==attacker.id&&u.row!==null&&!u.faceDown&&adjacent(u,defender))]}
function groupAttackPower(attacker,defender){let allies=attackGroup(attacker,defender),attack=allies.reduce((sum,u)=>sum+effectiveAtk(u,false),0);if(allies.length>1&&allies.some(u=>hasEffect(u,'infantry')))attack+=Math.max(...allies.map(u=>effectiveAtk(u,false)));return attack}
function botIsDefensiveByPower(ownTotal,enemyTotal){return ownTotal<enemyTotal}
function botDefensivePosture(player=botActor()){let opponent=botOpponent(player),total=owner=>state.players[owner].units.filter(u=>u.row!==null&&!u.faceDown).reduce((sum,u)=>sum+effectiveAtk(u,false),0);return botIsDefensiveByPower(total(player),total(opponent))}
function botAttackChoices(){let player=botActor(),opponent=botOpponent(player);if(attacksLocked(player))return[];let p=state.players[player],defensive=botDefensivePosture(player),attackers=p.units.filter(u=>u.row!==null&&!u.faceDown&&canUnitAttack(u)),defenders=state.players[opponent].units.filter(u=>u.row!==null&&!hasEffect(u,'duck')),choices=[];attackers.forEach(attacker=>defenders.forEach(defender=>{if(!canAttackTarget(attacker,defender))return;let attack=groupAttackPower(attacker,defender),defense=effectiveAtk(defender,true),allies=attackGroup(attacker,defender),joint=allies.length>1,gain=defender.fusion||1,loss=allies.reduce((sum,u)=>sum+(u.fusion||1),0),mars=allies.some(u=>hasEffect(u,'mars')&&inMovementRadius(u,defender)),outcome=defender.faceDown?'reveal':attack>defense||mars?'win':attack===defense&&gain>=loss?'trade':null;if(outcome){let base=outcome==='win'?100000+gain*1000+defense+(attack-defense):outcome==='trade'?50000+gain*1000-loss*500:150,jointBonus=defensive&&joint?35000+allies.length*5000:joint?2500:0;choices.push({attacker,defender,attack,defense,allies,joint,outcome,value:base+jointBonus})}}));return choices.sort((a,b)=>b.value-a.value)}
function botMoveRisk(u){if(hasEffect(u,'duck'))return 0;let opponent=botOpponent(u.owner),defense=effectiveAtk(u,true),threats=state.players[opponent].units.filter(attacker=>attacker.row!==null&&!attacker.faceDown&&canAttackTarget(attacker,u)).map(attacker=>{let attack=groupAttackPower(attacker,u);return attack>=defense?attack-defense+1:0});return Math.max(0,...threats)}
function botCanMoveUnit(u,p=state.players[botActor()]){if(hasEffect(u,'duck'))return u.movedTurn!==state.turn;return!p.moved||hasEffect(u,'hawk')&&hawkMovesThisTurn(u)===1||hasEffect(u,'mercury')&&mercuryMovesThisTurn(u)===1&&mercuryCanMoveAgain(u)}
function botMatchupScore(ownAttack,enemyAttack,distance,risk){let advantage=ownAttack-enemyAttack,aggressive=advantage>=0;return advantage*2+(aggressive?-distance*65:distance*25)-risk*(aggressive?550:1800)}
function botRepetitionPenalty(history,target){let recent=(history||[]).slice(-6),visits=recent.filter(move=>move.toRow===target.r&&move.toCol===target.c).length,last=recent[recent.length-1],reversal=last&&last.fromRow===target.r&&last.fromCol===target.c;return visits*24000+(reversal?70000:0)}
function botAdvanceProgress(owner,row,rows=ROWS){return owner===1?rows-1-row:row}
function botEnemySpawnDistance(owner,row,rows=ROWS){return owner===1?Math.max(0,row-1):Math.max(0,rows-2-row)}
function botFieldControlValue(advance,supportGap,spawnDistance){let advanceValue=spawnDistance>2?advance*16000:0,caution=spawnDistance===0?90000:spawnDistance===1?50000:spawnDistance===2?16000:0;return advanceValue+supportGap*5500-caution}
function botResponseLossValue(attack,defense,points=1,faceDown=false,immortal=false,forced=false){if(immortal)return 0;if(faceDown)return 120;if(forced||attack>=defense)return points*1400+defense+Math.max(0,attack-defense);return 0}
function botAttackResponseRisk(attacker,defender){if(!canAttackTarget(attacker,defender))return 0;let allies=attackGroup(attacker,defender),attack=groupAttackPower(attacker,defender),defense=effectiveAtk(defender,true),forced=allies.some(u=>hasEquipment(u,'sword')||hasEffect(u,'mars')&&inMovementRadius(u,defender))||hasEquipment(defender,'sword'),risk=botResponseLossValue(attack,defense,defender.fusion||1,defender.faceDown,hasEffect(defender,'duck'),forced);if(hasEquipment(defender,'asteroid')||defender.mounted)risk*=.35;return risk}
function botProjectedEnemyRisk(defender){let enemies=state.players[botOpponent(defender.owner)].units.filter(u=>u.row!==null&&!u.faceDown),worst=Math.max(0,...enemies.map(enemy=>botAttackResponseRisk(enemy,defender)));enemies.filter(mover=>!uranusBlocking(mover)&&(!hasEffect(mover,'archer')||canArcherMove(mover))).forEach(mover=>{let row=mover.row,col=mover.col,options=moveTargets(mover).filter(target=>!pitAt(target.r,target.c));options.forEach(target=>{mover.row=target.r;mover.col=target.c;worst=Math.max(worst,botAttackResponseRisk(mover,defender))});mover.row=row;mover.col=col});return worst}
function botFlipDecisionValue(attackValue,advance,risk,points=1){return attackValue*100+advance*16000-risk*4+points*800}
function botSetFaceDown(u,faceDown){if(!u||u.row===null||u.owner!==botActor()||u.faceDown===faceDown||u.attackedTurn===state.turn||u.flippedTurn===state.turn||faceDown&&state.arena==='abyss')return false;u.faceDown=faceDown;u.flippedTurn=state.turn;log(`${u.name} foi virado ${faceDown?'para baixo para se proteger':'para cima para agir'}.`);render();return true}
function botChooseReveal(){let player=botActor(),p=state.players[player],canRevealForMove=p.botMoveRevealTurn!==state.turn&&!p.moved,options=[];p.units.filter(u=>u.row!==null&&u.faceDown&&u.attackedTurn!==state.turn&&u.flippedTurn!==state.turn).forEach(u=>{u.faceDown=false;let attacks=botAttackChoices().filter(choice=>choice.allies.some(ally=>ally.id===u.id)),attackValue=attacks[0]?.value||0,moves=!uranusBlocking(u)&&(!hasEffect(u,'archer')||canArcherMove(u))?moveTargets(u).filter(target=>!pitAt(target.r,target.c)):[],advance=Math.max(-99,...moves.map(target=>botAdvanceProgress(player,target.r)-botAdvanceProgress(player,u.row))),risk=botProjectedEnemyRisk(u);u.faceDown=true;let purpose=attackValue?'attack':'move';if(attackValue||canRevealForMove&&moves.length&&advance>=0&&risk===0)options.push({u,purpose,score:botFlipDecisionValue(attackValue,Math.max(0,advance),risk,u.fusion||1)})});return options.sort((a,b)=>b.score-a.score)[0]||null}
function botChooseHide(){if(state.arena==='abyss')return null;let p=state.players[botActor()],options=p.units.filter(u=>u.row!==null&&!u.faceDown&&!hasEffect(u,'duck')&&u.attackedTurn!==state.turn&&u.flippedTurn!==state.turn).map(u=>({u,risk:botProjectedEnemyRisk(u),value:(u.fusion||1)*1000+effectiveAtk(u,true)})).filter(choice=>choice.risk>0);return options.sort((a,b)=>b.risk-a.risk||b.value-a.value)[0]?.u||null}
function botBestMovePlan(){let player=botActor(),p=state.players[player],defensive=botDefensivePosture(player),enemies=state.players[botOpponent(player)].units.filter(u=>u.row!==null);if(!enemies.length)return null;let field=p.units.filter(u=>u.row!==null),front=Math.max(0,...field.map(u=>botAdvanceProgress(player,u.row))),fusionBefore=botFusionSetupScore(p),enemyApproach=new Set;enemies.filter(u=>!u.faceDown).forEach(enemy=>moveTargets(enemy).forEach(cell=>enemyApproach.add(`${cell.r},${cell.c}`)));let plans=[];field.filter(u=>!u.faceDown&&botCanMoveUnit(u,p)&&!uranusBlocking(u)&&(!hasEffect(u,'archer')||canArcherMove(u))).forEach(u=>{let currentRisk=botProjectedEnemyRisk(u),currentProgress=botAdvanceProgress(player,u.row),supportGap=front-currentProgress,duckBlocker=p.archetype==='xadria'&&hasEffect(u,'duck');moveTargets(u).filter(target=>!pitAt(target.r,target.c)).forEach(target=>{let row=u.row,col=u.col,advance=botAdvanceProgress(player,target.r)-currentProgress;u.row=target.r;u.col=target.c;let attacks=botAttackChoices(),attackValue=attacks[0]?.value||0,jointAttack=attacks.find(choice=>choice.joint),jointSetup=jointAttack?jointAttack.value:0,risk=botMoveRisk(u),responseRisk=botProjectedEnemyRisk(u),nearest=[...enemies].sort((a,b)=>(Math.abs(target.r-a.row)+Math.abs(target.c-a.col))-(Math.abs(target.r-b.row)+Math.abs(target.c-b.col)))[0],distance=Math.abs(target.r-nearest.row)+Math.abs(target.c-nearest.col),ownAttack=duckBlocker?effectiveAtk(nearest,true)+1:effectiveAtk(u,false),enemyAttack=effectiveAtk(nearest,true),advantage=ownAttack-enemyAttack,repetition=botRepetitionPenalty(u.moveHistory,target),fieldControl=botFieldControlValue(advance,supportGap,botEnemySpawnDistance(player,target.r)),fusionSetup=(botFusionSetupScore(p)-fusionBefore)*5,duckBlock=duckBlocker?Math.max(0,6-distance)*11000+(enemyApproach.has(`${target.r},${target.c}`)?60000:0):0;u.row=row;u.col=col;plans.push({u,target,attackValue,jointSetup,risk,responseRisk,currentRisk,distance,advantage,repetition,fieldControl,fusionSetup,duckBlock,score:attackValue*100+jointSetup*(defensive?35:3)+botMatchupScore(ownAttack,enemyAttack,distance,risk)-responseRisk*3-repetition+fieldControl+fusionSetup+duckBlock+ownAttack/100})})});let defensiveJoint=plans.filter(plan=>defensive&&plan.jointSetup&&plan.responseRisk<=plan.currentRisk),safe=plans.filter(plan=>plan.responseRisk===0),reactive=plans.filter(plan=>plan.responseRisk<plan.currentRisk||plan.advantage>0&&plan.responseRisk<=plan.currentRisk);return(defensiveJoint.length?defensiveJoint:safe.length?safe:reactive).sort((a,b)=>b.score-a.score)[0]||null}
function botMovePawn(plan=botBestMovePlan()){if(!plan)return false;selected=plan.u;doMove(plan.u,plan.target.r,plan.target.c);return true}
function botAttackPawn(choice=botAttackChoices()[0]){if(!choice)return false;selected=choice.attacker;doAttack(choice.attacker,choice.defender);return true}
function botTakeTurn(){if(!botControls(state.current)||state.placementPhase)return;hint(`${state.players[state.current].name} está pensando…`);scheduleBot(botCombinationPhase,260)}
function botCombinationPhase(){if(!botControls(state.current))return;if(state.animating)return scheduleBot(botCombinationPhase,250);let combined=botCombinePawn();scheduleBot(combined?botCombinationPhase:botAfterCombinationPhase,combined?940:180)}
function botAfterCombinationPhase(){if(!botControls(state.current))return;if(botPrepareCastle())return scheduleBot(botAfterCombinationPhase,360);scheduleBot(()=>botEffectPhase(0),180)}
function botCombinationFollowup(next){if(!botControls(state.current))return;if(state.animating)return scheduleBot(()=>botCombinationFollowup(next),250);let combined=botCombinePawn();scheduleBot(combined?()=>botCombinationFollowup(next):next,combined?940:180)}
function botEffectPhase(played){if(!botControls(state.current))return;if(played<2&&botPlayEffect())return scheduleBot(()=>botEffectPhase(played+1),420);let deployed=botDeployPawn();scheduleBot(()=>botCombinationFollowup(botRevealPhase),deployed?760:180)}
function botRevealPhase(){if(!botControls(state.current))return;let choice=botChooseReveal();if(!choice)return scheduleBot(botAbilityPhase,180);if(choice.purpose==='move')state.players[botActor()].botMoveRevealTurn=state.turn;botSetFaceDown(choice.u,false);scheduleBot(botRevealPhase,360)}
function botAbilityPhase(){if(!botControls(state.current))return;let mounted=botUseMount();if(mounted)return scheduleBot(botAbilityPhase,520);let pushed=botUseNeptune();scheduleBot(botPreMoveAttackPhase,pushed?720:220)}
function botPreMoveAttackPhase(){if(!botControls(state.current))return;if(state.animating)return scheduleBot(botPreMoveAttackPhase,250);let current=botAttackChoices(),winning=current.find(choice=>choice.outcome==='win');if(winning){let attacked=botAttackPawn(winning);return scheduleBot(attacked?botPreMoveAttackPhase:botMovePhase,attacked?900:260)}let movePlan=botBestMovePlan(),attackFirst=current.length&&(!movePlan||movePlan.attackValue<=current[0].value);if(!attackFirst)return botMovePhase(movePlan);let attacked=botAttackPawn(current[0]);scheduleBot(attacked?botPreMoveAttackPhase:botMovePhase,attacked?900:260)}
function botMovePhase(plan=null){if(!botControls(state.current))return;let moved=botMovePawn(plan||botBestMovePlan());scheduleBot(()=>{let second=botBestMovePlan();if(moved&&second)return botMovePhase(second);botCombinationFollowup(botAttackPhase)},moved?650:320)}
function botAttackPhase(){if(!botControls(state.current))return;if(state.animating)return scheduleBot(botAttackPhase,250);let attacked=botAttackPawn();scheduleBot(attacked?botAttackPhase:botHidePhase,attacked?900:260)}
function botHidePhase(){if(!botControls(state.current))return;let u=botChooseHide();if(!u)return scheduleBot(botFinishTurn,180);let hidden=botSetFaceDown(u,true);scheduleBot(hidden?botHidePhase:botFinishTurn,hidden?360:180)}
function botFinishTurn(){if(!botControls(state.current))return;if(state.animating)return scheduleBot(botFinishTurn,300);if(checkWin())return;if(state.swordQueue.length){openSwordTransfer();return}endTurn()}
botProjectedEnemyRisk=function(defender){let opponent=botOpponent(defender.owner),enemies=state.players[opponent].units.filter(u=>u.row!==null&&!u.faceDown).sort((a,b)=>(Math.abs(a.row-defender.row)+Math.abs(a.col-defender.col))-(Math.abs(b.row-defender.row)+Math.abs(b.col-defender.col))).slice(0,10),worst=Math.max(0,...enemies.map(enemy=>botAttackResponseRisk(enemy,defender)));enemies.filter(mover=>!uranusBlocking(mover)&&(!hasEffect(mover,'archer')||canArcherMove(mover))).forEach(mover=>{let row=mover.row,col=mover.col,options=moveTargets(mover).filter(target=>!pitAt(target.r,target.c)).slice(0,8);options.forEach(target=>{mover.row=target.r;mover.col=target.c;worst=Math.max(worst,botAttackResponseRisk(mover,defender))});mover.row=row;mover.col=col});return worst};
function endTurn(){if(botMode&&botControls(state.current)&&canLocalAct())return;if(state.animating)return hint('Aguarde a animação terminar.');if(state.placementPhase)return;if(state.awaitingDraw)return openDrawChoice();if(checkWin())return;let old=state.current,next=old===1?2:1,oldPlayer=state.players[old];oldPlayer.units.slice().forEach(u=>{if(hasEquipment(u,'eyes')&&moveTargets(u).length&&u.movedTurn!==state.turn){let name=u.name;destroy(u,next,'efeito');log(`Eu Vejo os Olhos destruiu ${name}, que podia ter se movido mas terminou o turno sem se mover.`)}u.atraExtraMoves=0;u.atraExtraAttacks=0});if(checkWin())return;oldPlayer.attackLocked=false;oldPlayer.attackedThisTurn=false;oldPlayer.moveLocked=false;state.players[next].lastLosses=state.players[next].lossesThisTurn;state.players[next].lossesThisTurn=0;state.current=next;state.awaitingDraw=false;if(next===1)state.turn++;let p=state.players[next];p.drawn=state.turn===1;p.deployed=false;p.moved=false;selected=null;clearAction();render();showPass(next,'turn')}
function forfeitGame(){if(botVsBot)return hint('A partida entre bots termina automaticamente.');let loser=botMode?1:onlineMode?localPlayer:state.current;if(!loser||state.forfeitWinner||!confirm(`Duelista ${loser}, deseja realmente desistir?`))return;state.forfeitWinner=loser===1?2:1;log(`${state.players[loser].name} desistiu da partida.`);render();checkWin();if(onlineMode)sendGameState(true,true)}
function hasNormalPawnAvailable(player){let p=state.players[player];if((p.pawnDeck||[]).length)return true;return [...(p.units||[]),...(p.reserve||[]),...(p.initialUnits||[])].some(u=>!u.fusion||u.mounted)}
function checkWin(){let exhausted=state.placementPhase?[]:[1,2].filter(n=>!hasNormalPawnAvailable(n)),eliminated=exhausted.length===1?exhausted[0]:null,pointWinner=[1,2].find(n=>state.players[n].score>=(state.pointGoal||10)),reason=state.celestialWinner?'solar':state.forfeitWinner?'forfeit':pointWinner?'points':eliminated?'exhaustion':null,winner=reason==='solar'?state.celestialWinner:reason==='forfeit'?state.forfeitWinner:reason==='points'?pointWinner:reason==='exhaustion'?(eliminated===1?2:1):null;if(!winner)return false;let p=state.players[winner],dialog=$('#winner-dialog'),solar=reason==='solar';dialog.classList.toggle('solar-victory',solar);dialog.querySelector('.winner-crest').textContent=solar?'☀':'♛';$('#winner-name').textContent=`${p.name} · ${archetypes[p.archetype].name}`;$('#winner-score').textContent=solar?'Os oito astros convergiram: o SOL nasceu e encerrou o duelo.':reason==='forfeit'?`Vitória por desistência do Duelista ${winner===1?2:1}`:reason==='points'?`${p.score} pontos conquistados · meta de ${state.pointGoal||10}`:`Vitória automática: o Duelista ${eliminated} ficou sem Peões normais disponíveis.`;if(!dialog.open)dialog.showModal();return true}
document.addEventListener('pointerdown',event=>{if(!botVsBot&&(mode==='combinar'||pendingCard)&&!event.target.closest('#board')){selected=null;selectedEffect=null;clearAction();render();hint('A combinação ou carta em uso foi cancelada.')}});
$('#mobile-details-close').onclick=()=>$('.card-details').classList.add('mobile-details-hidden');
$('#draw-pawn').onclick=()=>drawPawn($('#draw-pawn'));$('#draw-effect').onclick=()=>drawEffect($('#draw-effect'));$('#choice-pawn').onclick=()=>drawPawn($('#choice-pawn'));$('#choice-effect').onclick=()=>drawEffect($('#choice-effect'));$('#skip-draw').onclick=()=>{let p=state.players[state.current];p.drawn=true;finishDrawChoice();render()};$('#flip').onclick=flipSelected;$('#ability').onclick=useAbility;$('#end-turn').onclick=endTurn;$('#pass-ready').onclick=()=>{let purpose=state.passPurpose;$('#pass').classList.add('hidden');if(purpose==='placement')beginInitialPlacement(state.placementPlayer);else beginTurn()};$('#forfeit-btn').onclick=forfeitGame;$('#rules-btn').onclick=()=>$('#rules-dialog').showModal();$('.dialog-close').onclick=()=>$('#rules-dialog').close();$('#restart-btn').onclick=()=>{if(onlineMode&&onlineRole!=='host')return sendPacket({type:'restart-request'});if(confirm('Reiniciar o duelo com os mesmos decks?')){newGame();if(onlineMode)sendGameState(true,true)}};$('#winner-restart').onclick=()=>{$('#winner-dialog').close();if(onlineMode){if(onlineRole==='host'){newGame();sendGameState(true,true)}else sendPacket({type:'restart-request'})}else $('#setup').classList.remove('hidden')};
$('.global-arena').onclick=inspectArena;
$('#setup-rules-btn').onclick=()=>$('#rules-dialog').showModal();
$('#home-brand').onclick=()=>{clearTimeout(botTimer);botTimer=null;clearTimeout(botWatchdogTimer);botWatchdogTimer=null;$('#winner-dialog')?.close();document.querySelectorAll('#turn-draw,#pass,#sword-transfer,#network-badge').forEach(element=>element.classList.add('hidden'));document.body.classList.remove('online-waiting','connection-lost');selectGameMode('local');$('#setup').classList.remove('hidden')};
$$('.deck-choice').forEach(button=>button.onclick=()=>{let row=button.closest('.choice-row'),player=+row.dataset.player;if(onlineMode&&localPlayer&&player!==localPlayer)return;selectedDecks[player]=button.dataset.deck;row.querySelectorAll('.deck-choice').forEach(b=>b.classList.toggle('selected',b===button));onlineDeckChanged(player,button.dataset.deck)});
$('#start-game').onclick=()=>{if(onlineMode)return startOnlineGame();$('#setup').classList.add('hidden');newGame()};
$('#point-goal').onchange=()=>{setPointGoal($('#point-goal').value);if(onlineMode&&onlineRole==='host')sendDeckChoice()};
newGame();
