const ROWS=8,COLS=6;
let pointGoal=10;
registerPawns({
 infantry:{name:'Infantaria do Reino de Xadria',atk:200,movement:[[-2,0],[-1,0],[0,-1],[0,1],[1,0],[2,0]],types:['LUZ','TREVAS'],glyph:'◐',art:'assets/cards/infantry.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'No ataque conjunto, dobra o ATK de um dos participantes.'},
 tower:{name:'Torre Branca de Xadria',atk:150,movement:[[-3,0],[-2,0],[-1,0],[1,0],[2,0],[3,0]],types:['LUZ','PEDRA'],glyph:'▥',art:'assets/cards/tower.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Lorc · Game-icons.net · CC BY 3.0',text:'Pode se sacrificar para negar um ataque contra aliado adjacente.'},
 jester:{name:'Bobo da Casa Branca de Xadria',atk:100,movement:[[-2,-1],[-2,1],[-1,-1],[-1,1],[0,-1],[0,1],[1,-2],[1,2],[2,-1],[2,0],[2,1]],types:['LUZ'],glyph:'✦',art:'assets/cards/jester.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'Habilidade: escolhe qualquer peão em campo e mantém o efeito copiado até o fim da partida.'},
 archer:{name:'Arqueiro da Casa Preta de Xadria',atk:250,movement:[[-3,-1],[-3,0],[-3,1],[-2,-2],[-2,2],[-1,-3],[-1,0],[-1,3],[0,-3],[0,-1],[0,1],[0,3],[1,-3],[1,0],[1,3],[2,-2],[2,2],[3,-1],[3,0],[3,1]],types:['TREVAS'],glyph:'➹',art:'assets/cards/archer.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Lorc · Game-icons.net · CC BY 3.0',text:'Só pode se mover quando um Peão adversário estiver em seu caminho e pode atacar adversários à distância dentro desse raio.'},
 duck:{name:'Ave Eterna do Reino Xadria',atk:0,movement:[[-3,0],[-2,-1],[-2,0],[-2,1],[-1,-2],[-1,-1],[-1,0],[-1,1],[-1,2],[0,-3],[0,-2],[0,-1],[0,1],[0,2],[0,3],[1,-2],[1,-1],[1,0],[1,1],[1,2],[2,-1],[2,0],[2,1],[3,0]],types:['LUZ','TREVAS','NATURAL'],glyph:'◆',art:'assets/cards/duck.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'Não é destruída por combate. Pode se mover uma vez por turno sem nunca gastar a ação de movimento.'},
 horse:{name:'Cavalo da Casa Preta de Xadria',atk:250,movement:[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]],types:['TREVAS','NATURAL'],glyph:'♞',art:'assets/cards/horse.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Lorc · Game-icons.net · CC BY 3.0',text:'Salta seguindo o alcance indicado em sua carta.'},
 rabbit:{name:'Coelho Selvagem',atk:200,movement:[[-3,0],[0,-3],[0,3],[3,0]],types:['NATURAL'],glyph:'●',art:'assets/cards/rabbit.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'Salta para uma das quatro casas indicadas no alcance.'},
 rider:{name:'Montador Selvagem',atk:150,movement:[[-1,0],[0,-1],[0,1],[1,0]],types:['NATURAL'],glyph:'⟁',art:'assets/cards/rider.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Skoll · Game-icons.net · CC BY 3.0',text:'Habilidade: monta um aliado Selvagem adjacente, somando ataque e alcance de ambos.'},
 babel:{name:'Torre Preta de Xadria: Babel',atk:400,movement:[[-3,0],[-2,0],[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1],[2,0],[3,0]],types:['TREVAS','PEDRA'],glyph:'⬟',fusion:2,materials:{kinds:['tower','infantry']},art:'assets/cards/babel.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'Inimigos dentro das casas indicadas em seu alcance de movimento têm o ATK reduzido à metade.'},
 justice:{name:'Cavaleiro da Casa Branca de Xadria: Justiça Alva',atk:350,movement:[[-2,-1],[-2,0],[-2,1],[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1],[2,-1],[2,0],[2,1]],types:['LUZ'],glyph:'✧',fusion:2,materials:{type:'LUZ'},art:'assets/cards/justice.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'Pode atacar um número de vezes igual à quantidade de peões aliados derrotados no turno anterior.'},
 serpent:{name:'Serpente Selvagem',atk:500,movement:[[-2,-1],[-2,0],[-2,1],[-1,-1],[-1,0],[-1,1],[1,0]],types:['NATURAL','LUZ'],glyph:'≈',fusion:3,materials:{type:'NATURAL'},art:'assets/cards/serpent.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Skoll · Game-icons.net · CC BY 3.0',text:'Habilidade: cria um obstáculo NATURAL adjacente uma vez por turno.'},
 hawk:{name:'Gavião Selvagem',atk:250,movement:[[-2,-2],[-2,2],[-1,-1],[-1,1],[1,0],[2,0]],types:['NATURAL'],glyph:'⌁',art:'assets/cards/hawk.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Lorc · Game-icons.net · CC BY 3.0',text:'Pode se mover duas vezes no mesmo turno.'},
 golem:{name:'Golem Selvagem',atk:400,movement:[[-1,0],[0,-2],[0,-1],[0,1],[0,2],[1,0]],types:['NATURAL','LUZ'],glyph:'▰',fusion:2,materials:{type:'NATURAL'},art:'assets/cards/golem.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'Pode pisar em obstáculos NATURAIS para destruí-los e ganhar 200 ATK permanentemente.'},
 mercury:{name:'Objeto Celeste: Mercúrio',atk:150,movement:[[-2,0],[-1,0],[1,0],[2,0]],types:['PEDRA'],glyph:'☿',celestial:true,art:'assets/planets/mercury.jpg',artCredit:'NASA/JHUAPL/Carnegie',text:'Se estiver no raio de movimento de qualquer outro peão, pode se mover uma segunda vez no turno.'},
 venus:{name:'Objeto Celeste: Vênus',atk:200,movement:[[-2,0],[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1],[2,0]],types:['PEDRA','FOGO'],glyph:'♀',celestial:true,art:'assets/planets/venus.jpg',artCredit:'NASA/JPL-Caltech',text:'Peões adversários dentro de seu raio não podem se mover para fora desse raio.'},
 earth:{name:'Objeto Celeste: Terra',atk:100,movement:[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],types:['TERRA'],glyph:'⊕',celestial:true,art:'assets/planets/earth.jpg',artCredit:'NASA',text:'Todo Objeto Celeste em contato tem seu ATK dobrado.'},
 mars:{name:'Objeto Celeste: Marte',atk:150,movement:[[0,-3],[0,-2],[0,-1],[0,1],[0,2],[0,3]],types:['PEDRA','FOGO'],glyph:'♂',celestial:true,art:'assets/planets/mars.jpg',artCredit:'NASA/JPL/USGS',text:'Ataca em seu raio horizontal e destrói o alvo com fogo mesmo quando perde o combate.'},
 jupiter:{name:'Objeto Celeste: Júpiter',atk:350,movement:[[-3,-1],[-3,1],[-2,-1],[-2,0],[-2,1],[-1,0],[1,0],[2,-1],[2,0],[2,1],[3,-1],[3,1]],types:['AR'],glyph:'♃',celestial:true,art:'assets/planets/jupiter.jpg',artCredit:'NASA/JPL-Caltech/SwRI/MSSS · Kevin M. Gill (CC BY)',text:'Ignora obstáculos da Arena; ao pisar em um obstáculo, destrói-o.'},
 saturn:{name:'Objeto Celeste: Saturno',atk:200,movement:[[-3,-1],[-3,0],[-3,1],[-2,-2],[-2,2],[-1,-3],[-1,3],[0,-3],[0,3],[1,-3],[1,3],[2,-2],[2,2],[3,-1],[3,0],[3,1]],types:['PEDRA','AR'],glyph:'♄',celestial:true,art:'assets/planets/saturn.jpg',artCredit:'NASA/JPL/Space Science Institute',text:'Quando é colocado em campo, gera 2 Cinturões de Asteroides na mão de seu dono.'},
 uranus:{name:'Objeto Celeste: Urano',atk:200,movement:[[-2,1],[-2,2],[-1,0],[-1,2],[1,-2],[1,0],[2,-2],[2,-1]],types:['ÁGUA'],glyph:'⛢',celestial:true,art:'assets/planets/uranus.jpg',artCredit:'NASA/JPL-Caltech',text:'Peões inimigos dentro de seu raio não podem se mover.'},
 neptune:{name:'Objeto Celeste: Netuno',atk:250,movement:[[-1,0],[-1,2],[0,-3],[0,-1],[0,1],[0,3],[1,-2],[1,0]],types:['ÁGUA','AR'],glyph:'♆',celestial:true,art:'assets/planets/neptune.jpg',artCredit:'NASA/JPL-Caltech',text:'Uma única vez por turno para o jogador, independentemente de quantas cópias de Netuno estejam em campo, escolhe um peão e o empurra em direção ao outro lado da Arena.'},
 pluto:{name:'Objeto Celeste: Plutão',atk:100,movement:[[-2,1],[-1,0],[0,-1],[0,1],[1,0],[2,-1]],types:['PEDRA'],glyph:'♇',celestial:true,art:'assets/planets/pluto.jpg',artCredit:'NASA/JHUAPL/SwRI',text:'Ao vencer um combate, seu dono compra um Peão.'},
 sun:{name:'Objeto Celeste: SOL',atk:10000,movement:[[-3,0],[-2,-1],[-2,0],[-2,1],[-1,-3],[-1,-2],[-1,-1],[-1,0],[-1,1],[-1,2],[-1,3],[0,-2],[0,-1],[0,1],[0,2],[1,-1],[1,0],[1,1],[2,-2],[2,-1],[2,1],[2,2],[3,-2],[3,2]],types:['PEDRA','FOGO'],glyph:'☀',celestial:true,art:'assets/planets/sun.jpg',artCredit:'NASA/GSFC/Solar Dynamics Observatory',fusion:8,materials:{kinds:['mercury','venus','earth','mars','jupiter','saturn','uranus','neptune']},text:'Ao ser criado em campo, seu dono vence imediatamente a partida.'}
});
registerEffects({
 retreat:{name:'Recuar!',type:'UTILIDADE',icon:'↩',art:'assets/cards/retreat.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'Escolha um peão; ele retorna ao local onde foi jogado.'},
 castle:{name:'Rocar Torre',type:'UTILIDADE',icon:'⇄',art:'assets/cards/castle.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Lorc · Game-icons.net · CC BY 3.0',text:'Troque um peão com “Torre” no nome por outro peão aliado.'},
 sword:{name:'Espada Maldita de Xadria',type:'EQUIPAMENTO',icon:'†',art:'assets/cards/sword.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Lorc · Game-icons.net · CC BY 3.0',text:'O equipado destrói qualquer rival, mas também cai após o combate. O dono do peão destruído escolhe qualquer outro peão que esteja no campo para receber a espada.'},
 burn:{name:'Queimar Pertences',type:'UTILIDADE',icon:'♨',art:'assets/cards/burn.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Lorc · Game-icons.net · CC BY 3.0',text:'Destrói todos os equipamentos do peão escolhido.'},
 roses:{name:'Campo das Rosas Pálidas',type:'ARENA',icon:'❀',art:'assets/cards/roses.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Lorc · Game-icons.net · CC BY 3.0',text:'Sempre que um jogador perde um peão, compra uma carta aleatória entre as pilhas de Peões e Efeitos.'},
 jungle:{name:'Selva Selvagem',type:'ARENA',icon:'♣',art:'assets/cards/jungle.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'No início de cada turno cria um obstáculo NATURAL ou, com 50% de chance, uma fruta. Quem pega a fruta ganha 100 ATK. Tudo que a Selva criou desaparece quando esta Arena é substituída.'},
 bow:{name:'Arco Selvagem',type:'EQUIPAMENTO',icon:'➶',art:'assets/cards/bow.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'O equipado pode atacar inimigos nas casas indicadas em seu próprio alcance de movimento, além do ataque adjacente normal.'},
 pit:{name:'Poço sem Fundo',type:'UTILIDADE',icon:'◉',art:'assets/cards/pit.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'Coloque um poço em qualquer casa livre da Arena. O peão que cair nele é destruído, concede seus pontos ao adversário do peão e o poço permanece.'},
 push:{name:'Empurrão',type:'UTILIDADE',icon:'»',art:'assets/cards/push.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'Escolha um peão em campo e depois quantas casas para trás ele será empurrado.'},
 asteroid:{name:'Cinturão de Asteroides',type:'EQUIPAMENTO',icon:'☄',art:'assets/cards/asteroid.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'Se o peão equipado fosse destruído em combate, destrua um Cinturão de Asteroides e negue essa destruição.'},
 project:{name:'Projetar Astros',type:'ARENA',icon:'✺',art:'assets/cards/project.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Skoll · Game-icons.net · CC BY 3.0',text:'Efeitos que exigem contato também funcionam dentro do raio de movimento do peão. Essa regra também vale para criar Peões Combinados.'},
 peace:{name:'Tratado de Paz',type:'UTILIDADE',icon:'⚑',art:'assets/cards/peace.webp',artCrop:{scale:100,x:0,y:0},artCredit:'Delapouite · Game-icons.net · CC BY 3.0',text:'Só pode ser jogado antes de atacar. Você não pode atacar neste turno e o oponente não pode atacar no próximo turno.'}
});
registerArchetype('xadria',{name:'Xadria',emblem:'◐',pawns:['infantry','tower','jester','archer','duck','horse'],fusions:['babel','justice'],effects:['retreat','castle','sword','burn','roses','pit','push','peace']});
registerArchetype('wild',{name:'Selvagem',emblem:'✿',pawns:['rabbit','rider','hawk'],fusions:['serpent','golem'],effects:['jungle','bow','retreat','burn','pit','push','peace']});
registerArchetype('celestial',{name:'Objeto Celeste',emblem:'✺',pawns:['mercury','venus','earth','mars','jupiter','saturn','uranus','neptune','pluto'],fusions:['sun'],effects:['asteroid','project','burn','pit','push','peace'],pawnComposition:['mercury','mercury','venus','venus','earth','earth','mars','mars','jupiter','jupiter','saturn','saturn','uranus','uranus','neptune','neptune','pluto','sun']});
let selectedDecks={1:'xadria',2:'wild'};
let state,selected=null,selectedEffect=null,spectatorSelected=null,spectatorEffect=null,mode=null,targets=[],attackTargets=[],pendingCard=null,pendingPushTarget=null,pendingAbilityTarget=null,castleFirst=null,fusionMaterials=[],initialPlacementResume=null,gameVersion=0,botMode=false,botVsBot=false,botPlayer=2,botTimer=null,botWatchdogTimer=null,lastArenaVisual='none',arenaAnimationTimer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function uid(){return Math.random().toString(36).slice(2,9)}
function unit(kind,owner){let d=defs[kind];return{id:uid(),kind,owner,row:null,col:null,origin:null,movedTurn:0,attackedTurn:0,equipment:[],abilityTurn:0,mounted:null,...d,types:[...(d.types||[])],baseTypes:[...(d.types||[])],pointValue:1}}
function artStyle(item){let crop=item?.artCrop;return crop?` style="--art-scale:${crop.scale}%;--art-x:${crop.x}%;--art-y:${crop.y}%"`:''}
function artVisual(item,context=''){let xadriaKinds=[...archetypes.xadria.pawns,...archetypes.xadria.fusions],xadriaCard=xadriaKinds.includes(item?.kind),dualXadria=xadriaCard&&item.types?.includes('LUZ')&&item.types.includes('TREVAS'),xadriaStyle=xadriaCard?(dualXadria?' dual-xadria-art':item.iconTone==='black'?' xadria-black-art':' xadria-white-art'):'';return item?.art?`<span class="art-crop ${context}${item.celestial?' celestial-art':''}${xadriaStyle} tone-${item.iconTone||'natural'}"><img src="${item.art}" alt="Arte de ${item.name}"${artStyle(item)}></span>`:''}
function unitVisual(u,context=''){let visual=u.art?artVisual(u,context):`<span class="glyph">${u.glyph}</span>`;return visual+(u.fruitPickup&&context==='board-art'?'<span class="fruit-pickup" aria-label="Fruta coletada">✦<i>+100</i></span>':'')}
function rawMovementOffsets(u){if(u.equipment?.includes('goldArmor'))return[[-1,0],[0,-1],[0,1],[1,0]];let base=[...(u.movement||[])],offsets=[...base];if(u.mounted)offsets.push(...(defs[u.mounted].movement||[]));if(u.kind==='earth'&&u.equipment?.includes('moon'))offsets.push(...base.flatMap(([dr,dc])=>[[dr*2,dc*2],[dr*3,dc*3]]));let seen=new Set;return offsets.filter(([dr,dc])=>{let key=`${dr},${dc}`;if(seen.has(key))return false;seen.add(key);return true})}
function movementOffsets(u){let direction=u.owner===2?-1:1;return rawMovementOffsets(u).map(([dr,dc])=>[dr*direction,dc*direction])}
function movementPreview(u){let active=new Set(rawMovementOffsets(u).map(([dr,dc])=>`${dr},${dc}`)),cells=[];for(let dr=-3;dr<=3;dr++)for(let dc=-3;dc<=3;dc++)cells.push(`<span class="${dr===0&&dc===0?'origin':active.has(`${dr},${dc}`)?'reach':''}"></span>`);return `<div class="movement-label">ALCANCE</div><div class="movement-preview" aria-label="Alcance de movimento">${cells.join('')}</div>`}
function fusionRequirementLabel(card,short=false){if(!card?.fusion)return'';if(card.materials?.requirements)return card.materials.requirements.map(req=>req.kind?(short?req.kind.toUpperCase().slice(0,5):defs[req.kind].name):req.combined?(short?'OURO COMB.':`Peão ${req.type} Combinado`):req.normal?(short?'OURO NORMAL':`Peão ${req.type} normal`):(short?req.type.slice(0,5):`Peão ${req.type}`)).join(short?'+':' + ');if(card.materials?.kinds){let names=card.materials.kinds.map(k=>short?(k==='tower'?'TORRE':k==='infantry'?'INF':defs[k].glyph):defs[k].name);return names.join(short?'+':' + ')}if(card.materials?.archetype)return `${card.fusion}+ ABISSAL`;let type=card.materials?.type||'PEÃO';return `${card.fusion}×${short&&type==='NATURAL'?'NAT':type}`}
function fusionRequirementVisual(card){if(!card?.fusion)return'';let field=state?.players?.[card.owner]?.units?.filter(u=>u.row!==null)||[],chips='',status='';if(card.materials?.kinds){chips=card.materials.kinds.map(kind=>{let found=field.some(u=>u.kind===kind);return`<span class="material-chip ${found?'ready':'missing'}"><i>${defs[kind].glyph}</i><b>${defs[kind].name.replace(' do Reino de Xadria','').replace(' de Xadria','')}</b><em>${found?'EM CAMPO':'FALTA'}</em></span>`}).join('');status=card.materials.kinds.every(kind=>field.some(u=>u.kind===kind))?'Materiais disponíveis — aproxime-os para combinar.':'Coloque os peões indicados no campo.'}else{let type=card.materials?.type,count=field.filter(u=>u.types.includes(type)).length,shown=Math.min(count,card.fusion);chips=Array.from({length:card.fusion},(_,i)=>`<span class="material-chip ${i<shown?'ready':'missing'}"><i>${type==='LUZ'?'✦':'✿'}</i><b>PEÃO ${type}</b><em>${i<shown?'EM CAMPO':'FALTA'}</em></span>`).join('');status=count>=card.fusion?'Materiais disponíveis — mantenha-os em contato.':`${shown}/${card.fusion} materiais no campo.`}return`<div class="fusion-requirements"><small>PEÕES NECESSÁRIOS</small><div>${chips}</div><p>${status}</p></div>`}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function normalizePointGoal(value){let number=Math.round(Number(value));return Number.isFinite(number)?Math.max(1,Math.min(99,number)):10}
function setPointGoal(value){pointGoal=normalizePointGoal(value);let input=$('#point-goal');if(input)input.value=pointGoal;return pointGoal}
function selectedPointGoal(){return setPointGoal($('#point-goal')?.value??pointGoal)}
function botControls(player){return botMode&&(botVsBot||player===botPlayer)}
function botActor(){return botVsBot?state.current:botPlayer}
function botOpponent(player=botActor()){return player===1?2:1}
function makePawnDeck(owner,key){let arc=archetypes[key];if(arc.pawnComposition)return shuffle([...arc.pawnComposition,...arc.pawnComposition].map(kind=>unit(kind,owner)));let fusionSlots=key==='xadria'?8:6,commonSlots=36-fusionSlots,cards=Array.from({length:commonSlots},(_,i)=>unit(arc.pawns[i%arc.pawns.length],owner));for(let i=0;i<fusionSlots;i++)cards.push(unit(arc.fusions[i%arc.fusions.length],owner));return shuffle(cards)}
function ownedFusionKinds(player){return new Set([...(player?.reserve||[]),...(player?.units||[]),...(player?.initialUnits||[])].filter(u=>u.fusion).map(u=>u.kind))}
function ownsEveryUniqueFusion(player){let unique=archetypes[player?.archetype]?.fusions||[];if(!unique.length)return false;let owned=ownedFusionKinds(player);return unique.every(kind=>owned.has(kind))}
function takePawnFromDeck(player){if(!player?.pawnDeck?.length)return null;let index=player.pawnDeck.length-1;if(ownsEveryUniqueFusion(player)){for(let i=index;i>=0;i--)if(!player.pawnDeck[i].fusion){index=i;break}}return player.pawnDeck.splice(index,1)[0]}
function drawRandomInitialPawns(player,count=3){for(let i=0;i<count;i++){let index=player.pawnDeck.findIndex(u=>!u.fusion&&!u.condition);if(index<0)break;let u=player.pawnDeck.splice(index,1)[0];u.initial=true;player.initialUnits.push(u)}}
function makeEffectDeck(key){let pool=archetypes[key].effects;return shuffle(Array.from({length:40},(_,i)=>pool[i%pool.length]))}
function newGame(){
 let version=++gameVersion;
 if($('#winner-dialog')?.open)$('#winner-dialog').close();$('#winner-dialog')?.classList.remove('solar-victory');let winnerCrest=$('#winner-dialog .winner-crest');if(winnerCrest)winnerCrest.textContent='♛';
 selected=null;selectedEffect=null;spectatorSelected=null;spectatorEffect=null;initialPlacementResume=null;
 state={turn:1,current:1,pointGoal:selectedPointGoal(),players:{},obstacles:[],pits:[],graveyard:[],log:[],animating:false,initialDeal:true,awaitingDraw:false,arena:null,arenaOwner:null,arenaDefeatedStart:0,swordQueue:[],defeatedCount:0,goldDefeatedCount:0,placementPhase:true,placementPlayer:1,passPurpose:null,forfeitWinner:null,celestialWinner:null};
 clearTimeout(botTimer);botTimer=null;clearTimeout(botWatchdogTimer);botWatchdogTimer=null;clearTimeout(arenaAnimationTimer);arenaAnimationTimer=null;lastArenaVisual='none';
 for(let p=1;p<=2;p++){let key=selectedDecks[p],player=state.players[p]={name:botControls(p)?`Bot ${p}`:`Duelista ${p}`,archetype:key,score:0,units:[],initialUnits:[],hand:[],reserve:[],arena:null,drawn:true,deployed:false,moved:false,attackedThisTurn:false,attackLocked:false,neptuneAbilityTurn:0,lastLosses:0,lossesThisTurn:0,pawnDeck:makePawnDeck(p,key),effectDeck:makeEffectDeck(key)};for(let i=0;i<3;i++)player.hand.push(player.effectDeck.pop());drawRandomInitialPawns(player)}
 log('Preparação: escolha onde posicionar os três peões iniciais.');clearAction();render();beginInitialPlacement(1);setTimeout(()=>{if(version!==gameVersion)return;state.initialDeal=false;renderHands()},1300);
}
function initialTargetsFor(player){let rows=player===1?[ROWS-2,ROWS-1]:[0,1],out=[];for(let r of rows)for(let c=0;c<COLS;c++)if(!at(r,c)&&!obstacleAt(r,c)&&!pitAt(r,c))out.push({r,c});return out}
function mausoleumEdge(owner){let field=state.players[owner]?.units?.filter(u=>u.row!==null)||[];return field.length?(owner===1?Math.min(...field.map(u=>u.row)):Math.max(...field.map(u=>u.row))):(owner===1?ROWS-2:1)}
function mausoleumAreaContains(owner,row){if(state.arena!=='mausoleum'||!owner)return false;let edge=mausoleumEdge(owner);return owner===1?row>=edge:row<=edge}
function deploymentTargetsFor(player){let rows=new Set(player===1?[ROWS-2,ROWS-1]:[0,1]);if(state.arena==='mausoleum'){let edge=mausoleumEdge(player);for(let r=player===1?edge:0;r<=(player===1?ROWS-1:edge);r++)rows.add(r)}state.players[player].units.filter(u=>u.row!==null&&hasEffect(u,'jellyWitch')).forEach(witch=>[[-1,0],[1,0],[0,-1],[0,1]].forEach(([dr,dc])=>{let r=witch.row+dr,c=witch.col+dc;if(r>=0&&r<ROWS&&c>=0&&c<COLS)rows.add(`${r},${c}`)}));let out=[];for(let entry of rows){if(typeof entry==='string'){let [r,c]=entry.split(',').map(Number);if(!at(r,c)&&!obstacleAt(r,c)&&!pitAt(r,c))out.push({r,c});continue}for(let c=0;c<COLS;c++)if(!at(entry,c)&&!obstacleAt(entry,c)&&!pitAt(entry,c))out.push({r:entry,c})}return[...new Map(out.map(pos=>[`${pos.r},${pos.c}`,pos])).values()]}
function beginInitialPlacement(player){state.current=player;state.placementPlayer=player;state.placementPhase=true;selectedEffect=null;selected=state.players[player].initialUnits[0]||null;clearAction();mode='initial-deploy';targets=initialTargetsFor(player);render();hint(botControls(player)?`${state.players[player].name} está posicionando os peões iniciais…`:`${state.players[player].name}: escolha uma casa destacada para cada peão inicial.`);if(botControls(player))scheduleBot(botPlaceInitial,500)}
function continueInitialPlacement(u,version=gameVersion){let p=state.players[state.placementPlayer];if(p.initialUnits.length){selected=p.initialUnits[0];mode='initial-deploy';targets=initialTargetsFor(state.placementPlayer);render();hint(`Posicione os ${p.initialUnits.length} peões iniciais restantes.`);setTimeout(()=>{if(version!==gameVersion)return;u.deployed=false;renderBoard()},650);return}selected=null;clearAction();render();hint(`${p.name} concluiu sua preparação.`);setTimeout(()=>{if(version!==gameVersion)return;u.deployed=false;if(state.placementPlayer===1){state.placementPlayer=2;state.current=2;render();showPass(2,'placement')}else{state.placementPhase=false;state.current=1;render();showPass(1,'start')}},620)}
function placeInitialPawn(r,c){let p=state.players[state.placementPlayer],u=selected,version=gameVersion;if(!u||!u.initial||u.owner!==state.placementPlayer)return;place(u,r,c);u.initial=false;u.deployed=true;p.initialUnits=p.initialUnits.filter(x=>x.id!==u.id);p.units.push(u);collectFruit(u,r,c);log(`${p.name} posicionou ${u.name} em ${boardCoordinate(r,c)}.`);if(hasEffect(u,'devotee')){initialPlacementResume={unit:u,version};onUnitDeployed(u);render();return hint('Devoto inicial: escolha uma casa livre para abrir o Poço antes de continuar a preparação.')}onUnitDeployed(u);continueInitialPlacement(u,version)}
function showPass(player,purpose){let p=state.players[player],a=archetypes[p.archetype];state.passPurpose=purpose;if(onlineMode){render();syncOnlineState(true);if(player===localPlayer){if(purpose==='placement')beginInitialPlacement(player);else beginTurn()}else updateOnlineLock();return}if(botMode){$('#pass').classList.add('hidden');if(purpose==='placement')beginInitialPlacement(player);else beginTurn();return}$('#pass-name').textContent=`${p.name} · ${a.name}`;$('#pass .crest').innerHTML=archetypeVisual(p.archetype);$('#pass').classList.remove('hidden')}
function beginTurn(){let p=state.players[state.current],automated=botControls(state.current);state.passPurpose=null;if(state.arena==='jungle')spawnJungleFeature();if(state.turn===1){state.awaitingDraw=false;p.drawn=true;render();hint(automated?`${p.name} está pensando…`:'Rodada 1: nenhum jogador compra cartas ou peões.')}else if(automated){botDraw();render()}else{p.drawn=false;openDrawChoice()}if(automated)scheduleBot(botTakeTurn,650)}
function place(u,r,c){if(u.row===null&&u.kind==='goldBlacksmith'&&u.goldDefeatedAtEntry==null)u.goldDefeatedAtEntry=state?.goldDefeatedCount||0;u.row=r;u.col=c;if(!u.origin)u.origin={row:r,col:c}}
function boardCoordinate(r,c){return `${String.fromCharCode(65+c)}${r+1}`}
function allUnits(){return[...state.players[1].units,...state.players[2].units]}
function at(r,c){return allUnits().find(u=>u.row===r&&u.col===c)}
function featureAt(r,c){return (state.obstacles||[]).find(o=>o.row===r&&o.col===c)}
function obstacleAt(r,c){let feature=featureAt(r,c);return feature?.type!=='FRUIT'?feature:null}
function fruitAt(r,c){let feature=featureAt(r,c);return feature?.type==='FRUIT'?feature:null}
function pitAt(r,c){return (state.pits||[]).find(p=>p.row===r&&p.col===c)}
function collectFruit(u,r,c){let fruit=fruitAt(r,c);if(!u||!fruit)return false;state.obstacles=state.obstacles.filter(x=>x!==fruit);u.bonusAtk=(u.bonusAtk||0)+100;u.fruitPickup=true;log(`${u.name} pegou uma fruta em ${boardCoordinate(r,c)} e ganhou 100 ATK.`);let version=gameVersion;setTimeout(()=>{if(version!==gameVersion)return;delete u.fruitPickup;renderBoard();if(onlineMode)syncOnlineState(true)},760);return true}
function own(u){return u&&u.owner===state.current}
function viewPlayerNumber(){return botMode?1:onlineMode&&localPlayer?localPlayer:state.current}
function perspectivePlayer(){return botMode?1:onlineMode&&localPlayer?localPlayer:state.current}
function canLocalAct(){if(state?.animating||botVsBot)return false;if(botMode)return state.swordQueue?.length?state.swordQueue[0]!==botPlayer:state.current!==botPlayer;return !onlineMode||(state.swordQueue?.length?state.swordQueue[0]===localPlayer:state.current===localPlayer)}
