function isGoldUnit(u){return !!u?.types?.includes('OURO')}
function materialMatchesRequirement(u,req){return !!u&&(!req.kind||u.kind===req.kind)&&(!req.type||u.types?.includes(req.type))&&(!req.combined||!!u.fusion)&&(!req.normal||!u.fusion)}
function goldUnitHasReducedAttack(u){if(!isGoldUnit(u)||hasEffect(u,'goldWorshipper'))return false;if((u.goldAttackReduced||0)>0)return true;return allUnits().some(b=>b.owner!==u.owner&&hasEffect(b,'babel')&&inMovementRadius(b,u))}
let lastGoldPriestActivePairs=new Set;
function goldPriestIsActive(u){return !!u?.goldPriestPulse}
function syncGoldPriestVisuals(){let priests=allUnits().filter(u=>u.row!==null&&hasEffect(u,'goldPriest')),reduced=allUnits().filter(u=>u.row!==null&&goldUnitHasReducedAttack(u)),activePairs=new Set(priests.flatMap(priest=>reduced.map(target=>`${priest.id}>${target.id}`))),activatedPriests=priests.filter(priest=>reduced.some(target=>!lastGoldPriestActivePairs.has(`${priest.id}>${target.id}`)));lastGoldPriestActivePairs=activePairs;if(!activatedPriests.length)return;let version=gameVersion;activatedPriests.forEach(priest=>{let pulse=(priest.goldPriestPulse||0)+1;priest.goldPriestPulse=pulse;setTimeout(()=>{if(version!==gameVersion||priest.goldPriestPulse!==pulse)return;delete priest.goldPriestPulse;renderBoard()},1200)})}
function goldDragonAttack(u){return allUnits().filter(v=>v.id!==u.id&&isGoldUnit(v)).reduce((sum,v)=>sum+effectiveAtk(v,false,1),0)+100}
function reduceGoldAttack(u,amount){if(!u||amount<=0||hasEffect(u,'goldWorshipper'))return 0;u.bonusAtk=(u.bonusAtk||0)-amount;if(isGoldUnit(u))u.goldAttackReduced=(u.goldAttackReduced||0)+amount;return amount}
function consumeGoldArmor(u){let index=u?.equipment?.indexOf('goldArmor');if(index<0)return false;u.equipment.splice(index,1);log(`A Armadura de Ouro de ${u.name} foi destruída e negou sua destruição.`,'effect');return true}
function equipCamouflagedVest(bearer,source){if(!bearer||!source||bearer.id===source.id)return false;if(!bearer.equipment.includes('camouflagedVest'))bearer.equipment.push('camouflagedVest');bearer.camouflageTypes=[...new Set(source.types||[])];bearer.types=[...new Set([...(bearer.baseTypes||bearer.types||[]),...bearer.camouflageTypes])];return true}
function removeCamouflagedTypes(u){if(!u)return;delete u.camouflageTypes;u.types=[...(u.baseTypes||u.types||[])]}
function resolveGoldenGoblin(victim,killer){if(!victim||!killer||!hasEffect(victim,'goldGoblin')||killer.row===null)return false;let inherited=effectiveAtk(victim,false);killer.atk=inherited;killer.bonusAtk=0;killer.goldAttackReduced=0;log(`${killer.name} derrotou ${victim.name} e teve seu ATK fixado em ${inherited}.`,'combat');return true}
function transferGoldAttack(first,second){if(!isGoldUnit(first)||!isGoldUnit(second)||first.id===second.id)return false;let firstAtk=effectiveAtk(first,false),secondAtk=effectiveAtk(second,false),donor=firstAtk<=secondAtk?first:second,receiver=donor===first?second:first,total=firstAtk+secondAtk;donor.atk=0;donor.bonusAtk=0;donor.goldAttackReduced=0;receiver.atk=total;receiver.bonusAtk=0;receiver.goldAttackReduced=0;log(`${donor.name} transferiu ${Math.min(firstAtk,secondAtk)} ATK para ${receiver.name}, que agora possui ${total} ATK.`,'effect');return true}
function gildUnit(u){if(!u)return false;u.baseTypes=[...new Set([...(u.baseTypes||u.types||[]),'OURO'])];u.types=[...new Set([...(u.types||[]),'OURO'])];u.goldConverted=true;return true}
function resolveAllOrNothing(target){if(!target)return 0;let donors=[];let drained=allUnits().filter(isGoldUnit).reduce((sum,u)=>{let amount=reduceGoldAttack(u,100);if(amount){u.goldDrainTo={row:target.row,col:target.col};donors.push(u)}return sum+amount},0);target.bonusAtk=(target.bonusAtk||0)+drained;target.goldReceiving=true;renderBoard();let version=gameVersion;setTimeout(()=>{if(version!==gameVersion)return;donors.forEach(u=>delete u.goldDrainTo);delete target.goldReceiving;renderBoard();if(onlineMode)syncOnlineState(true)},900);log(`${target.name} retirou ${drained} ATK dos Peões OURO com Tudo ou Nada.`,'effect');return drained}
