const ROWS=8,COLS=6,GOAL=10;
const defs={
 infantry:{name:'Infantaria do Reino de Xadria',atk:200,movement:[[-2,0],[-1,0],[0,-1],[0,1],[1,0],[2,0]],types:['LUZ','TREVAS'],glyph:'◐',art:'soldado.png',text:'No ataque conjunto, dobra o ATK de um dos participantes.'},
 tower:{name:'Torre Branca de Xadria',atk:150,movement:[[-3,0],[-2,0],[-1,0],[1,0],[2,0],[3,0]],types:['LUZ','PEDRA'],glyph:'▥',text:'Pode se sacrificar para negar um ataque contra aliado adjacente.'},
 jester:{name:'Bobo da Casa Branca de Xadria',atk:100,movement:[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],types:['LUZ'],glyph:'✦',text:'Habilidade: copia até o fim do turno o efeito de um peão no caminho.'},
 archer:{name:'Arqueiro da Casa Preta de Xadria',atk:250,movement:[[-3,-1],[-3,0],[-3,1],[-2,-2],[-2,2],[-1,-3],[-1,0],[-1,3],[0,-3],[0,-1],[0,1],[0,3],[1,-3],[1,0],[1,3],[2,-2],[2,2],[3,-1],[3,0],[3,1]],types:['LUZ'],glyph:'➹',text:'Só se move quando um Peão adversário estiver em seu caminho.'},
 duck:{name:'Pato Familiar do Reino Xadria',atk:0,movement:[[-3,0],[-2,-1],[-2,0],[-2,1],[-1,-2],[-1,-1],[-1,0],[-1,1],[-1,2],[0,-3],[0,-2],[0,-1],[0,1],[0,2],[0,3],[1,-2],[1,-1],[1,0],[1,1],[1,2],[2,-1],[2,0],[2,1],[3,0]],types:['LUZ','TREVAS','NATURAL'],glyph:'◆',text:'Não é destruído em combate. Pode se mover uma vez por turno sem gastar a ação de movimento.'},
 rabbit:{name:'Coelho Selvagem',atk:200,movement:[[-3,0],[0,-3],[0,3],[3,0]],types:['NATURAL'],glyph:'●',text:'Salta para uma das quatro casas indicadas no alcance.'},
 rider:{name:'Montador Selvagem',atk:150,movement:[[-1,0],[0,-1],[0,1],[1,0]],types:['NATURAL'],glyph:'⟁',text:'Habilidade: monta um aliado Selvagem adjacente, somando ataque e alcance de ambos.'},
 babel:{name:'Torre Preta de Xadria: Babel',atk:400,movement:[[-3,0],[-2,0],[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1],[2,0],[3,0]],types:['TREVAS','PEDRA'],glyph:'⬟',fusion:2,text:'Inimigos em sua linha têm o ATK reduzido à metade.'},
 justice:{name:'Cavaleiro da Casa Branca: Justiça Alva',atk:300,movement:[[-2,0],[-1,-1],[-1,0],[-1,1],[0,-2],[0,-1],[0,1],[0,2],[1,-1],[1,0],[1,1],[2,0]],types:['LUZ'],glyph:'✧',fusion:2,text:'Seu ATK cresce 100 por aliado derrotado no último turno.'},
 serpent:{name:'Serpente Selvagem',atk:500,movement:[[-2,-1],[-2,0],[-2,1],[-1,-1],[-1,0],[-1,1],[1,0]],types:['NATURAL','LUZ'],glyph:'≈',fusion:3,text:'Habilidade: cria um obstáculo NATURAL adjacente uma vez por turno.'}
};
const effects={
 retreat:{name:'Recuar!',type:'UTILIDADE',icon:'↩',text:'Escolha um peão; ele retorna ao local onde foi jogado.'},
 castle:{name:'Rocar Torre',type:'UTILIDADE',icon:'⇄',text:'Troque um peão com “Torre” no nome por outro peão aliado.'},
 sword:{name:'Espada Maldita',type:'EQUIPAMENTO',icon:'†',text:'O equipado destrói qualquer rival, mas também cai após o combate. O dono do peão destruído escolhe qualquer outro peão que esteja no campo para receber a espada.'},
 burn:{name:'Queimar Pertences',type:'UTILIDADE',icon:'♨',text:'Destrói todos os equipamentos do peão escolhido.'},
 roses:{name:'Campo das Rosas Pálidas',type:'ARENA',icon:'❀',text:'Peões LUZ ganham 100 ATK enquanto são atacados.'},
 camouflage:{name:'Camuflar-se na Selva',type:'UTILIDADE',icon:'◒',text:'Vira todos os peões aliados em campo para baixo.'},
 jungle:{name:'Selva Selvagem',type:'ARENA',icon:'♣',text:'Todos os peões ganham 100 ATK por peão derrotado depois que esta Arena entra em campo.'},
 bow:{name:'Arco Selvagem',type:'EQUIPAMENTO',icon:'➶',text:'O equipado pode atacar inimigos em linha reta sem precisar tocá-los.'}
};
const archetypes={
 xadria:{name:'Xadria',emblem:'◐',pawns:['infantry','tower','jester','archer','duck'],fusions:['babel','justice'],starters:['infantry','tower','jester'],effects:['retreat','castle','sword','burn','roses']},
 wild:{name:'Selvagem',emblem:'✿',pawns:['rabbit','rider','rabbit','rider','rabbit'],fusions:['serpent'],starters:['rabbit','rider','rabbit'],effects:['camouflage','jungle','bow','retreat','burn']}
};
let selectedDecks={1:'xadria',2:'wild'};
let state,selected=null,selectedEffect=null,mode=null,targets=[],pendingCard=null,castleFirst=null,fusionMaterials=[],gameVersion=0,botMode=false,botPlayer=2,botTimer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function uid(){return Math.random().toString(36).slice(2,9)}
function unit(kind,owner){let d=defs[kind];return{id:uid(),kind,owner,row:null,col:null,origin:null,faceDown:false,flippedTurn:0,movedTurn:0,equipment:[],abilityTurn:0,mounted:null,...d}}
function unitVisual(u,context=''){return u.art?`<span class="art-crop ${context}"><img src="${u.art}" alt="Arte de ${u.name}"></span>`:`<span class="glyph">${u.glyph}</span>`}
function rawMovementOffsets(u){let offsets=[...(u.movement||[])];if(u.mounted)offsets.push(...(defs[u.mounted].movement||[]));let seen=new Set;return offsets.filter(([dr,dc])=>{let key=`${dr},${dc}`;if(seen.has(key))return false;seen.add(key);return true})}
function movementOffsets(u){let direction=u.owner===2?-1:1;return rawMovementOffsets(u).map(([dr,dc])=>[dr*direction,dc*direction])}
function movementPreview(u){let active=new Set(rawMovementOffsets(u).map(([dr,dc])=>`${dr},${dc}`)),cells=[];for(let dr=-3;dr<=3;dr++)for(let dc=-3;dc<=3;dc++)cells.push(`<span class="${dr===0&&dc===0?'origin':active.has(`${dr},${dc}`)?'reach':''}"></span>`);return `<div class="movement-label">ALCANCE</div><div class="movement-preview" aria-label="Alcance de movimento">${cells.join('')}</div>`}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makePawnDeck(owner,key){let arc=archetypes[key],fusionSlots=key==='xadria'?4:3,commonSlots=18-fusionSlots,cards=Array.from({length:commonSlots},(_,i)=>unit(arc.pawns[i%arc.pawns.length],owner));for(let i=0;i<fusionSlots;i++)cards.push(unit(arc.fusions[i%arc.fusions.length],owner));return shuffle(cards)}
function makeEffectDeck(key){let pool=archetypes[key].effects;return shuffle(Array.from({length:20},(_,i)=>pool[i%pool.length]))}
function newGame(){
 let version=++gameVersion;
 if($('#winner-dialog')?.open)$('#winner-dialog').close();
 selected=null;selectedEffect=null;
 state={turn:1,current:1,players:{},obstacles:[],log:[],animating:false,initialDeal:true,awaitingDraw:false,arena:null,arenaOwner:null,arenaDefeatedStart:0,swordQueue:[],defeatedCount:0,placementPhase:true,placementPlayer:1,passPurpose:null,forfeitWinner:null};
 clearTimeout(botTimer);botTimer=null;
 for(let p=1;p<=2;p++){let key=selectedDecks[p],player=state.players[p]={name:botMode&&p===botPlayer?'Bot':`Duelista ${p}`,archetype:key,score:0,units:[],initialUnits:[],hand:[],reserve:[],arena:null,drawn:true,deployed:false,moved:false,lastLosses:0,lossesThisTurn:0,pawnDeck:makePawnDeck(p,key),effectDeck:makeEffectDeck(key)};for(let i=0;i<3;i++)player.hand.push(player.effectDeck.pop());archetypes[key].starters.forEach(kind=>{let index=player.pawnDeck.findIndex(u=>u.kind===kind),u=index>=0?player.pawnDeck.splice(index,1)[0]:unit(kind,p);u.initial=true;player.initialUnits.push(u)})}
 log('Preparação: escolha onde posicionar os três peões iniciais.');clearAction();render();beginInitialPlacement(1);setTimeout(()=>{if(version!==gameVersion)return;state.initialDeal=false;renderHands()},1300);
}
function initialTargetsFor(player){let rows=player===1?[ROWS-2,ROWS-1]:[0,1],out=[];for(let r of rows)for(let c=0;c<COLS;c++)if(!at(r,c)&&!obstacleAt(r,c))out.push({r,c});return out}
function beginInitialPlacement(player){state.current=player;state.placementPlayer=player;state.placementPhase=true;selectedEffect=null;selected=state.players[player].initialUnits[0]||null;clearAction();mode='initial-deploy';targets=initialTargetsFor(player);render();hint(`${state.players[player].name}: escolha uma casa destacada para cada peão inicial.`)}
function placeInitialPawn(r,c){let p=state.players[state.placementPlayer],u=selected,version=gameVersion;if(!u||!u.initial||u.owner!==state.placementPlayer)return;place(u,r,c);u.initial=false;u.deployed=true;p.initialUnits=p.initialUnits.filter(x=>x.id!==u.id);p.units.push(u);log(`${p.name} posicionou ${u.name} em ${boardCoordinate(r,c)}.`);if(p.initialUnits.length){selected=p.initialUnits[0];targets=initialTargetsFor(state.placementPlayer);render();hint(`Posicione os ${p.initialUnits.length} peões iniciais restantes.`);setTimeout(()=>{if(version!==gameVersion)return;u.deployed=false;renderBoard()},650);return}selected=null;clearAction();render();hint(`${p.name} concluiu sua preparação.`);setTimeout(()=>{if(version!==gameVersion)return;u.deployed=false;if(state.placementPlayer===1){state.placementPlayer=2;state.current=2;render();showPass(2,'placement')}else{state.placementPhase=false;state.current=1;render();showPass(1,'start')}},620)}
function showPass(player,purpose){let p=state.players[player],a=archetypes[p.archetype];state.passPurpose=purpose;if(onlineMode){render();syncOnlineState(true);if(player===localPlayer){if(purpose==='placement')beginInitialPlacement(player);else beginTurn()}else updateOnlineLock();return}if(botMode){$('#pass').classList.add('hidden');if(player===botPlayer&&purpose==='placement'){beginInitialPlacement(player);scheduleBot(botPlaceInitial,500)}else beginTurn();return}$('#pass-name').textContent=`${p.name} · ${a.name}`;$('#pass .crest').textContent=a.emblem;$('#pass').classList.remove('hidden')}
function beginTurn(){let p=state.players[state.current];state.passPurpose=null;if(state.turn===1){state.awaitingDraw=false;p.drawn=true;render();hint(botMode&&state.current===botPlayer?'O Bot está pensando…':'Rodada 1: nenhum jogador compra cartas ou peões.')}else if(botMode&&state.current===botPlayer){botDraw();render()}else{p.drawn=false;openDrawChoice()}if(botMode&&state.current===botPlayer)scheduleBot(botTakeTurn,650)}
function place(u,r,c){u.row=r;u.col=c;if(!u.origin)u.origin={row:r,col:c}}
function boardCoordinate(r,c){return `${String.fromCharCode(65+c)}${r+1}`}
function allUnits(){return[...state.players[1].units,...state.players[2].units]}
function at(r,c){return allUnits().find(u=>u.row===r&&u.col===c)}
function obstacleAt(r,c){return state.obstacles.find(o=>o.row===r&&o.col===c)}
function own(u){return u&&u.owner===state.current}
function viewPlayerNumber(){return botMode?1:onlineMode&&localPlayer?localPlayer:state.current}
function perspectivePlayer(){return botMode?1:onlineMode&&localPlayer?localPlayer:state.current}
function canLocalAct(){if(state?.animating)return false;if(botMode)return state.swordQueue?.length?state.swordQueue[0]!==botPlayer:state.current!==botPlayer;return !onlineMode||(state.swordQueue?.length?state.swordQueue[0]===localPlayer:state.current===localPlayer)}
function adjacent(a,b){return Math.abs(a.row-b.row)+Math.abs(a.col-b.col)===1}
function log(msg){state.log.unshift({turn:state.turn,msg});state.log=state.log.slice(0,40)}
function hint(t){$('#hint').textContent=t}
function clearAction(){mode=null;targets=[];pendingCard=null;castleFirst=null;fusionMaterials=[];$$('.action').forEach(b=>b.classList.remove('active'))}
function select(u){clearAction();selectedEffect=null;selected=u;render();hint(u?`${u.name} selecionado.`:'Seleção removida.')}
function startMode(m,valid,msg){if(!valid){hint(msg);return}mode=m;targets=[];$$('.action').forEach(b=>b.classList.remove('active'));$('#'+m)?.classList.add('active');hint(msg);renderBoard()}
function render(){renderHeader();renderBoard();renderHands();renderCard();renderLog();if(onlineMode)updateOnlineLock()}
function renderHeader(){
 let active=state.players[state.current],view=state.players[viewPlayerNumber()],arc=archetypes[active.archetype],board=$('#board'),locked=state.placementPhase,busy=state.animating,waiting=!canLocalAct();
 let perspective=perspectivePlayer(),layout=$('.game-layout'),handZone=$('.hand-zone');$('main').insertBefore($(`#p${perspective===1?2:1}-strip`),layout);$('main').insertBefore($(`#p${perspective}-strip`),handZone);
 $('#turn-count').textContent=locked?'PREPARAÇÃO':`TURNO ${state.turn}`;$('#turn-name').textContent=`${active.name.toUpperCase()} · ${arc.name.toUpperCase()}`;$('#phase-label').textContent=busy?'Resolvendo animação':waiting?'Aguardando adversário':locked?'Posicione os peões iniciais':state.awaitingDraw?'Escolha uma pilha':mode?`Ação: ${mode}`:'Escolha sua ação';document.body.dataset.deck=view.archetype;board.dataset.p1=state.players[1].archetype;board.dataset.p2=state.players[2].archetype;
 for(let n=1;n<=2;n++){let x=state.players[n],a=archetypes[x.archetype],strip=$(`#p${n}-strip`);$(`#p${n}-score`).textContent=x.score;$(`#p${n}-field`).textContent=x.units.filter(u=>u.row!==null).length;$(`#p${n}-hand-count`).textContent=onlineMode&&n!==localPlayer||botMode&&n===botPlayer?'?':x.hand.length;$(`#p${n}-name`).textContent=a.name;$(`#p${n}-deck`).textContent=`DECK ${a.name.toUpperCase()}`;$(`#p${n}-emblem`).textContent=a.emblem;strip.querySelector('.player-id small').textContent=botMode?(n===botPlayer?'BOT · J2':'VOCÊ · J1'):onlineMode?(n===localPlayer?`VOCÊ · J${n}`:`RIVAL · J${n}`):`DUELISTA ${n}`;strip.dataset.deck=x.archetype;strip.classList.toggle('current',n===state.current);strip.classList.toggle('opponent',n!==state.current)}
 $('#reserve-count').textContent=view.reserve.length+view.initialUnits.length;$('#pawn-deck-count').textContent=view.pawnDeck.length;$('#effect-deck-count').textContent=view.effectDeck.length;$('#arena-global').textContent=state.arena?effects[state.arena].name:'SLOT VAZIO';$('#arena-owner').textContent=state.arenaOwner?`ATIVADA PELO DUELISTA ${state.arenaOwner}`:'';$('#draw-pawn').disabled=waiting||locked||busy||view.drawn||!view.pawnDeck.length;$('#draw-effect').disabled=waiting||locked||busy||view.drawn||!view.effectDeck.length;['flip','attack','ability','end-turn'].forEach(id=>$('#'+id).disabled=waiting||locked||busy)
}
function renderBoard(){let board=$('#board'),perspective=perspectivePlayer(),rows=[...Array(ROWS).keys()],cols=[...Array(COLS).keys()];if(perspective===2){rows.reverse();cols.reverse()}board.dataset.view=perspective;board.classList.toggle('combat-active',!!state.animating&&allUnits().some(u=>u.combatRole));board.classList.toggle('combine-active',!!state.animating&&allUnits().some(u=>u.combining));board.innerHTML='';for(let r of rows)for(let c of cols){let cell=document.createElement('div'),file=String.fromCharCode(65+c),coordinate=`${file}${r+1}`;cell.className=`cell ${(r+c)%2?'dark':'light'}${r>=ROWS-2?' zone1':r<2?' zone2':''}`;cell.dataset.r=r;cell.dataset.c=c;cell.dataset.coordinate=coordinate;cell.setAttribute('aria-label',`Casa ${coordinate}`);let edgeLabels=[];if(r===rows[0])edgeLabels.push(['coord-file coord-top',file]);if(r===rows[rows.length-1])edgeLabels.push(['coord-file coord-bottom',file]);if(c===cols[0])edgeLabels.push(['coord-rank coord-left',r+1]);if(c===cols[cols.length-1])edgeLabels.push(['coord-rank coord-right',r+1]);edgeLabels.forEach(([className,text])=>{let label=document.createElement('span');label.className=`coord ${className}`;label.textContent=text;cell.append(label)});let u=at(r,c),o=obstacleAt(r,c);if(isValidCell(r,c))cell.classList.add(mode==='attack'?'target':'valid');if(o){let e=document.createElement('span');e.className='obstacle';e.textContent='✿';e.title='Obstáculo NATURAL';cell.append(e)}if(u){let pc=document.createElement('div');pc.className=`piece p${u.owner} deck-${state.players[u.owner].archetype}${u.faceDown?' facedown':''}${u.fusion?' fusion':''}${u.mounted?' mounted':''}${selected?.id===u.id?' selected':''}${fusionMaterials.some(x=>x.id===u.id)?' fusion-material':''}${u.combatRole?` combat-${u.combatRole}`:''}${u.combining?' combining-material':''}${u.combinedEntry?' combined-entry':''}${u.moving?' moving-piece':''}${u.intro?' intro-piece':''}${u.deployed?' deploy-piece':''}`;pc.style.setProperty('--delay',`${u.enterDelay||0}ms`);if(u.combatRole==='attacker'){let combatDirection=perspective===2?-1:1;pc.style.setProperty('--combat-x',`${u.combatDx*72*combatDirection}%`);pc.style.setProperty('--combat-y',`${u.combatDy*72*combatDirection}%`)}if(u.combining){pc.style.setProperty('--combine-x',`${u.combineDx*105}%`);pc.style.setProperty('--combine-y',`${u.combineDy*105}%`)}if(u.moving){let viewDirection=perspective===2?-1:1;pc.style.setProperty('--move-x',`${u.moveDx*100*viewDirection}%`);pc.style.setProperty('--move-y',`${u.moveDy*100*viewDirection}%`)}pc.innerHTML=`${unitVisual(u,'board-art')}<span class="atk">${effectiveAtk(u,false)}</span>${u.mounted?'<span class="mount-mark">⟁</span>':''}`;pc.title=u.faceDown?'Peão virado para baixo':u.name;cell.append(pc)}cell.onclick=()=>cellClick(r,c);board.append(cell)}}
function renderHands(){let p=state.players[viewPlayerNumber()],pawnCards=[...p.initialUnits,...p.reserve];$('#effect-hand').innerHTML=p.hand.map((k,i)=>`<article class="effect-card ${state.initialDeal?'initial-card':''} ${selectedEffect&&!selectedEffect.arena&&selectedEffect.index===i?'selected':''}" data-i="${i}" style="--i:${i}" title="Clique para ver o efeito"><span class="effect-symbol">${effects[k].icon}</span><h4>${effects[k].name}</h4><span class="type">${effects[k].type}</span></article>`).join('')||'<div class="empty-pile">VAZIA</div>';$$('.effect-card').forEach(e=>e.onclick=()=>inspectEffect(+e.dataset.i));$('#pawn-hand').innerHTML=pawnCards.map(u=>`<button class="reserve-piece ${u.art?'has-art':''} ${u.initial?'initial-pawn-card':''} ${u.fusion?'fusion-card':''} ${selected?.id===u.id?'selected':''}" data-id="${u.id}" title="${u.name}${u.fusion?' · PEÃO COMBINADO':''}">${unitVisual(u,'hand-art')}<b>${u.initial?'INICIAL':u.fusion?`COMBINADO ${u.fusion}`:u.atk}</b></button>`).join('')||'<div class="empty-pile">VAZIA</div>';$$('.reserve-piece').forEach(e=>e.onclick=()=>selectPawnFromHand(pawnCards.find(u=>u.id===e.dataset.id)))}
function inspectEffect(i){let k=state.players[viewPlayerNumber()].hand[i];if(!k)return;selected=null;clearAction();selectedEffect={key:k,index:i,arena:false};render();hint(canLocalAct()&&!state.placementPhase?'Confira o efeito e use o botão Jogar carta.':'Carta inspecionada — você pode ler seu efeito enquanto aguarda.')}
function inspectArena(){if(!state.arena)return hint('O Slot de Arena está vazio.');selected=null;clearAction();selectedEffect={key:state.arena,index:null,arena:true};render();hint('Efeito global da Arena ativa.')}
function selectPawnFromHand(u){if(!u)return;if(state.animating)return hint('Aguarde a animação terminar.');select(u);if(!canLocalAct())return hint('Carta inspecionada — você pode ler seu efeito enquanto aguarda.');if(u.initial){if(!state.placementPhase||u.owner!==state.placementPlayer)return;mode='initial-deploy';targets=initialTargetsFor(state.placementPlayer);renderBoard();return hint('Escolha uma casa destacada para este peão inicial.')}if(u.fusion)return beginFusion(u);beginDeploy()}
function renderCard(){
 let el=$('#unit-card'),title=$('#detail-title');title.textContent='DETALHES DA CARTA';
 if(selectedEffect){let e=effects[selectedEffect.key],canPlay=canLocalAct()&&!state.placementPhase,arenaStatus=selectedEffect.arena?`<p class="arena-status">ATIVA NO CAMPO · EFEITO PARA AMBOS</p>`:'';el.className='unit-card effect-detail';el.innerHTML=`<div class="card-art effect-art"><span>${e.icon}</span></div><h3>${e.name}</h3><div class="badges"><span class="badge">${e.type}</span></div><p class="full-effect">${e.text}</p>${arenaStatus}${selectedEffect.arena?'':`<button id="play-selected-effect" class="primary play-card-btn" ${canPlay?'':'disabled'}>${canPlay?'JOGAR CARTA':'SOMENTE NO SEU TURNO'}</button>`}`;if(!selectedEffect.arena)$('#play-selected-effect').onclick=()=>playCard(selectedEffect.index);return}
 if(!selected){el.className='unit-card empty';el.innerHTML='<div class="card-art"><span>⬢</span></div><h3>Selecione uma carta</h3><p>Peões, Efeitos e a Arena aparecem aqui.</p>';return}
 let art=selected.art?`<span class="art-crop detail-art"><img src="${selected.art}" alt="Arte de ${selected.name}"></span>`:`<span>${selected.glyph}</span>`,mountInfo=selected.mounted?`<div class="mount-status"><span>⟁</span><div><b>MONTADOR ACOPLADO</b><small>+${defs.rider.atk} ATK · ao perder, somente o Montador é destruído</small></div></div>`:'',riderButton=selected.kind==='rider'&&canLocalAct()&&own(selected)&&selected.row!==null&&!selected.mounted?'<button id="mount-now" class="primary mount-now">⟁ MONTAR ALIADO</button>':'';
 el.className=`unit-card${selected.mounted?' mounted-card':''}`;el.innerHTML=`<div class="card-art">${art}</div><h3>${selected.name}</h3><div class="badges">${selected.mounted?'<span class="badge mounted-badge">MONTADO</span>':''}${selected.fusion?`<span class="badge fusion-badge">PEÃO COMBINADO · ${selected.fusion} MATERIAIS</span>`:''}${selected.types.map(t=>`<span class="badge">${t}</span>`).join('')}</div><div class="statline"><span>ATK ${effectiveAtk(selected,false)}</span><span>${rawMovementOffsets(selected).length} CASAS</span></div>${movementPreview(selected)}${mountInfo}<p>${selected.text}</p>${riderButton}${selected.equipment.length?`<p>† ${selected.equipment.map(e=>effects[e].name).join(', ')}</p>`:''}`;if(riderButton)$('#mount-now').onclick=useAbility
}
function renderLog(){$('#log').innerHTML=state.log.map(x=>`<div class="log-entry"><b>T${x.turn}</b> ${x.msg}</div>`).join('')}
function isValidCell(r,c){return['initial-deploy','move','deploy','attack','serpent','copy','mount','combinar'].includes(mode)&&targets.some(t=>t.r===r&&t.c===c)}
function cellClick(r,c){if(state.animating)return hint('Aguarde a animação terminar.');let u=at(r,c);if(!canLocalAct()){if(u){select(u);return hint('Peão inspecionado — você pode ler seu efeito enquanto aguarda.')}return hint('Aguarde a jogada do adversário.')}if(state.placementPhase){if(mode==='initial-deploy'&&isValidCell(r,c))placeInitialPawn(r,c);else hint('Durante a preparação, escolha uma casa destacada para o peão inicial.');return}if(mode==='combinar'){if(u&&fusionMaterials.some(x=>x.id===u.id))toggleFusionMaterial(u);else if(isValidCell(r,c))toggleFusionMaterial(u);else hint('Escolha somente um material destacado que esteja tocando os demais.');return}if(pendingCard){cardTarget(u,r,c);return}if(mode&&isValidCell(r,c)){if(mode==='move')doMove(selected,r,c);else if(mode==='deploy')doDeploy(selected,r,c);else if(mode==='attack')doAttack(selected,u);else if(mode==='serpent')createObstacle(selected,r,c);else if(mode==='copy')copyEffect(selected,u);else if(mode==='mount')mountRider(selected,u);return}if(u){select(u);if(own(u))beginMove()}else{selected=null;selectedEffect=null;clearAction();render();hint('Casa vazia.')}}
function hasEffect(u,kind){return u.kind===kind||u.copiedKind===kind}
function moveTargets(u){let out=[];for(let [dr,dc] of movementOffsets(u)){let r=u.row+dr,c=u.col+dc;if(r<0||r>=ROWS||c<0||c>=COLS||at(r,c)||obstacleAt(r,c))continue;out.push({r,c})}return out}
function canArcherMove(u){return allUnits().some(v=>v.owner!==u.owner&&(v.row===u.row||v.col===u.col))}
function beginMove(){let p=state.players[state.current];if(!own(selected)||selected.row===null)return hint('Selecione um peão seu em campo.');if(selected.faceDown)return hint('Peões virados para baixo não podem se mover. Vire este peão para cima primeiro.');let freeMove=hasEffect(selected,'duck');if(freeMove&&selected.movedTurn===state.turn)return hint('O movimento gratuito deste peão já foi usado neste turno.');if(p.moved&&!freeMove)return hint('A ação de movimento deste turno já foi usada.');if(hasEffect(selected,'archer')&&!canArcherMove(selected))return hint('O Arqueiro só se move com um adversário em sua linha.');startMode('move',true,'Escolha uma casa destacada.');targets=moveTargets(selected);renderBoard()}
function doMove(u,r,c){if(!own(u)||u.row===null){clearAction();render();return hint('Você só pode mover seus próprios peões.')}if(u.faceDown){clearAction();render();return hint('Peões virados para baixo não podem se mover.')}let fromRow=u.row,fromCol=u.col,from=boardCoordinate(fromRow,fromCol),freeMove=hasEffect(u,'duck'),version=gameVersion;state.animating=true;u.moving=true;u.moveDx=fromCol-c;u.moveDy=fromRow-r;place(u,r,c);if(freeMove)u.movedTurn=state.turn;else state.players[state.current].moved=true;log(`${u.name} moveu de ${from} para ${boardCoordinate(r,c)}${freeMove?' sem gastar a ação de movimento':''}.`);clearAction();render();hint(`${u.name} em movimento…`);if(onlineMode)sendPacket({type:'visual',kind:'move',unit:u.id,from:{row:fromRow,col:fromCol},to:{row:r,col:c}});setTimeout(()=>{if(version!==gameVersion)return;clearAnimationMarks([u]);state.animating=false;render();if(onlineMode)syncOnlineState(true)},480)}
function beginDeploy(){let p=state.players[state.current];if(p.deployed)return hint('Você já colocou um peão neste turno.');if(!selected||selected.row!==null||!own(selected))return hint('Selecione um peão da mão de Peões.');if(selected.fusion)return hint('Peões Combinados só entram em campo ao combinar os materiais exigidos em contato.');if(p.units.filter(u=>u.row!==null).length>=5)return hint('O limite de 5 peões em campo foi atingido.');startMode('deploy',true,'Escolha uma casa livre no seu polo.');let rows=state.current===1?[ROWS-2,ROWS-1]:[0,1];targets=[];for(let r of rows)for(let c=0;c<COLS;c++)if(!at(r,c)&&!obstacleAt(r,c))targets.push({r,c});renderBoard()}
function doDeploy(u,r,c){if(!own(u)||u.row!==null||u.fusion){clearAction();render();return hint('Esse peão não pode ser colocado dessa forma.')}let p=state.players[state.current];p.reserve=p.reserve.filter(x=>x.id!==u.id);place(u,r,c);u.deployed=true;p.units.push(u);p.deployed=true;log(`${u.name} entrou em campo em ${boardCoordinate(r,c)}.`);clearAction();render();setTimeout(()=>{u.deployed=false;renderBoard()},650)}
function flipSelected(){if(!own(selected)||selected.row===null)return hint('Selecione um peão seu em campo.');if(selected.flippedTurn===state.turn)return hint('Este peão já foi virado neste turno.');selected.faceDown=!selected.faceDown;selected.flippedTurn=state.turn;log(`${selected.name} foi virado ${selected.faceDown?'para baixo':'para cima'}.`);clearAction();render()}
function hasEquipment(u,key){return u.equipment.includes(key)}
function clearLine(a,b){if(a.row!==b.row&&a.col!==b.col)return false;let dr=Math.sign(b.row-a.row),dc=Math.sign(b.col-a.col),r=a.row+dr,c=a.col+dc;while(r!==b.row||c!==b.col){if(at(r,c)||obstacleAt(r,c))return false;r+=dr;c+=dc}return true}
function canAttackTarget(attacker,target){return adjacent(attacker,target)||hasEquipment(attacker,'bow')&&clearLine(attacker,target)}
function beginAttack(){if(!own(selected)||selected.row===null)return hint('Selecione o atacante.');let ranged=hasEquipment(selected,'bow');startMode('attack',true,ranged?'Escolha um inimigo adjacente ou em linha reta.':'Escolha um inimigo adjacente.');targets=allUnits().filter(u=>u.owner!==state.current&&canAttackTarget(selected,u)).map(u=>({r:u.row,c:u.col}));if(!targets.length){clearAction();hint(ranged?'Nenhum adversário ao alcance do Arco Selvagem.':'Nenhum adversário adjacente.')}renderBoard()}
function effectiveAtk(u,defending){let atk=u.atk;if(hasEffect(u,'justice'))atk+=state.players[u.owner].lastLosses*100;let babel=allUnits().find(b=>b.owner!==u.owner&&hasEffect(b,'babel')&&(b.row===u.row||b.col===u.col));if(babel)atk=Math.floor(atk/2);if(defending&&u.types.includes('LUZ')&&state.arena==='roses')atk+=100;if(state.arena==='jungle')atk+=Math.max(0,(state.defeatedCount||0)-(state.arenaDefeatedStart||0))*100;if(u.mounted)atk+=defs[u.mounted].atk;return atk}
function destroy(u,scorer,reason='combate'){let p=state.players[u.owner];if(reason==='combate'&&u.mounted){u.mounted=null;p.lossesThisTurn++;state.defeatedCount=(state.defeatedCount||0)+1;if(scorer){state.players[scorer].score++;log(`${state.players[scorer].name} recebeu 1 ponto.`)}log(`O Montador de ${u.name} foi destruído, mas a montaria permaneceu.`);return false}if(hasEffect(u,'duck')&&reason==='combate'){log(`${u.name} não pode ser destruído por combate.`);return false}p.units=p.units.filter(x=>x.id!==u.id);p.lossesThisTurn++;state.defeatedCount=(state.defeatedCount||0)+1;let pts=u.fusion||1;if(scorer){state.players[scorer].score+=pts;log(`${state.players[scorer].name} recebeu ${pts} ponto${pts>1?'s':''}.`)}if(selected?.id===u.id)selected=null;return true}
function clearAnimationMarks(units){units.filter(Boolean).forEach(u=>{delete u.combatRole;delete u.combatDx;delete u.combatDy;delete u.combining;delete u.combineDx;delete u.combineDy;delete u.moving;delete u.moveDx;delete u.moveDy})}
function finishAnimatedAction(){state.animating=false;clearAction();render();checkWin();if(onlineMode)syncOnlineState();if(state.swordQueue.length)setTimeout(openSwordTransfer,180)}
function revealDefender(defender){let version=gameVersion;state.animating=true;defender.combatRole='defender';clearAction();render();hint(`${defender.name} está sendo revelado…`);setTimeout(()=>{if(version!==gameVersion)return;clearAnimationMarks([defender]);defender.faceDown=false;log(`${defender.name} foi revelado; o combate foi cancelado.`);finishAnimatedAction()},620)}
function resolveCombat(attacker,defender,allies,atk,defAtk,tower,version){if(version!==gameVersion)return;clearAnimationMarks([...allies,defender,tower]);let cursedBearers=[...allies,defender].flatMap(u=>u.equipment.filter(e=>e==='sword').map(()=>u));if(atk>defAtk&&tower){destroy(tower,null,'sacrifício');log('Torre Branca se sacrificou e negou o ataque.')}else if(cursedBearers.length){let victims=new Map([[defender.id,{unit:defender,scorer:attacker.owner}]]);cursedBearers.forEach(bearer=>{victims.set(bearer.id,{unit:bearer,scorer:bearer.owner===attacker.owner?defender.owner:attacker.owner});if(bearer.id===defender.id)victims.set(attacker.id,{unit:attacker,scorer:defender.owner})});victims.forEach(({unit,scorer})=>destroy(unit,scorer,'maldição'));log(`A Espada Maldita destruiu ${[...victims.values()].map(v=>v.unit.name).join(' e ')}.`);cursedBearers.forEach(bearer=>queueSwordTransfer(bearer.owner))}else if(atk>defAtk){destroy(defender,attacker.owner);log(`${attacker.name} venceu (${atk} × ${defAtk}).`)}else if(atk<defAtk){destroy(attacker,defender.owner);log(`${defender.name} resistiu e venceu (${defAtk} × ${atk}).`)}else{allies.forEach(u=>destroy(u,defender.owner));destroy(defender,attacker.owner);log(`Empate em ${atk}: todos os ${allies.length} atacantes participantes e o defensor foram atingidos.`)}finishAnimatedAction()}
function doAttack(attacker,defender){
 if(state.animating)return hint('Aguarde a animação terminar.');
 if(!own(attacker)||!defender||defender.owner===state.current||!canAttackTarget(attacker,defender)){clearAction();render();return hint('Combate inválido. Selecione um adversário ao alcance.')}
 if(defender.faceDown)return revealDefender(defender);
 let allies=[attacker,...state.players[attacker.owner].units.filter(u=>u.id!==attacker.id&&u.row!==null&&adjacent(u,defender))],atk=allies.reduce((sum,u)=>sum+effectiveAtk(u,false),0),infantry=allies.find(u=>hasEffect(u,'infantry'));
 if(infantry){let best=Math.max(...allies.map(u=>effectiveAtk(u,false)));atk+=best;log('A Infantaria dobrou o ataque de um participante.')}
 let defAtk=effectiveAtk(defender,true),tower=state.players[defender.owner].units.find(u=>hasEffect(u,'tower')&&u.id!==defender.id&&adjacent(u,defender)),version=gameVersion;
 state.animating=true;allies.forEach(u=>{u.combatRole='attacker';u.combatDx=defender.col-u.col;u.combatDy=defender.row-u.row});defender.combatRole='defender';if(atk>defAtk&&tower)tower.combatRole='sacrifice';clearAction();render();let combatLabel=`${allies.length>1?'Ataque conjunto':'Combate'}: ${atk} × ${defAtk}`;hint(combatLabel);if(onlineMode)sendPacket({type:'visual',kind:'combat',attackers:allies.map(u=>u.id),defender:defender.id,tower:atk>defAtk&&tower?tower.id:null,label:combatLabel});setTimeout(()=>resolveCombat(attacker,defender,allies,atk,defAtk,tower,version),760)
}
function queueSwordTransfer(owner){state.swordQueue.push(owner);if(!state.animating)openSwordTransfer()}
function openSwordTransfer(){if(!state.swordQueue.length||onlineMode&&state.swordQueue[0]!==localPlayer||!$('#sword-transfer').classList.contains('hidden'))return;let owner=state.swordQueue[0],p=state.players[owner],choices=allUnits().filter(u=>u.row!==null);if(!choices.length){log('A Espada Maldita aguarda outro peão em campo.');renderLog();return}if(botMode&&owner===botPlayer){let target=choices.sort((a,b)=>effectiveAtk(b,false)-effectiveAtk(a,false))[0];return scheduleBot(()=>completeSwordTransfer(owner,target.id),350)}$('#sword-owner-name').textContent=`${p.name}: escolha qualquer peão em campo`;$('#sword-options').innerHTML=choices.map(u=>`<button class="sword-option" data-id="${u.id}">${unitVisual(u,'sword-art')}<b>${u.name}</b><small>${u.owner===owner?'ALIADO':'ADVERSÁRIO'} · ATK ${u.atk}</small></button>`).join('');$$('.sword-option').forEach(button=>button.onclick=()=>completeSwordTransfer(owner,button.dataset.id));$('#sword-transfer').classList.remove('hidden')}
function completeSwordTransfer(owner,id){if(state.swordQueue[0]!==owner)return;let p=state.players[owner],target=allUnits().find(u=>u.id===id&&u.row!==null);if(!target)return hint('A Espada Maldita só pode passar para um peão que esteja no campo.');target.equipment.push('sword');state.swordQueue.shift();$('#sword-transfer').classList.add('hidden');log(`${p.name} passou a Espada Maldita para ${target.name}.`);render();if(onlineMode)syncOnlineState();if(state.swordQueue.length)setTimeout(openSwordTransfer,180);else if(botMode&&state.current===botPlayer)scheduleBot(botFinishTurn,260)}
function animateDraw(source,target,kind){if(!source||!target)return;let a=source.getBoundingClientRect(),b=target.getBoundingClientRect(),ghost=document.createElement('div');ghost.className=`flying-card ${kind}`;ghost.textContent=kind==='pawn'?'⬢':'✦';Object.assign(ghost.style,{left:`${a.left+a.width/2-25}px`,top:`${a.top+a.height/2-34}px`});document.body.append(ghost);source.classList.add('drawing');let animation=ghost.animate([{transform:'translate(0,0) rotateY(0) scale(.8)',opacity:.4},{transform:`translate(${b.left+b.width/2-a.left-a.width/2}px,${b.top+b.height/2-a.top-a.height/2}px) rotateY(540deg) scale(1)`,opacity:1}],{duration:620,easing:'cubic-bezier(.2,.8,.2,1)'});animation.onfinish=()=>{ghost.remove();source.classList.remove('drawing');target.animate([{transform:'scale(.8)'},{transform:'scale(1.12)'},{transform:'scale(1)'}],{duration:280})}}
function openDrawChoice(){if(onlineMode&&state.current!==localPlayer)return;let p=state.players[state.current],a=archetypes[p.archetype];state.awaitingDraw=true;$('#draw-choice-name').textContent=`${p.name} · ${a.name}`;$('#choice-pawn-count').textContent=p.pawnDeck.length;$('#choice-effect-count').textContent=p.effectDeck.length;$('#choice-pawn').disabled=!p.pawnDeck.length;$('#choice-effect').disabled=!p.effectDeck.length;$('#skip-draw').classList.toggle('hidden',!!(p.pawnDeck.length||p.effectDeck.length));$('#turn-draw').classList.remove('hidden');renderHeader()}
function finishDrawChoice(){state.awaitingDraw=false;$('#turn-draw').classList.add('hidden')}
function drawPawn(source=$('#draw-pawn')){let p=state.players[state.current];if(p.drawn||!p.pawnDeck.length)return;p.reserve.push(p.pawnDeck.pop());p.drawn=true;log(`${p.name} escolheu a pilha de Peões.`);render();animateDraw(source,$('#pawn-hand .reserve-piece:last-child'),'pawn');finishDrawChoice();renderHeader();if(state.swordQueue[0]===state.current)setTimeout(openSwordTransfer,180)}
function drawEffect(source=$('#draw-effect')){let p=state.players[state.current];if(p.drawn||!p.effectDeck.length)return;p.hand.push(p.effectDeck.pop());p.drawn=true;log(`${p.name} escolheu a pilha de Efeitos.`);render();animateDraw(source,$('#effect-hand .effect-card:last-child'),'effect');finishDrawChoice();renderHeader()}
function playCard(i){if(!canLocalAct())return hint('Aguarde seu turno.');if(state.placementPhase)return hint('Termine de posicionar os peões iniciais primeiro.');let p=state.players[state.current],k=p.hand[i];if(!k)return;selectedEffect=null;pendingCard={key:k,index:i};selected=null;clearAction();pendingCard={key:k,index:i};if(effects[k].type==='ARENA'){if(state.arena===k){pendingCard=null;hint(`${effects[k].name} já está ativa — a carta permaneceu na sua mão.`);log(`A Arena repetida de ${p.name} não foi gasta.`);render();return}state.arena=k;state.arenaOwner=state.current;state.arenaDefeatedStart=state.defeatedCount||0;p.hand.splice(i,1);log(`${p.name} substituiu a Arena por ${effects[k].name}.`);pendingCard=null;render();return}if(k==='camouflage'){p.units.filter(u=>u.row!==null).forEach(u=>u.faceDown=true);p.hand.splice(i,1);pendingCard=null;log(`${p.name} camuflou todos os seus peões na selva.`);render();return}hint(cardPrompt(k));render()}
function cardPrompt(k){return{retreat:'Escolha qualquer peão para recuar.',castle:'Escolha uma Torre sua; depois, outro aliado.',sword:'Escolha um peão para equipar.',bow:'Escolha um peão para equipar com o Arco Selvagem.',burn:'Escolha um peão para queimar seus equipamentos.'}[k]}
function cardTarget(u){if(!u)return hint('Essa carta exige um peão como alvo.');let p=state.players[state.current],{key,index}=pendingCard;if(key==='retreat'){if(u.faceDown)return hint('Peões virados para baixo não podem ser movidos por Recuar.');let row=Number(u.origin?.row),col=Number(u.origin?.col);if(!Number.isInteger(row)||!Number.isInteger(col)||row<0||row>=ROWS||col<0||col>=COLS)return hint('A origem deste peão não é válida.');let occupant=at(row,col);if(occupant&&occupant.id!==u.id)return hint('A casa original está ocupada.');u.row=row;u.col=col;selected=u;log(`${u.name} recuou exatamente para ${boardCoordinate(row,col)}.`)}else if(key==='sword'||key==='bow'){u.equipment.push(key);log(`${u.name} recebeu ${effects[key].name}.`)}else if(key==='burn'){u.equipment=[];log(`Os equipamentos de ${u.name} foram destruídos.`)}else if(key==='castle'){if(!castleFirst){if(!own(u)||!u.name.includes('Torre'))return hint('Primeiro selecione uma Torre sua.');if(u.faceDown)return hint('Uma Torre virada para baixo não pode realizar o roque.');castleFirst=u;hint('Agora selecione outro peão aliado.');return}else{if(!own(u)||u.id===castleFirst.id)return hint('Selecione outro aliado.');if(u.faceDown)return hint('Peões virados para baixo não podem participar do roque.');let r=castleFirst.row,c=castleFirst.col,towerFrom=boardCoordinate(r,c),allyFrom=boardCoordinate(u.row,u.col);castleFirst.row=u.row;castleFirst.col=u.col;u.row=r;u.col=c;log(`${castleFirst.name} foi de ${towerFrom} para ${allyFrom}; ${u.name} foi para ${towerFrom} no roque.`)}}p.hand.splice(index,1);pendingCard=null;castleFirst=null;render()}
function fusionMaterialFits(card,u,chosen=fusionMaterials){if(!u||u.owner!==state.current||u.row===null||chosen.some(x=>x.id===u.id))return false;if(card.kind==='babel'&&!['tower','infantry'].includes(u.kind))return false;if(card.kind==='babel'&&chosen.some(x=>x.kind===u.kind))return false;if(card.kind==='justice'&&!u.types.includes('LUZ'))return false;if(card.kind==='serpent'&&!u.types.includes('NATURAL'))return false;return !chosen.length||chosen.some(x=>adjacent(x,u))}
function fusionTargets(card){return state.players[state.current].units.filter(u=>fusionMaterialFits(card,u)).map(u=>({r:u.row,c:u.col}))}
function validFusionSet(card,parts){if(parts.length!==card.fusion)return false;if(card.kind==='babel'&&(!parts.some(u=>u.kind==='tower')||!parts.some(u=>u.kind==='infantry')))return false;return parts.every((u,i)=>parts.some((v,j)=>i!==j&&adjacent(u,v)))}
function beginFusion(card=selected){if(!canLocalAct())return hint('Aguarde seu turno.');let p=state.players[state.current];if(!card?.fusion||card.row!==null||!p.reserve.some(u=>u.id===card.id))return hint('Selecione um Peão Combinado na sua mão de Peões.');clearAction();selected=card;mode='combinar';targets=fusionTargets(card);if(!targets.length){clearAction();render();return hint('Não há materiais válidos em campo para iniciar esta combinação.')}render();hint(`Escolha ${card.fusion} materiais em contato · 0/${card.fusion}.`)}
function toggleFusionMaterial(u){let card=selected,index=fusionMaterials.findIndex(x=>x.id===u.id);if(index>=0)fusionMaterials.splice(index,1);else if(fusionMaterialFits(card,u))fusionMaterials.push(u);if(fusionMaterials.length===card.fusion){if(validFusionSet(card,fusionMaterials))return completeFusion(card,[...fusionMaterials]);fusionMaterials.pop();hint('Esses materiais não formam uma sequência em contato.')}targets=fusionTargets(card);renderBoard();hint(`Escolha ${card.fusion} materiais em contato · ${fusionMaterials.length}/${card.fusion}.`)}
function resolveCombination(f,parts,pos,p,version){if(version!==gameVersion)return;clearAnimationMarks(parts);p.units=p.units.filter(u=>!parts.some(x=>x.id===u.id));p.reserve=p.reserve.filter(u=>u.id!==f.id);f.combinedEntry=true;place(f,pos.row,pos.col);p.units.push(f);state.animating=false;clearAction();selected=f;log(`${f.name} foi criado em ${boardCoordinate(pos.row,pos.col)} ao combinar ${f.fusion} materiais em contato.`);render();if(onlineMode)syncOnlineState();setTimeout(()=>{if(version!==gameVersion)return;f.combinedEntry=false;renderBoard()},720)}
function completeFusion(f,parts){if(state.animating)return;let p=state.players[state.current],pos={row:parts[0].row,col:parts[0].col},version=gameVersion;state.animating=true;clearAction();selected=f;parts.forEach(u=>{u.combining=true;u.combineDx=pos.col-u.col;u.combineDy=pos.row-u.row});render();hint(`Combinando ${parts.length} materiais…`);if(onlineMode)sendPacket({type:'visual',kind:'combine',materials:parts.map(u=>u.id),pos});setTimeout(()=>resolveCombination(f,parts,pos,p,version),760)}
function useAbility(){if(!own(selected)||selected.row===null)return hint('Selecione um peão seu com habilidade utilizável.');if(selected.abilityTurn===state.turn)return hint('Esta habilidade já foi usada neste turno.');if(selected.kind==='rider'&&selected.mounted)return hint('Um Montador que já está montado não pode montar outro peão.');if(hasEffect(selected,'serpent')){mode='serpent';targets=[];for(let [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){let r=selected.row+dr,c=selected.col+dc;if(r>=0&&r<ROWS&&c>=0&&c<COLS&&!at(r,c)&&!obstacleAt(r,c))targets.push({r,c})}hint('Escolha uma casa adjacente para o obstáculo NATURAL.')}else if(selected.kind==='jester'){mode='copy';targets=allUnits().filter(u=>u.id!==selected.id&&(u.row===selected.row||u.col===selected.col)).map(u=>({r:u.row,c:u.col}));hint('Escolha um peão na mesma linha ou coluna para copiar seu efeito.')}else if(selected.kind==='rider'){mode='mount';targets=state.players[state.current].units.filter(u=>u.id!==selected.id&&adjacent(selected,u)&&u.name.includes('Selvagem')&&!u.mounted).map(u=>({r:u.row,c:u.col}));hint('Escolha um aliado Selvagem adjacente para montar.')}else return hint('A habilidade deste peão é automática.');if(!targets.length){clearAction();return hint('Não há um alvo válido para esta habilidade.')}renderBoard()}
function createObstacle(u,r,c){state.obstacles.push({row:r,col:c,type:'NATURAL',owner:u.owner});u.abilityTurn=state.turn;log(`${u.name} criou um obstáculo NATURAL.`);clearAction();render()}
function copyEffect(jester,target){jester.copiedKind=target.kind;jester.abilityTurn=state.turn;log(`${jester.name} copiou o efeito de ${target.name} até o fim do turno.`);clearAction();render()}
function mountRider(rider,target){if(!rider||rider.mounted||rider.kind!=='rider'||!target||target.mounted)return hint('Este Montador ou alvo não pode realizar uma nova montagem.');state.players[rider.owner].units=state.players[rider.owner].units.filter(u=>u.id!==rider.id);target.mounted='rider';target.abilityTurn=state.turn;selected=target;log(`${rider.name} montou ${target.name}; seus ataques foram somados.`);clearAction();render()}
function scheduleBot(action,delay=450){clearTimeout(botTimer);let version=gameVersion;botTimer=setTimeout(()=>{if(!botMode||version!==gameVersion||state?.forfeitWinner)return;action()},delay)}
function botPlaceInitial(){if(!botMode||!state.placementPhase||state.placementPlayer!==botPlayer)return;let p=state.players[botPlayer],u=p.initialUnits[0];if(!u)return;selected=u;mode='initial-deploy';targets=initialTargetsFor(botPlayer);let target=[...targets].sort((a,b)=>b.r-a.r||Math.abs(a.c-(COLS-1)/2)-Math.abs(b.c-(COLS-1)/2))[0];if(!target)return;placeInitialPawn(target.r,target.c);if(p.initialUnits.length)scheduleBot(botPlaceInitial,720)}
function botDraw(){let p=state.players[botPlayer];if(p.drawn)return;let field=p.units.filter(u=>u.row!==null).length,drawPawnNow=p.pawnDeck.length&&(field<5||p.reserve.filter(u=>!u.fusion).length<2||!p.effectDeck.length);if(drawPawnNow){p.reserve.push(p.pawnDeck.pop());log('Bot comprou um Peão.')}else if(p.effectDeck.length){p.hand.push(p.effectDeck.pop());log('Bot comprou uma carta de Efeito.')}else if(p.pawnDeck.length){p.reserve.push(p.pawnDeck.pop());log('Bot comprou um Peão.')}p.drawn=true;state.awaitingDraw=false}
function botPlayEffect(){let p=state.players[botPlayer],arenaIndex=p.hand.findIndex(k=>effects[k].type==='ARENA'&&state.arena!==k);if(arenaIndex>=0){let key=p.hand.splice(arenaIndex,1)[0];state.arena=key;state.arenaOwner=botPlayer;state.arenaDefeatedStart=state.defeatedCount||0;log(`Bot ativou a Arena ${effects[key].name}.`);render();return true}let equipmentIndex=p.hand.findIndex(k=>['sword','bow'].includes(k)),equipmentKey=equipmentIndex>=0?p.hand[equipmentIndex]:null,bearer=p.units.filter(u=>u.row!==null&&equipmentKey&&!u.equipment.includes(equipmentKey)).sort((a,b)=>effectiveAtk(b,false)-effectiveAtk(a,false))[0];if(equipmentIndex>=0&&bearer){let key=p.hand.splice(equipmentIndex,1)[0];bearer.equipment.push(key);log(`Bot equipou ${effects[key].name} em ${bearer.name}.`);render();return true}let burnIndex=p.hand.indexOf('burn'),burnTarget=state.players[1].units.find(u=>u.row!==null&&u.equipment.length);if(burnIndex>=0&&burnTarget){p.hand.splice(burnIndex,1);burnTarget.equipment=[];log(`Bot destruiu os equipamentos de ${burnTarget.name}.`);render();return true}return false}
function botDeployPawn(){let p=state.players[botPlayer];if(p.deployed||p.units.filter(u=>u.row!==null).length>=5)return false;let u=p.reserve.find(card=>!card.fusion);if(!u)return false;let cells=[];for(let r of [0,1])for(let c=0;c<COLS;c++)if(!at(r,c)&&!obstacleAt(r,c))cells.push({r,c});let target=cells.sort((a,b)=>b.r-a.r||Math.abs(a.c-(COLS-1)/2)-Math.abs(b.c-(COLS-1)/2))[0];if(!target)return false;selected=u;doDeploy(u,target.r,target.c);return true}
function botMovePawn(){let p=state.players[botPlayer],enemies=state.players[1].units.filter(u=>u.row!==null);if(p.moved||!enemies.length)return false;let choices=[];p.units.filter(u=>u.row!==null&&!u.faceDown).forEach(u=>moveTargets(u).forEach(target=>{let distance=Math.min(...enemies.map(enemy=>Math.abs(target.r-enemy.row)+Math.abs(target.c-enemy.col)));choices.push({u,target,distance})}));let choice=choices.sort((a,b)=>a.distance-b.distance||effectiveAtk(b.u,false)-effectiveAtk(a.u,false))[0];if(!choice)return false;selected=choice.u;doMove(choice.u,choice.target.r,choice.target.c);return true}
function botAttackPawn(){let attackers=state.players[botPlayer].units.filter(u=>u.row!==null),defenders=state.players[1].units.filter(u=>u.row!==null),choices=[];attackers.forEach(attacker=>defenders.forEach(defender=>{if(canAttackTarget(attacker,defender))choices.push({attacker,defender,value:effectiveAtk(attacker,false)-effectiveAtk(defender,true)})}));let choice=choices.sort((a,b)=>b.value-a.value)[0];if(!choice)return false;selected=choice.attacker;doAttack(choice.attacker,choice.defender);return true}
function botTakeTurn(){if(state.current!==botPlayer||state.placementPhase)return;hint('Bot está pensando…');botPlayEffect();let deployed=botDeployPawn();scheduleBot(botMovePhase,deployed?760:380)}
function botMovePhase(){if(state.current!==botPlayer)return;let moved=botMovePawn();scheduleBot(botAttackPhase,moved?650:320)}
function botAttackPhase(){if(state.current!==botPlayer)return;if(state.animating)return scheduleBot(botAttackPhase,250);let attacked=botAttackPawn();scheduleBot(botFinishTurn,attacked?900:320)}
function botFinishTurn(){if(state.current!==botPlayer)return;if(state.animating||state.swordQueue.length)return scheduleBot(botFinishTurn,300);if([1,2].some(n=>state.players[n].score>=GOAL))return checkWin();endTurn()}
function endTurn(){if(botMode&&state.current===botPlayer&&canLocalAct())return;if(state.animating)return hint('Aguarde a animação terminar.');if(state.placementPhase)return;if(state.awaitingDraw)return openDrawChoice();let old=state.current,next=old===1?2:1;state.players[old].units.forEach(u=>delete u.copiedKind);state.players[next].lastLosses=state.players[next].lossesThisTurn;state.players[next].lossesThisTurn=0;state.current=next;state.awaitingDraw=false;if(next===1)state.turn++;let p=state.players[next];p.drawn=state.turn===1;p.deployed=false;p.moved=false;selected=null;selectedEffect=null;clearAction();render();showPass(next,'turn')}
function forfeitGame(){let loser=botMode?1:onlineMode?localPlayer:state.current;if(!loser||state.forfeitWinner||!confirm(`Duelista ${loser}, deseja realmente desistir?`))return;state.forfeitWinner=loser===1?2:1;log(`${state.players[loser].name} desistiu da partida.`);render();checkWin();if(onlineMode)sendGameState(true,true)}
function checkWin(){let winner=state.forfeitWinner||[1,2].find(n=>state.players[n].score>=GOAL);if(!winner)return;let p=state.players[winner],dialog=$('#winner-dialog');$('#winner-name').textContent=`${p.name} · ${archetypes[p.archetype].name}`;$('#winner-score').textContent=state.forfeitWinner?`Vitória por desistência do Duelista ${winner===1?2:1}`:`${p.score} pontos conquistados`;if(!dialog.open)dialog.showModal()}
$('#draw-pawn').onclick=()=>drawPawn($('#draw-pawn'));$('#draw-effect').onclick=()=>drawEffect($('#draw-effect'));$('#choice-pawn').onclick=()=>drawPawn($('#choice-pawn'));$('#choice-effect').onclick=()=>drawEffect($('#choice-effect'));$('#skip-draw').onclick=()=>{let p=state.players[state.current];p.drawn=true;finishDrawChoice();render()};$('#flip').onclick=flipSelected;$('#attack').onclick=beginAttack;$('#ability').onclick=useAbility;$('#end-turn').onclick=endTurn;$('#pass-ready').onclick=()=>{let purpose=state.passPurpose;$('#pass').classList.add('hidden');if(purpose==='placement')beginInitialPlacement(state.placementPlayer);else beginTurn()};$('#forfeit-btn').onclick=forfeitGame;$('#rules-btn').onclick=()=>$('#rules-dialog').showModal();$('.dialog-close').onclick=()=>$('#rules-dialog').close();$('#restart-btn').onclick=()=>{if(onlineMode&&onlineRole!=='host')return sendPacket({type:'restart-request'});if(confirm('Reiniciar o duelo com os mesmos decks?')){newGame();if(onlineMode)sendGameState(true,true)}};$('#winner-restart').onclick=()=>{$('#winner-dialog').close();if(onlineMode){if(onlineRole==='host'){newGame();sendGameState(true,true)}else sendPacket({type:'restart-request'})}else $('#setup').classList.remove('hidden')};
$('.global-arena').onclick=inspectArena;
$$('.deck-choice').forEach(button=>button.onclick=()=>{let row=button.closest('.choice-row'),player=+row.dataset.player;if(onlineMode&&localPlayer&&player!==localPlayer)return;selectedDecks[player]=button.dataset.deck;row.querySelectorAll('.deck-choice').forEach(b=>b.classList.toggle('selected',b===button));onlineDeckChanged(player,button.dataset.deck)});
$('#start-game').onclick=()=>{if(onlineMode)return startOnlineGame();$('#setup').classList.add('hidden');newGame()};
newGame();
