const ROWS=8,COLS=6,GOAL=10;
const defs={
 infantry:{name:'Infantaria do Reino de Xadria',atk:200,movement:[[-2,0],[-1,0],[0,-1],[0,1],[1,0],[2,0]],types:['LUZ','TREVAS'],glyph:'◐',art:'cartas.png',artCrop:{scale:321,x:-150,y:-304},text:'No ataque conjunto, dobra o ATK de um dos participantes.'},
 tower:{name:'Torre Branca de Xadria',atk:150,movement:[[-3,0],[-2,0],[-1,0],[1,0],[2,0],[3,0]],types:['LUZ','PEDRA'],glyph:'▥',art:'cartas.png',artCrop:{scale:346,x:-142,y:-215},text:'Pode se sacrificar para negar um ataque contra aliado adjacente.'},
 jester:{name:'Bobo da Casa Branca de Xadria',atk:100,movement:[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],types:['LUZ'],glyph:'✦',text:'Habilidade: escolhe qualquer peão em campo e mantém o efeito copiado até o fim da partida.'},
 archer:{name:'Arqueiro da Casa Preta de Xadria',atk:250,movement:[[-3,-1],[-3,0],[-3,1],[-2,-2],[-2,2],[-1,-3],[-1,0],[-1,3],[0,-3],[0,-1],[0,1],[0,3],[1,-3],[1,0],[1,3],[2,-2],[2,2],[3,-1],[3,0],[3,1]],types:['LUZ'],glyph:'➹',text:'Só se move quando um Peão adversário estiver em seu caminho e pode atacar qualquer adversário nesse caminho, dentro do raio indicado pela carta.'},
 duck:{name:'Ave Eterna do Reino Xadria',atk:0,movement:[[-3,0],[-2,-1],[-2,0],[-2,1],[-1,-2],[-1,-1],[-1,0],[-1,1],[-1,2],[0,-3],[0,-2],[0,-1],[0,1],[0,2],[0,3],[1,-2],[1,-1],[1,0],[1,1],[1,2],[2,-1],[2,0],[2,1],[3,0]],types:['LUZ','TREVAS','NATURAL'],glyph:'◆',art:'cartas.png',artCrop:{scale:300,x:-193,y:-283},text:'Não é destruída por combate. Pode se mover uma vez por turno sem gastar a ação de movimento.'},
 horse:{name:'Cavalo da Casa Preta de Xadria',atk:250,movement:[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]],types:['TREVAS','NATURAL'],glyph:'♞',text:'Salta seguindo o alcance indicado em sua carta.'},
 rabbit:{name:'Coelho Selvagem',atk:200,movement:[[-3,0],[0,-3],[0,3],[3,0]],types:['NATURAL'],glyph:'●',text:'Salta para uma das quatro casas indicadas no alcance.'},
 rider:{name:'Montador Selvagem',atk:150,movement:[[-1,0],[0,-1],[0,1],[1,0]],types:['NATURAL'],glyph:'⟁',text:'Habilidade: monta um aliado Selvagem adjacente, somando ataque e alcance de ambos.'},
 babel:{name:'Torre Preta de Xadria: Babel',atk:400,movement:[[-3,0],[-2,0],[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1],[2,0],[3,0]],types:['TREVAS','PEDRA'],glyph:'⬟',fusion:2,art:'cartas.png',artCrop:{scale:300,x:-27,y:-67},text:'Inimigos dentro das casas indicadas em seu alcance de movimento têm o ATK reduzido à metade.'},
 justice:{name:'Cavaleiro da Casa Branca: Justiça Alva',atk:300,movement:[[-2,0],[-1,-1],[-1,0],[-1,1],[0,-2],[0,-1],[0,1],[0,2],[1,-1],[1,0],[1,1],[2,0]],types:['LUZ'],glyph:'✧',fusion:2,art:'cartas.png',artCrop:{scale:225,x:-17,y:-190},text:'Seu ATK cresce 100 por aliado derrotado no último turno.'},
 serpent:{name:'Serpente Selvagem',atk:500,movement:[[-2,-1],[-2,0],[-2,1],[-1,-1],[-1,0],[-1,1],[1,0]],types:['NATURAL','LUZ'],glyph:'≈',fusion:3,text:'Habilidade: cria um obstáculo NATURAL adjacente uma vez por turno.'},
 hawk:{name:'Gavião Selvagem',atk:250,movement:[[-2,-2],[-2,2],[-1,-1],[-1,1],[1,0],[2,0]],types:['NATURAL','LUZ'],glyph:'⌁',text:'Habilidade: cria um obstáculo NATURAL adjacente uma vez por turno.'},
 golem:{name:'Golem Selvagem',atk:400,movement:[[-1,0],[0,-2],[0,-1],[0,1],[0,2],[1,0]],types:['NATURAL','LUZ'],glyph:'▰',fusion:2,text:'Pode pisar em obstáculos NATURAIS para destruí-los e ganhar 200 ATK permanentemente.'}
};
const effects={
 retreat:{name:'Recuar!',type:'UTILIDADE',icon:'↩',text:'Escolha um peão; ele retorna ao local onde foi jogado.'},
 castle:{name:'Rocar Torre',type:'UTILIDADE',icon:'⇄',text:'Troque um peão com “Torre” no nome por outro peão aliado.'},
 sword:{name:'Espada Maldita',type:'EQUIPAMENTO',icon:'†',art:'cartas.png',artCrop:{scale:375,x:-271,y:-75},text:'O equipado destrói qualquer rival, mas também cai após o combate. O dono do peão destruído escolhe qualquer outro peão que esteja no campo para receber a espada.'},
 burn:{name:'Queimar Pertences',type:'UTILIDADE',icon:'♨',text:'Destrói todos os equipamentos do peão escolhido.'},
 roses:{name:'Campo das Rosas Pálidas',type:'ARENA',icon:'❀',text:'Peões LUZ ganham 100 ATK enquanto são atacados.'},
 camouflage:{name:'Camuflar-se na Selva',type:'UTILIDADE',icon:'◒',text:'Vira todos os peões aliados em campo para baixo.'},
 jungle:{name:'Selva Selvagem',type:'ARENA',icon:'♣',text:'No início de cada turno cria um obstáculo NATURAL ou, com 50% de chance, uma fruta. Quem pisa na fruta ganha 100 ATK.'},
 bow:{name:'Arco Selvagem',type:'EQUIPAMENTO',icon:'➶',text:'O equipado pode atacar inimigos nas casas indicadas em seu próprio alcance de movimento, além do ataque adjacente normal.'},
 pit:{name:'Poço sem Fundo',type:'UTILIDADE',icon:'◉',text:'Coloque um poço em qualquer casa livre da Arena. O peão que pisar nele é destruído.'}
};
const archetypes={
 xadria:{name:'Xadria',emblem:'◐',pawns:['infantry','tower','jester','archer','duck','horse'],fusions:['babel','justice'],starters:['infantry','tower','jester'],effects:['retreat','castle','sword','burn','roses','pit']},
 wild:{name:'Selvagem',emblem:'✿',pawns:['rabbit','rider','hawk'],fusions:['serpent','golem'],starters:['rabbit','rider','rabbit'],effects:['camouflage','jungle','bow','retreat','burn','pit']}
};
let selectedDecks={1:'xadria',2:'wild'};
let state,selected=null,selectedEffect=null,mode=null,targets=[],pendingCard=null,castleFirst=null,fusionMaterials=[],gameVersion=0,botMode=false,botPlayer=2,botTimer=null,lastArenaVisual='none',arenaAnimationTimer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function uid(){return Math.random().toString(36).slice(2,9)}
function unit(kind,owner){let d=defs[kind];return{id:uid(),kind,owner,row:null,col:null,origin:null,faceDown:false,flippedTurn:0,movedTurn:0,attackedTurn:0,equipment:[],abilityTurn:0,mounted:null,...d}}
function artStyle(item){let crop=item?.artCrop;return crop?` style="--art-scale:${crop.scale}%;--art-x:${crop.x}%;--art-y:${crop.y}%"`:''}
function artVisual(item,context=''){return item?.art?`<span class="art-crop ${context}"><img src="${item.art}" alt="Arte de ${item.name}"${artStyle(item)}></span>`:''}
function unitVisual(u,context=''){return u.art?artVisual(u,context):`<span class="glyph">${u.glyph}</span>`}
function rawMovementOffsets(u){let offsets=[...(u.movement||[])];if(u.mounted)offsets.push(...(defs[u.mounted].movement||[]));let seen=new Set;return offsets.filter(([dr,dc])=>{let key=`${dr},${dc}`;if(seen.has(key))return false;seen.add(key);return true})}
function movementOffsets(u){let direction=u.owner===2?-1:1;return rawMovementOffsets(u).map(([dr,dc])=>[dr*direction,dc*direction])}
function movementPreview(u){let active=new Set(rawMovementOffsets(u).map(([dr,dc])=>`${dr},${dc}`)),cells=[];for(let dr=-3;dr<=3;dr++)for(let dc=-3;dc<=3;dc++)cells.push(`<span class="${dr===0&&dc===0?'origin':active.has(`${dr},${dc}`)?'reach':''}"></span>`);return `<div class="movement-label">ALCANCE</div><div class="movement-preview" aria-label="Alcance de movimento">${cells.join('')}</div>`}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makePawnDeck(owner,key){let arc=archetypes[key],fusionSlots=key==='xadria'?4:3,commonSlots=18-fusionSlots,cards=Array.from({length:commonSlots},(_,i)=>unit(arc.pawns[i%arc.pawns.length],owner));for(let i=0;i<fusionSlots;i++)cards.push(unit(arc.fusions[i%arc.fusions.length],owner));return shuffle(cards)}
function makeEffectDeck(key){let pool=archetypes[key].effects;return shuffle(Array.from({length:20},(_,i)=>pool[i%pool.length]))}
function newGame(){
 let version=++gameVersion;
 if($('#winner-dialog')?.open)$('#winner-dialog').close();
 selected=null;selectedEffect=null;
 state={turn:1,current:1,players:{},obstacles:[],pits:[],log:[],animating:false,initialDeal:true,awaitingDraw:false,arena:null,arenaOwner:null,arenaDefeatedStart:0,swordQueue:[],defeatedCount:0,placementPhase:true,placementPlayer:1,passPurpose:null,forfeitWinner:null};
 clearTimeout(botTimer);botTimer=null;clearTimeout(arenaAnimationTimer);arenaAnimationTimer=null;lastArenaVisual='none';
 for(let p=1;p<=2;p++){let key=selectedDecks[p],player=state.players[p]={name:botMode&&p===botPlayer?'Bot':`Duelista ${p}`,archetype:key,score:0,units:[],initialUnits:[],hand:[],reserve:[],arena:null,drawn:true,deployed:false,moved:false,lastLosses:0,lossesThisTurn:0,pawnDeck:makePawnDeck(p,key),effectDeck:makeEffectDeck(key)};for(let i=0;i<3;i++)player.hand.push(player.effectDeck.pop());archetypes[key].starters.forEach(kind=>{let index=player.pawnDeck.findIndex(u=>u.kind===kind),u=index>=0?player.pawnDeck.splice(index,1)[0]:unit(kind,p);u.initial=true;player.initialUnits.push(u)})}
 log('Preparação: escolha onde posicionar os três peões iniciais.');clearAction();render();beginInitialPlacement(1);setTimeout(()=>{if(version!==gameVersion)return;state.initialDeal=false;renderHands()},1300);
}
function initialTargetsFor(player){let rows=player===1?[ROWS-2,ROWS-1]:[0,1],out=[];for(let r of rows)for(let c=0;c<COLS;c++)if(!at(r,c)&&!obstacleAt(r,c)&&!pitAt(r,c))out.push({r,c});return out}
function beginInitialPlacement(player){state.current=player;state.placementPlayer=player;state.placementPhase=true;selectedEffect=null;selected=state.players[player].initialUnits[0]||null;clearAction();mode='initial-deploy';targets=initialTargetsFor(player);render();hint(`${state.players[player].name}: escolha uma casa destacada para cada peão inicial.`)}
function placeInitialPawn(r,c){let p=state.players[state.placementPlayer],u=selected,version=gameVersion;if(!u||!u.initial||u.owner!==state.placementPlayer)return;place(u,r,c);u.initial=false;u.deployed=true;p.initialUnits=p.initialUnits.filter(x=>x.id!==u.id);p.units.push(u);log(`${p.name} posicionou ${u.name} em ${boardCoordinate(r,c)}.`);if(p.initialUnits.length){selected=p.initialUnits[0];targets=initialTargetsFor(state.placementPlayer);render();hint(`Posicione os ${p.initialUnits.length} peões iniciais restantes.`);setTimeout(()=>{if(version!==gameVersion)return;u.deployed=false;renderBoard()},650);return}selected=null;clearAction();render();hint(`${p.name} concluiu sua preparação.`);setTimeout(()=>{if(version!==gameVersion)return;u.deployed=false;if(state.placementPlayer===1){state.placementPlayer=2;state.current=2;render();showPass(2,'placement')}else{state.placementPhase=false;state.current=1;render();showPass(1,'start')}},620)}
function showPass(player,purpose){let p=state.players[player],a=archetypes[p.archetype];state.passPurpose=purpose;if(onlineMode){render();syncOnlineState(true);if(player===localPlayer){if(purpose==='placement')beginInitialPlacement(player);else beginTurn()}else updateOnlineLock();return}if(botMode){$('#pass').classList.add('hidden');if(player===botPlayer&&purpose==='placement'){beginInitialPlacement(player);scheduleBot(botPlaceInitial,500)}else beginTurn();return}$('#pass-name').textContent=`${p.name} · ${a.name}`;$('#pass .crest').textContent=a.emblem;$('#pass').classList.remove('hidden')}
function beginTurn(){let p=state.players[state.current];state.passPurpose=null;if(state.arena==='jungle')spawnJungleFeature();if(state.turn===1){state.awaitingDraw=false;p.drawn=true;render();hint(botMode&&state.current===botPlayer?'O Bot está pensando…':'Rodada 1: nenhum jogador compra cartas ou peões.')}else if(botMode&&state.current===botPlayer){botDraw();render()}else{p.drawn=false;openDrawChoice()}if(botMode&&state.current===botPlayer)scheduleBot(botTakeTurn,650)}
function place(u,r,c){u.row=r;u.col=c;if(!u.origin)u.origin={row:r,col:c}}
function boardCoordinate(r,c){return `${String.fromCharCode(65+c)}${r+1}`}
function allUnits(){return[...state.players[1].units,...state.players[2].units]}
function at(r,c){return allUnits().find(u=>u.row===r&&u.col===c)}
function featureAt(r,c){return (state.obstacles||[]).find(o=>o.row===r&&o.col===c)}
function obstacleAt(r,c){let feature=featureAt(r,c);return feature?.type!=='FRUIT'?feature:null}
function fruitAt(r,c){let feature=featureAt(r,c);return feature?.type==='FRUIT'?feature:null}
function pitAt(r,c){return (state.pits||[]).find(p=>p.row===r&&p.col===c)}
function own(u){return u&&u.owner===state.current}
function viewPlayerNumber(){return botMode?1:onlineMode&&localPlayer?localPlayer:state.current}
function perspectivePlayer(){return botMode?1:onlineMode&&localPlayer?localPlayer:state.current}
function canLocalAct(){if(state?.animating)return false;if(botMode)return state.swordQueue?.length?state.swordQueue[0]!==botPlayer:state.current!==botPlayer;return !onlineMode||(state.swordQueue?.length?state.swordQueue[0]===localPlayer:state.current===localPlayer)}
function adjacent(a,b){return Math.abs(a.row-b.row)+Math.abs(a.col-b.col)===1}
function log(msg){state.log.unshift({turn:state.turn,msg});state.log=state.log.slice(0,40)}
function hint(t){$('#hint').textContent=t}
function clearAction(){mode=null;targets=[];pendingCard=null;castleFirst=null;fusionMaterials=[];$$('.action').forEach(b=>b.classList.remove('active'))}
function select(u){clearAction();selectedEffect=null;selected=u;render();hint(u?`${u.name} selecionado.`:'Seleção removida.')}
function startMode(m,valid,msg){if(!valid){hint(msg);return}mode=m;targets=[];$$('.action').forEach(b=>b.classList.remove('active'));$('#'+m)?.classList.add('active');hint(msg);renderBoard()}
function render(){renderHeader();renderBoard();renderHands();renderCard();renderLog();if(onlineMode)updateOnlineLock()}
function updateArenaTheme(board){let arenaSlot=$('.global-arena'),arenaKey=state.arena||'none',changed=arenaKey!==lastArenaVisual;board.dataset.arena=arenaKey;arenaSlot.dataset.arena=arenaKey;if(changed&&arenaKey!=='none'){clearTimeout(arenaAnimationTimer);[board,arenaSlot].forEach(el=>{el.classList.remove('arena-changing');void el.offsetWidth;el.classList.add('arena-changing')});arenaAnimationTimer=setTimeout(()=>[board,arenaSlot].forEach(el=>el.classList.remove('arena-changing')),900)}lastArenaVisual=arenaKey}
function renderHeader(){
 let active=state.players[state.current],view=state.players[viewPlayerNumber()],arc=archetypes[active.archetype],board=$('#board'),locked=state.placementPhase,busy=state.animating,waiting=!canLocalAct();
 let perspective=perspectivePlayer(),layout=$('.game-layout'),handZone=$('.hand-zone');$('main').insertBefore($(`#p${perspective===1?2:1}-strip`),layout);$('main').insertBefore($(`#p${perspective}-strip`),handZone);
 $('#turn-count').textContent=locked?'PREPARAÇÃO':`TURNO ${state.turn}`;$('#turn-name').textContent=`${active.name.toUpperCase()} · ${arc.name.toUpperCase()}`;$('#phase-label').textContent=busy?'Resolvendo animação':waiting?'Aguardando adversário':locked?'Posicione os peões iniciais':state.awaitingDraw?'Escolha uma pilha':mode?`Ação: ${mode}`:'Escolha sua��˨ѩ춻Ǳ˞��.filter(u=>!parts.some(x=>x.id===u.id));p.reserve=p.reserve.filter(u=>u.id!==f.id);f.combinedEntry=true;place(f,pos.row,pos.col);p.units.push(f);state.animating=false;clearAction();selected=f;log(`${f.name} foi criado em ${boardCoordinate(pos.row,pos.col)} ao combinar ${f.fusion} materiais em contato.`);render();if(onlineMode)syncOnlineState();setTimeout(()=>{if(version!==gameVersion)return;f.combinedEntry=false;renderBoard()},720)}
function completeFusion(f,parts){if(state.animating)return;let p=state.players[state.current],pos={row:parts[0].row,col:parts[0].col},version=gameVersion;state.animating=true;clearAction();selected=f;parts.forEach(u=>{u.combining=true;u.combineDx=pos.col-u.col;u.combineDy=pos.row-u.row});render();hint(`Combinando ${parts.length} materiais…`);if(onlineMode)sendPacket({type:'visual',kind:'combine',materials:parts.map(u=>u.id),pos});setTimeout(()=>resolveCombination(f,parts,pos,p,version),760)}
function useAbility(){
 if(!own(selected)||selected.row===null)return hint('Selecione um peão seu com habilidade utilizável.');if(selected.abilityTurn===state.turn)return hint('Esta habilidade já foi usada neste turno.');if(hasEffect(selected,'rider')&&selected.mounted)return hint('Um Montador que já está montado não pode montar outro peão.');
 if(hasEffect(selected,'serpent')||hasEffect(selected,'hawk')){mode='serpent';targets=[];for(let [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){let r=selected.row+dr,c=selected.col+dc;if(r>=0&&r<ROWS&&c>=0&&c<COLS&&!at(r,c)&&!featureAt(r,c)&&!pitAt(r,c))targets.push({r,c})}hint('Escolha uma casa adjacente para o obstáculo NATURAL.')}else if(selected.kind==='jester'&&!selected.copiedKind){mode='copy';targets=allUnits().filter(u=>u.id!==selected.id&&u.row!==null).map(u=>({r:u.row,c:u.col}));hint('Escolha qualquer peão em campo para copiar seu efeito até o fim da partida.')}else if(hasEffect(selected,'rider')){mode='mount';targets=state.players[state.current].units.filter(u=>u.id!==selected.id&&adjacent(selected,u)&&u.name.includes('Selvagem')&&!u.mounted).map(u=>({r:u.row,c:u.col}));hint('Escolha um aliado Selvagem adjacente para montar.')}else return hint(selected.kind==='jester'?'O Bobo já mantém o efeito copiado até o fim da partida.':'A habilidade deste peão é automática.');if(!targets.length){clearAction();return hint('Não há um alvo válido para esta habilidade.')}renderBoard()
}
function createObstacle(u,r,c){state.obstacles.push({row:r,col:c,type:'NATURAL',owner:u.owner});u.abilityTurn=state.turn;log(`${u.name} criou um obstáculo NATURAL.`);clearAction();render()}
function spawnJungleFeature(){let free=[];for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(!at(r,c)&&!featureAt(r,c)&&!pitAt(r,c))free.push({r,c});if(!free.length)return;let pos=free[Math.floor(Math.random()*free.length)],fruit=Math.random()<.5;state.obstacles.push({row:pos.r,col:pos.c,type:fruit?'FRUIT':'NATURAL',owner:state.arenaOwner});log(`A Selva Selvagem criou ${fruit?'uma fruta':'um obstáculo NATURAL'} em ${boardCoordinate(pos.r,pos.c)}.`)}
function copyEffect(jester,target){jester.copiedKind=target.kind;jester.abilityTurn=state.turn;log(`${jester.name} copiou o efeito de ${target.name} até o fim da partida.`);clearAction();render()}
function mountRider(rider,target){if(!rider||rider.mounted||!hasEffect(rider,'rider')||!target||target.mounted)return hint('Este Montador ou alvo não pode realizar uma nova montagem.');state.players[rider.owner].units=state.players[rider.owner].units.filter(u=>u.id!==rider.id);target.mounted='rider';target.abilityTurn=state.turn;selected=target;log(`${rider.name} montou ${target.name}; seus ataques foram somados.`);clearAction();render()}
function scheduleBot(action,delay=450){clearTimeout(botTimer);let version=gameVersion;botTimer=setTimeout(()=>{if(!botMode||version!==gameVersion||state?.forfeitWinner)return;action()},delay)}
function botPlaceInitial(){if(!botMode||!state.placementPhase||state.placementPlayer!==botPlayer)return;let p=state.players[botPlayer],u=p.initialUnits[0];if(!u)return;selected=u;mode='initial-deploy';targets=initialTargetsFor(botPlayer);let target=[...targets].sort((a,b)=>b.r-a.r||Math.abs(a.c-(COLS-1)/2)-Math.abs(b.c-(COLS-1)/2))[0];if(!target)return;placeInitialPawn(target.r,target.c);if(p.initialUnits.length)scheduleBot(botPlaceInitial,720)}
function botDraw(){let p=state.players[botPlayer];if(p.drawn)return;let field=p.units.filter(u=>u.row!==null).length,drawPawnNow=p.pawnDeck.length&&(field<5||p.reserve.filter(u=>!u.fusion).length<2||!p.effectDeck.length);if(drawPawnNow){p.reserve.push(p.pawnDeck.pop());log('Bot comprou um Peão.')}else if(p.effectDeck.length){p.hand.push(p.effectDeck.pop());log('Bot comprou uma carta de Efeito.')}else if(p.pawnDeck.length){p.reserve.push(p.pawnDeck.pop());log('Bot comprou um Peão.')}p.drawn=true;state.awaitingDraw=false}
function botPlayEffect(){let p=state.players[botPlayer],arenaIndex=p.hand.findIndex(k=>effects[k].type==='ARENA'&&state.arena!==k);if(arenaIndex>=0){let key=p.hand.splice(arenaIndex,1)[0];state.arena=key;state.arenaOwner=botPlayer;state.arenaDefeatedStart=state.defeatedCount||0;log(`Bot ativou a Arena ${effects[key].name}.`);render();return true}let equipmentIndex=p.hand.findIndex(k=>['sword','bow'].includes(k)),equipmentKey=equipmentIndex>=0?p.hand[equipmentIndex]:null,bearer=p.units.filter(u=>u.row!==null&&equipmentKey&&!u.equipment.includes(equipmentKey)).sort((a,b)=>effectiveAtk(b,false)-effectiveAtk(a,false))[0];if(equipmentIndex>=0&&bearer){let key=p.hand.splice(equipmentIndex,1)[0];bearer.equipment.push(key);log(`Bot equipou ${effects[key].name} em ${bearer.name}.`);render();return true}let burnIndex=p.hand.indexOf('burn'),burnTarget=state.players[1].units.find(u=>u.row!==null&&u.equipment.length);if(burnIndex>=0&&burnTarget){p.hand.splice(burnIndex,1);burnTarget.equipment=[];log(`Bot destruiu os equipamentos de ${burnTarget.name}.`);render();return true}return false}
function botDeployPawn(){let p=state.players[botPlayer];if(p.deployed||p.units.filter(u=>u.row!==null).length>=5)return false;let u=p.reserve.find(card=>!card.fusion);if(!u)return false;let cells=[];for(let r of [0,1])for(let c=0;c<COLS;c++)if(!at(r,c)&&!obstacleAt(r,c))cells.push({r,c});let target=cells.sort((a,b)=>b.r-a.r||Math.abs(a.c-(COLS-1)/2)-Math.abs(b.c-(COLS-1)/2))[0];if(!target)return false;selected=u;doDeploy(u,target.r,target.c);return true}
function combinationsOf(items,size,start=0,picked=[],out=[]){if(picked.length===size){out.push([...picked]);return out}for(let i=start;i<=items.length-(size-picked.length);i++){picked.push(items[i]);combinationsOf(items,size,i+1,picked,out);picked.pop()}return out}
function botCombinePawn(){let p=state.players[botPlayer],options=[];p.reserve.filter(card=>card.fusion).forEach(card=>{let candidates=p.units.filter(u=>fusionMaterialFits(card,u,[]));combinationsOf(candidates,card.fusion).filter(parts=>validFusionSet(card,parts)).forEach(parts=>options.push({card,parts,value:card.fusion*1000+card.atk-parts.reduce((sum,u)=>sum+u.atk+u.equipment.length*300,0)}))});let choice=options.sort((a,b)=>b.value-a.value)[0];if(!choice)return false;selected=choice.card;completeFusion(choice.card,choice.parts);return true}
function botUseMount(){let p=state.players[botPlayer],choices=[];p.units.filter(u=>u.kind==='rider'&&u.row!==null&&!u.mounted).forEach(rider=>p.units.filter(target=>target.id!==rider.id&&target.row!==null&&adjacent(rider,target)&&target.name.includes('Selvagem')&&!target.mounted).forEach(target=>choices.push({rider,target,value:effectiveAtk(target,false)+rawMovementOffsets(target).length*10})));let choice=choices.sort((a,b)=>b.value-a.value)[0];if(!choice)return false;mountRider(choice.rider,choice.target);return true}
function groupAttackPower(attacker,defender){let allies=[attacker,...state.players[attacker.owner].units.filter(u=>u.id!==attacker.id&&u.row!==null&&!u.faceDown&&adjacent(u,defender))],attack=allies.reduce((sum,u)=>sum+effectiveAtk(u,false),0);if(allies.length>1&&allies.some(u=>hasEffect(u,'infantry')))attack+=Math.max(...allies.map(u=>effectiveAtk(u,false)));return attack}
function botAttackChoices(){let p=state.players[botPlayer],attackers=p.units.filter(u=>u.row!==null&&!u.faceDown&&u.attackedTurn!==state.turn),defenders=state.players[1].units.filter(u=>u.row!==null&&!hasEffect(u,'duck')),choices=[];attackers.forEach(attacker=>defenders.forEach(defender=>{if(!canAttackTarget(attacker,defender))return;let attack=groupAttackPower(attacker,defender),defense=effectiveAtk(defender,true);if(defender.faceDown||attack>defense)choices.push({attacker,defender,attack,defense,value:defender.faceDown?150:(defender.fusion||1)*1000+defense+attack-defense})}));return choices.sort((a,b)=>b.value-a.value)}
function botMoveRisk(u){if(hasEffect(u,'duck'))return 0;let defense=effectiveAtk(u,true),threats=state.players[1].units.filter(attacker=>attacker.row!==null&&!attacker.faceDown&&canAttackTarget(attacker,u)).map(attacker=>{let attack=groupAttackPower(attacker,u);return attack>=defense?attack-defense+1:0});return Math.max(0,...threats)}
function botBestMovePlan(){let p=state.players[botPlayer],enemies=state.players[1].units.filter(u=>u.row!==null);if(p.moved||!enemies.length)return null;let plans=[];p.units.filter(u=>u.row!==null&&!u.faceDown&&(!hasEffect(u,'archer')||canArcherMove(u))).forEach(u=>moveTargets(u).forEach(target=>{let row=u.row,col=u.col;u.row=target.r;u.col=target.c;let attacks=botAttackChoices(),attackValue=attacks[0]?.value||0,risk=botMoveRisk(u),distance=Math.min(...enemies.map(enemy=>Math.abs(target.r-enemy.row)+Math.abs(target.c-enemy.col)));u.row=row;u.col=col;plans.push({u,target,attackValue,risk,distance,score:attackValue*100-risk*1000-distance*10+effectiveAtk(u,false)/100})}));let safe=plans.filter(plan=>plan.risk===0);return safe.sort((a,b)=>b.score-a.score)[0]||null}
function botMovePawn(plan=botBestMovePlan()){if(!plan)return false;selected=plan.u;doMove(plan.u,plan.target.r,plan.target.c);return true}
function botAttackPawn(){let choice=botAttackChoices()[0];if(!choice)return false;selected=choice.attacker;doAttack(choice.attacker,choice.defender);return true}
function botTakeTurn(){if(state.current!==botPlayer||state.placementPhase)return;hint('Bot está pensando…');scheduleBot(botCombinationPhase,260)}
function botCombinationPhase(){if(state.current!==botPlayer)return;if(state.animating)return scheduleBot(botCombinationPhase,250);let combined=botCombinePawn();scheduleBot(combined?botCombinationPhase:botAfterCombinationPhase,combined?940:180)}
function botAfterCombinationPhase(){if(state.current!==botPlayer)return;botPlayEffect();let deployed=botDeployPawn();scheduleBot(botAbilityPhase,deployed?760:380)}
function botAbilityPhase(){if(state.current!==botPlayer)return;let mounted=botUseMount();scheduleBot(botPreMoveAttackPhase,mounted?520:220)}
function botPreMoveAttackPhase(){if(state.current!==botPlayer)return;if(state.animating)return scheduleBot(botPreMoveAttackPhase,250);let current=botAttackChoices(),movePlan=botBestMovePlan(),attackFirst=current.length&&(!movePlan||movePlan.attackValue<=current[0].value);if(!attackFirst)return botMovePhase(movePlan);let attacked=botAttackPawn();scheduleBot(attacked?botPreMoveAttackPhase:botMovePhase,attacked?900:260)}
function botMovePhase(plan=null){if(state.current!==botPlayer)return;let moved=botMovePawn(plan||botBestMovePlan());scheduleBot(botAttackPhase,moved?650:320)}
function botAttackPhase(){if(state.current!==botPlayer)return;if(state.animating)return scheduleBot(botAttackPhase,250);let attacked=botAttackPawn();scheduleBot(attacked?botAttackPhase:botFinishTurn,attacked?900:320)}
function botFinishTurn(){if(state.current!==botPlayer)return;if(state.animating||state.swordQueue.length)return scheduleBot(botFinishTurn,300);if([1,2].some(n=>state.players[n].score>=GOAL))return checkWin();endTurn()}
function endTurn(){if(botMode&&state.current===botPlayer&&canLocalAct())return;if(state.animating)return hint('Aguarde a animação terminar.');if(state.placementPhase)return;if(state.awaitingDraw)return openDrawChoice();let old=state.current,next=old===1?2:1;state.players[next].lastLosses=state.players[next].lossesThisTurn;state.players[next].lossesThisTurn=0;state.current=next;state.awaitingDraw=false;if(next===1)state.turn++;let p=state.players[next];p.drawn=state.turn===1;p.deployed=false;p.moved=false;selected=null;selectedEffect=null;clearAction();render();showPass(next,'turn')}
function forfeitGame(){let loser=botMode?1:onlineMode?localPlayer:state.current;if(!loser||state.forfeitWinner||!confirm(`Duelista ${loser}, deseja realmente desistir?`))return;state.forfeitWinner=loser===1?2:1;log(`${state.players[loser].name} desistiu da partida.`);render();checkWin();if(onlineMode)sendGameState(true,true)}
function checkWin(){let winner=state.forfeitWinner||[1,2].find(n=>state.players[n].score>=GOAL);if(!winner)return;let p=state.players[winner],dialog=$('#winner-dialog');$('#winner-name').textContent=`${p.name} · ${archetypes[p.archetype].name}`;$('#winner-score').textContent=state.forfeitWinner?`Vitória por desistência do Duelista ${winner===1?2:1}`:`${p.score} pontos conquistados`;if(!dialog.open)dialog.showModal()}
$('#draw-pawn').onclick=()=>drawPawn($('#draw-pawn'));$('#draw-effect').onclick=()=>drawEffect($('#draw-effect'));$('#choice-pawn').onclick=()=>drawPawn($('#choice-pawn'));$('#choice-effect').onclick=()=>drawEffect($('#choice-effect'));$('#skip-draw').onclick=()=>{let p=state.players[state.current];p.drawn=true;finishDrawChoice();render()};$('#flip').onclick=flipSelected;$('#attack').onclick=beginAttack;$('#ability').onclick=useAbility;$('#end-turn').onclick=endTurn;$('#pass-ready').onclick=()=>{let purpose=state.passPurpose;$('#pass').classList.add('hidden');if(purpose==='placement')beginInitialPlacement(state.placementPlayer);else beginTurn()};$('#forfeit-btn').onclick=forfeitGame;$('#rules-btn').onclick=()=>$('#rules-dialog').showModal();$('.dialog-close').onclick=()=>$('#rules-dialog').close();$('#restart-btn').onclick=()=>{if(onlineMode&&onlineRole!=='host')return sendPacket({type:'restart-request'});if(confirm('Reiniciar o duelo com os mesmos decks?')){newGame();if(onlineMode)sendGameState(true,true)}};$('#winner-restart').onclick=()=>{$('#winner-dialog').close();if(onlineMode){if(onlineRole==='host'){newGame();sendGameState(true,true)}else sendPacket({type:'restart-request'})}else $('#setup').classList.remove('hidden')};
$('.global-arena').onclick=inspectArena;
$$('.deck-choice').forEach(button=>button.onclick=()=>{let row=button.closest('.choice-row'),player=+row.dataset.player;if(onlineMode&&localPlayer&&player!==localPlayer)return;selectedDecks[player]=button.dataset.deck;row.querySelectorAll('.deck-choice').forEach(b=>b.classList.toggle('selected',b===button));onlineDeckChanged(player,button.dataset.deck)});
$('#start-game').onclick=()=>{if(onlineMode)return startOnlineGame();$('#setup').classList.add('hidden');newGame()};
newGame();
