const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(`${__dirname}/engine-actions-a.js`,'utf8');
const ctx={document:{documentElement:{lang:'pt-BR'}}};
vm.createContext(ctx);
vm.runInContext(source.slice(0,source.indexOf('function cleanChatMessage')),ctx);
vm.runInContext(source.slice(source.indexOf('function renderLogEntry'),source.indexOf('function renderLog(){')),ctx);
let html=ctx.renderLogEntry({turn:6,msg:'Joaninha venceu (350 × 200). · Duelista 1 +1 ponto',type:'combat'});
assert.match(html,/log-combat/);assert.match(html,/Combate/);assert.match(html,/log-result/);assert.match(html,/350 × 200/);
assert.match(ctx.renderLogEntry({turn:6,msg:'Duelista 1 recebeu 2 pontos.',type:'system'}),/log-score/);
assert.match(ctx.renderLogEntry({turn:7,msg:'Infantaria moveu de B7 para A5.',type:'move'},true),/log-turn-start/);
html=ctx.renderLogEntry({turn:6,msg:'<img src=x onerror=alert(1)> · Eu +2 pontos',sender:'<b>Teste</b>',type:'chat'});
assert.ok(!html.includes('<img'));assert.ok(!html.includes('log-result'));assert.match(html,/&lt;b&gt;/);
assert.match(ctx.renderLogEntry({turn:1,msg:'Teste',type:'evil" onclick="x'}),/log-system/);
ctx.document.documentElement.lang='en';
assert.match(ctx.renderLogEntry({turn:1,msg:'Test',type:'deploy'}),/Deployment/);
// Existing history ordering and scroll anchoring are intentionally retained.
assert.match(source,/mobile\?state.log:\[\.\.\.state.log\]\.reverse\(\)/);
assert.match(source,/oldTop\+\(el.scrollHeight-oldHeight\)/);
const logElement={scrollHeight:500,scrollTop:100,clientHeight:100,_html:'',set innerHTML(value){this._html=value;this.scrollHeight=600},get innerHTML(){return this._html}};
ctx.$=()=>logElement;
ctx.window={matchMedia:()=>({matches:false})};
ctx.state={log:[{turn:2,msg:'new',type:'system'},{turn:1,msg:'old',type:'system'}]};
vm.runInContext(source.match(/^function renderLog\(\).*$/m)[0],ctx);
ctx.renderLog();
assert.equal(logElement.scrollTop,100,'desktop preserves a reader’s scroll position');
assert.ok(logElement.innerHTML.indexOf('old')<logElement.innerHTML.indexOf('new'));
logElement.scrollHeight=500;logElement.scrollTop=400;ctx.renderLog();
assert.equal(logElement.scrollTop,600,'desktop follows when already at the end');
ctx.window.matchMedia=()=>({matches:true});
logElement.scrollHeight=500;logElement.scrollTop=100;ctx.renderLog();
assert.equal(logElement.scrollTop,200,'mobile anchors older entries after prepend');
assert.ok(logElement.innerHTML.indexOf('new')<logElement.innerHTML.indexOf('old'));
logElement.scrollTop=0;ctx.renderLog();assert.equal(logElement.scrollTop,0);
console.log('Identity and combat journal tests passed.');
